# MultiMend — Kaggle A→Z baseline reproduction (first benchmark: QuixBugs-Python)

**Scope:** official MultiMend repository + official fine-tuned checkpoints + official QuixBugs benchmark.

This notebook deliberately does **not** run all six benchmarks. It first validates the complete pipeline on QuixBugs-Python:

`buggy/correct programs → official bug-line/context extraction → local RAG → CodeT5 checkpoint ensemble → 100 candidates/checkpoint → combine/deduplicate → patch validation → CSV/JSON summary`

No OpenAI/Claude/Gemini API is used. The model and the RAG embedding model are downloaded locally from Hugging Face.

In [7]:
from pathlib import Path
import shutil

repo = Path("/kaggle/working/MultiMend28")

if repo.exists():
    shutil.rmtree(repo)

print("Old repository removed.")

Old repository removed.

In [8]:
# Cell 1 — Kaggle setup
import os
import subprocess
import sys
from pathlib import Path

REPO_URL = "https://github.com/ThaoTo2806/MultiMend28.git"
REPO = Path("/kaggle/working/MultiMend28")

if not REPO.exists():
    subprocess.run(["git", "clone", "--depth", "1", REPO_URL, str(REPO)], check=True)

os.chdir(REPO)
print("Repository:", REPO)
print("Commit:", subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip())
print("Python:", sys.version)

try:
    import torch
    print("Torch:", torch.__version__)
    print("CUDA available:", torch.cuda.is_available())
    if torch.cuda.is_available():
        print("GPU:", torch.cuda.get_device_name(0))
except ImportError:
    print("Torch will be checked after dependency installation.")

Cloning into '/kaggle/working/MultiMend28'...

Repository: /kaggle/working/MultiMend28
Commit: 08c0c75f5331f54616a083267e501f21713c6047
Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Torch: 2.4.0+cu121
CUDA available: True
GPU: Tesla T4

In [5]:
# Cell 1 — Kaggle environment
import os, sys, subprocess, textwrap, json, pathlib, shutil, time
from pathlib import Path

print("Python:", sys.version)
print("CUDA_VISIBLE_DEVICES:", os.environ.get("CUDA_VISIBLE_DEVICES"))
try:
    import torch
    print("Torch:", torch.__version__)
    print("CUDA available:", torch.cuda.is_available())
    if torch.cuda.is_available():
        print("GPU:", torch.cuda.get_device_name(0))
except Exception as e:
    print("Torch import error:", repr(e))

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
CUDA_VISIBLE_DEVICES: None
Torch: 2.4.0+cu121
CUDA available: True
GPU: Tesla T4

In [9]:
# Cell 2 — Install the repository dependencies
subprocess.run(
    [
        sys.executable, "-m", "pip", "install", "-q", "--no-cache-dir",
        "-r", "requirements.txt", "more-itertools", "pygments",
    ],
    check=True,
)
print("Dependencies installed.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 1.1 MB/s eta 0:00:00
Dependencies installed.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
diffusers 0.37.1 requires huggingface-hub<2.0,>=0.34.0, but you have huggingface-hub 0.27.1 which is incompatible.
torchaudio 2.10.0+cu128 requires torch==2.10.0, but you have torch 2.4.0 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.6.1 which is incompatible.
gradio 5.50.0 requires huggingface-hub<2.0,>=0.33.5, but you have huggingface-hub 0.27.1 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.3.0 which is incompatible.
gradio 5.50.0 requires pydantic<=2.12.3,>=2.0, but you have pydantic 2.13.5 which is incompatible.

In [10]:
# Download QuixBugs if it is not already present
QB_DIR = REPO / "benchmarks" / "QuixBugs"

if not (QB_DIR / "python_programs").is_dir():
    QB_DIR.parent.mkdir(parents=True, exist_ok=True)

    !git clone https://github.com/jkoppel/QuixBugs.git "{QB_DIR}"

print("QuixBugs:", QB_DIR)
print("Python programs:", len(list((QB_DIR / "python_programs").glob("*.py"))))

Cloning into '/kaggle/working/MultiMend28/benchmarks/QuixBugs'...
remote: Enumerating objects: 1123, done.
remote: Counting objects: 100% (478/478), done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 1123 (delta 340), reused 300 (delta 300), pack-reused 645 (from 1)
Receiving objects: 100% (1123/1123), 1.14 MiB | 20.80 MiB/s, done.
Resolving deltas: 100% (648/648), done.
QuixBugs: /kaggle/working/MultiMend28/benchmarks/QuixBugs
Python programs: 50

In [11]:
# Cell 3 — Prepare benchmark data and checkpoints

import os
import json
import shutil
from pathlib import Path

# ================================================================
# 1. Repository
# ================================================================

REPO = Path("/kaggle/working/MultiMend28")
REPO.mkdir(parents=True, exist_ok=True)
os.chdir(REPO)

print("Repository:", REPO)


# ================================================================
# 2. Prepare QuixBugs benchmark
# ================================================================

QB_DIR = REPO / "benchmarks" / "QuixBugs"

# Download QuixBugs only if it is missing.
if not (QB_DIR / "python_programs").is_dir():
    print("\nQuixBugs not found. Downloading...")

    QB_DIR.parent.mkdir(parents=True, exist_ok=True)

    result = os.system(
        f'git clone https://github.com/jkoppel/QuixBugs.git "{QB_DIR}"'
    )

    if result != 0:
        raise RuntimeError(
            "Failed to download QuixBugs. "
            "Please enable Internet in Kaggle or attach QuixBugs as a dataset."
        )

# Verify benchmark structure.
if not (QB_DIR / "python_programs").is_dir():
    raise FileNotFoundError(
        f"QuixBugs python_programs directory is missing: {QB_DIR}"
    )

if not (QB_DIR / "correct_python_programs").is_dir():
    raise FileNotFoundError(
        f"QuixBugs correct_python_programs directory is missing: {QB_DIR}"
    )

buggy_programs = sorted(
    (QB_DIR / "python_programs").glob("*.py")
)

correct_programs = sorted(
    (QB_DIR / "correct_python_programs").glob("*.py")
)

print("\nQuixBugs benchmark:", QB_DIR)
print("Buggy programs:", len(buggy_programs))
print("Correct programs:", len(correct_programs))


# ================================================================
# 3. Locate MultiMend checkpoints
# ================================================================

MODEL_DIR = REPO / "models" / "multimend-codet5-small"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

# Optional manual override.
# Example:
# os.environ["MULTIMEND_CHECKPOINT_SOURCE"] = "/kaggle/input/..."
configured_source = os.environ.get("MULTIMEND_CHECKPOINT_SOURCE")


if configured_source:
    print("\nUsing configured checkpoint source:")
    print(configured_source)

    source = Path(configured_source)

    checkpoint_dirs = sorted(
        p for p in source.rglob("checkpoint-*")
        if p.is_dir() and (p / "trainer_state.json").is_file()
    )

else:
    # Automatically search all Kaggle input datasets.
    print("\nSearching /kaggle/input/datasets for checkpoints...")

    checkpoint_dirs = sorted(
        p.parent
        for p in Path("/kaggle/input/datasets").rglob("trainer_state.json")
        if p.parent.name.startswith("checkpoint-")
    )


# Remove duplicates while preserving order.
checkpoint_dirs = sorted(set(checkpoint_dirs))


if not checkpoint_dirs:
    raise FileNotFoundError(
        "No MultiMend checkpoints found.\n"
        "Expected checkpoint directories containing trainer_state.json "
        "under /kaggle/input/datasets."
    )


print(f"\nFound {len(checkpoint_dirs)} checkpoint(s):")

for checkpoint in checkpoint_dirs:
    print(" -", checkpoint)


# ================================================================
# 4. Copy checkpoints into the repository
# ================================================================

print("\nPreparing model checkpoints...")

for checkpoint in checkpoint_dirs:

    destination = MODEL_DIR / checkpoint.name

    if destination.exists():
        print(f"Already exists: {destination.name}")
        continue

    print(f"Copying: {checkpoint.name}")

    shutil.copytree(
        checkpoint,
        destination
    )


# ================================================================
# 5. Verify final model directory
# ================================================================

installed_checkpoints = sorted(
    p for p in MODEL_DIR.glob("checkpoint-*")
    if p.is_dir() and (p / "trainer_state.json").is_file()
)

if not installed_checkpoints:
    raise FileNotFoundError(
        f"No valid checkpoints were installed in {MODEL_DIR}"
    )


print("\n" + "=" * 60)
print("Cell 3 completed successfully")
print("=" * 60)

print("\nQuixBugs:")
print("  Location:", QB_DIR)
print("  Buggy programs:", len(buggy_programs))
print("  Correct programs:", len(correct_programs))

print("\nModel:")
print("  Location:", MODEL_DIR)
print("  Checkpoints:", len(installed_checkpoints))

for checkpoint in installed_checkpoints:
    print("   -", checkpoint.name)

Repository: /kaggle/working/MultiMend28

QuixBugs benchmark: /kaggle/working/MultiMend28/benchmarks/QuixBugs
Buggy programs: 50
Correct programs: 50

Searching /kaggle/input/datasets for checkpoints...

Found 10 checkpoint(s):
 - /kaggle/input/datasets/honglcl/checkpoint-116200/checkpoint-116200
 - /kaggle/input/datasets/honglcl/checkpoint174300/checkpoint-174300
 - /kaggle/input/datasets/minhhanh123/checkpoint-232400/checkpoint-232400
 - /kaggle/input/datasets/minhhanh123/checkpoint290500/checkpoint-290500
 - /kaggle/input/datasets/thothanh28/checkpoint58100/checkpoint-58100
 - /kaggle/input/datasets/tramtvt/checkpoint348600/checkpoint-348600
 - /kaggle/input/datasets/tramtvt/checkpoint406700/checkpoint-406700
 - /kaggle/input/datasets/tramtvt/checkpoint464800/checkpoint-464800
 - /kaggle/input/datasets/tramtvt/checkpoint522900/checkpoint-522900
 - /kaggle/input/datasets/tramtvt/checkpoint581008/checkpoint-581008

Preparing model checkpoints...
Copying: checkpoint-116200
Copying: checkpoint-174300
Copying: checkpoint-232400
Copying: checkpoint-290500
Copying: checkpoint-58100
Copying: checkpoint-348600
Copying: checkpoint-406700
Copying: checkpoint-464800
Copying: checkpoint-522900
Copying: checkpoint-581008

============================================================
Cell 3 completed successfully
============================================================

QuixBugs:
  Location: /kaggle/working/MultiMend28/benchmarks/QuixBugs
  Buggy programs: 50
  Correct programs: 50

Model:
  Location: /kaggle/working/MultiMend28/models/multimend-codet5-small
  Checkpoints: 10
   - checkpoint-116200
   - checkpoint-174300
   - checkpoint-232400
   - checkpoint-290500
   - checkpoint-348600
   - checkpoint-406700
   - checkpoint-464800
   - checkpoint-522900
   - checkpoint-58100
   - checkpoint-581008

In [12]:
# Cell 4 — Build QuixBugs-Python metadata WITHOUT RAG / Embedding

from pathlib import Path
import json
import difflib

# ------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------

quixbugs_dir = REPO / "benchmarks" / "QuixBugs"

# QuixBugs-Python thường có các thư mục này
buggy_dir = quixbugs_dir / "python_programs"
correct_dir = quixbugs_dir / "correct_python_programs"

output_dir = REPO / "outputs" / "QuixBugs-Python"
output_dir.mkdir(parents=True, exist_ok=True)

metadata_file = output_dir / "QuixBugs_Python.jsonl"
rem_file = output_dir / "rem.txt"
add_file = output_dir / "add.txt"

print("QuixBugs:", quixbugs_dir)
print("Buggy:", buggy_dir)
print("Correct:", correct_dir)


# ------------------------------------------------------------------
# Validate benchmark
# ------------------------------------------------------------------

if not buggy_dir.exists():
    raise FileNotFoundError(
        f"Buggy programs directory not found: {buggy_dir}"
    )

if not correct_dir.exists():
    raise FileNotFoundError(
        f"Correct programs directory not found: {correct_dir}"
    )


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def read_program(path):
    return path.read_text(encoding="utf-8").splitlines()


def unified_diff(old_lines, new_lines):
    """
    Return removed and added lines between buggy and correct versions.
    """
    diff = difflib.unified_diff(
        old_lines,
        new_lines,
        lineterm="",
    )

    removed = []
    added = []

    for line in diff:
        if line.startswith("---") or line.startswith("+++"):
            continue

        if line.startswith("-"):
            removed.append(line[1:])

        elif line.startswith("+"):
            added.append(line[1:])

    return removed, added


# ------------------------------------------------------------------
# Build metadata
# ------------------------------------------------------------------

records = []
all_removed = []
all_added = []

buggy_files = sorted(buggy_dir.glob("*.py"))

print("Buggy programs:", len(buggy_files))

for buggy_path in buggy_files:

    bugid = buggy_path.stem

    correct_path = correct_dir / buggy_path.name

    if not correct_path.exists():
        print(f"WARNING: missing correct program: {bugid}")
        continue

    buggy_lines = read_program(buggy_path)
    correct_lines = read_program(correct_path)

    removed, added = unified_diff(
        buggy_lines,
        correct_lines,
    )

    # Store global patch information
    all_removed.extend(removed)
    all_added.extend(added)

    record = {
        "bugid": bugid,
        "buggy_file": str(buggy_path),
        "correct_file": str(correct_path),
        "removed": removed,
        "added": added,
    }

    records.append(record)


# ------------------------------------------------------------------
# Write JSONL
# ------------------------------------------------------------------

with metadata_file.open("w", encoding="utf-8") as f:
    for record in records:
        f.write(
            json.dumps(
                record,
                ensure_ascii=False,
            )
            + "\n"
        )


# ------------------------------------------------------------------
# Write rem.txt / add.txt
# ------------------------------------------------------------------

rem_file.write_text(
    "\n".join(all_removed) + ("\n" if all_removed else ""),
    encoding="utf-8",
)

add_file.write_text(
    "\n".join(all_added) + ("\n" if all_added else ""),
    encoding="utf-8",
)


# ------------------------------------------------------------------
# Validate
# ------------------------------------------------------------------

required_metadata = [
    metadata_file,
    rem_file,
    add_file,
]

missing = [
    str(path)
    for path in required_metadata
    if not path.is_file()
]

if missing:
    raise FileNotFoundError(
        f"Metadata generation failed: {missing}"
    )

bug_count = sum(
    1
    for _ in metadata_file.open(encoding="utf-8")
)

print()
print("========================================")
print("Metadata generation complete")
print("========================================")
print("Metadata:", metadata_file)
print("rem.txt:", rem_file)
print("add.txt:", add_file)
print("Bug records:", bug_count)
print("Removed lines:", len(all_removed))
print("Added lines:", len(all_added))

QuixBugs: /kaggle/working/MultiMend28/benchmarks/QuixBugs
Buggy: /kaggle/working/MultiMend28/benchmarks/QuixBugs/python_programs
Correct: /kaggle/working/MultiMend28/benchmarks/QuixBugs/correct_python_programs
Buggy programs: 50

========================================
Metadata generation complete
========================================
Metadata: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/QuixBugs_Python.jsonl
rem.txt: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/rem.txt
add.txt: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/add.txt
Bug records: 50
Removed lines: 742
Added lines: 540

In [14]:
import subprocess
import sys
import os

env = os.environ.copy()
env["PYTHONPATH"] = str(REPO)

result = subprocess.run(
    [sys.executable, "-m", "src.bugline_finders.quixbugs_python"],
    cwd=REPO,
    env=env,
    text=True,
)

print("Return code:", result.returncode)

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event CollectionAddEvent: capture() takes 1 positional argument but 3 were given

Embedding...
bitcount 0
breadth_first_search 0
bucketsort 0
depth_first_search 0
detect_cycle 0
find_first_in_sorted 0
find_in_sorted 0
flatten 0
gcd 0
get_factors 0
hanoi 0
is_valid_parenthesization 0
kheapsort 0
knapsack 0
kth 0
lcs_length 0
levenshtein 0
lis 0
longest_common_subsequence 0
max_sublist_sum 0
mergesort 0
minimum_spanning_tree 0
next_palindrome 0
next_permutation 0
pascal 0
possible_change 0
powerset 0
quicksort 0
reverse_linked_list 0
rpn_eval 0
shortest_path_length 0
shortest_path_lengths 0
shortest_paths 0
shunting_yard 0
sieve 0
sqrt 0
subsequences 0
to_base 0
topological_ordering 0
wrap 0
Return code: 0

In [15]:
from src.configs import chromadb_path
import chromadb

print("ChromaDB path:", chromadb_path)

client = chromadb.PersistentClient(path=str(chromadb_path))

print("Collections hiện có:")
for collection in client.list_collections():
    print("-", collection.name)

Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given

ChromaDB path: /kaggle/working/MultiMend28/chroma_db
Collections hiện có:
- QuixBugs-Python

In [16]:
# Cell 5 - Generate both experimental conditions from trainer-state checkpoints
import os
import subprocess
import sys

output_root = REPO / "outputs" / "QuixBugs-Python"


def run_generation(strategy: str) -> None:
    strategy_dir = output_root / f"outputs-multimend-{strategy}"
    for stale_file in (strategy_dir / "sequences_100.jsonl", strategy_dir / "generated_input.jsonl"):
        if stale_file.exists():
            stale_file.unlink()
    env = os.environ.copy()
    env["MULTIMEND_CONTEXT_STRATEGY"] = strategy
    env["PYTHONPATH"] = str(REPO)
    subprocess.run([sys.executable, "-m", "src.generate_primary_candidates"], cwd=REPO, env=env, check=True)
    raw_file = strategy_dir / "sequences_100.jsonl"
    if not raw_file.is_file() or raw_file.stat().st_size == 0:
        raise RuntimeError(f"{strategy}: missing {raw_file}")
    print(f"{strategy}: {raw_file.stat().st_size:,} bytes")


for strategy in ("no_rag", "fixed_rag"):
    run_generation(strategy)

Starting no_rag...
Selected checkpoints:
- checkpoint-348600: global_step=348600
- checkpoint-406700: global_step=406700
- checkpoint-464800: global_step=464800
- checkpoint-522900: global_step=522900
- checkpoint-581008: global_step=581008
# RAG retrievals...
bitcount 0
breadth_first_search 0
bucketsort 0
depth_first_search 0
detect_cycle 0
find_first_in_sorted 0
find_in_sorted 0
flatten 0
gcd 0
get_factors 0
hanoi 0
is_valid_parenthesization 0
kheapsort 0
knapsack 0
kth 0
lcs_length 0
levenshtein 0
lis 0
longest_common_subsequence 0
max_sublist_sum 0
mergesort 0
minimum_spanning_tree 0
next_palindrome 0
next_permutation 0
pascal 0
possible_change 0
powerset 0
quicksort 0
reverse_linked_list 0
rpn_eval 0
shortest_path_length 0
shortest_path_lengths 0
shortest_paths 0
shunting_yard 0
sieve 0
sqrt 0
subsequences 0
to_base 0
topological_ordering 0
wrap 0
Tokenizing...

Creating json from Arrow format: 100%|██████████| 1/1 [00:00<00:00, 42.34ba/s]
Map: 100%|██████████| 40/40 [00:00<00:00, 1042.65 examples/s]

Generating from checkpoint-348600...

Map: 100%|██████████| 40/40 [00:21<00:00,  1.84 examples/s]

Generating from checkpoint-406700...

Map: 100%|██████████| 40/40 [00:22<00:00,  1.75 examples/s]

Generating from checkpoint-464800...

Map: 100%|██████████| 40/40 [00:23<00:00,  1.69 examples/s]

Generating from checkpoint-522900...

Map: 100%|██████████| 40/40 [00:21<00:00,  1.84 examples/s]

Generating from checkpoint-581008...

Map: 100%|██████████| 40/40 [00:22<00:00,  1.76 examples/s]
Creating json from Arrow format: 100%|██████████| 20/20 [00:00<00:00, 329.63ba/s]

no_rag: generation complete (3,114,407 bytes)
Starting fixed_rag...

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event CollectionQueryEvent: capture() takes 1 positional argument but 3 were given

Selected checkpoints:
- checkpoint-348600: global_step=348600
- checkpoint-406700: global_step=406700
- checkpoint-464800: global_step=464800
- checkpoint-522900: global_step=522900
- checkpoint-581008: global_step=581008
# RAG retrievals...
bitcount 0
breadth_first_search 0
bucketsort 0
depth_first_search 0
detect_cycle 0
find_first_in_sorted 0
find_in_sorted 0
flatten 0
gcd 0
get_factors 0
hanoi 0
is_valid_parenthesization 0
kheapsort 0
knapsack 0
kth 0
lcs_length 0
levenshtein 0
lis 0
longest_common_subsequence 0
max_sublist_sum 0
mergesort 0
minimum_spanning_tree 0
next_palindrome 0
next_permutation 0
pascal 0
possible_change 0
powerset 0
quicksort 0
reverse_linked_list 0
rpn_eval 0
shortest_path_length 0
shortest_path_lengths 0
shortest_paths 0
shunting_yard 0
sieve 0
sqrt 0
subsequences 0
to_base 0
topological_ordering 0
wrap 0
Tokenizing...

Creating json from Arrow format: 100%|██████████| 1/1 [00:00<00:00, 800.90ba/s]
Map: 100%|██████████| 40/40 [00:00<00:00, 3143.98 examples/s]

Generating from checkpoint-348600...

Map: 100%|██████████| 40/40 [00:23<00:00,  1.71 examples/s]

Generating from checkpoint-406700...

Map: 100%|██████████| 40/40 [00:24<00:00,  1.62 examples/s]

Generating from checkpoint-464800...

Map: 100%|██████████| 40/40 [00:25<00:00,  1.55 examples/s]

Generating from checkpoint-522900...

Map: 100%|██████████| 40/40 [00:23<00:00,  1.70 examples/s]

Generating from checkpoint-581008...

Map: 100%|██████████| 40/40 [00:24<00:00,  1.64 examples/s]
Creating json from Arrow format: 100%|██████████| 20/20 [00:00<00:00, 386.66ba/s]

fixed_rag: generation complete (3,117,214 bytes)

In [17]:
# Cell 6 — Combine and deduplicate candidates for B0/B1

import os
import subprocess
import sys

STRATEGIES = ("no_rag", "fixed_rag")


def run_combine(strategy):
    output_dir = (
        REPO
        / "outputs"
        / "QuixBugs-Python"
        / f"outputs-multimend-{strategy}"
    )
    final_file = output_dir / "final_candidates_100.jsonl"

    output_dir.mkdir(parents=True, exist_ok=True)

    # Remove old combined output so we always combine
    # from the current generation results.
    if final_file.exists():
        final_file.unlink()
        print(f"{strategy}: removed old {final_file.name}")

    env = os.environ.copy()
    env["MULTIMEND_CONTEXT_STRATEGY"] = strategy

    print(f"\nStarting combine for {strategy}...")

    subprocess.run(
        [sys.executable, "-m", "src.combine_checkpoints_results"],
        cwd=REPO,
        env=env,
        check=True,
    )

    if not final_file.is_file() or final_file.stat().st_size == 0:
        raise RuntimeError(
            f"{strategy}: combine did not create a valid output: {final_file}"
        )

    print(
        f"{strategy}: combine complete "
        f"({final_file.stat().st_size:,} bytes)"
    )


for strategy in STRATEGIES:
    run_combine(strategy)

Starting combine for no_rag...
All: 20000
Deduped: 9709
no_rag: combine complete (4,286,423 bytes)

Starting combine for fixed_rag...
All: 20000
Deduped: 9667
fixed_rag: combine complete (4,270,513 bytes)

In [40]:
import requests
from pathlib import Path

base_url = "https://raw.githubusercontent.com/ThaoTo2806/MultiMend28/main/"

files = [
    "src/validators/validate_runbugrunjs.py",
    "src/validators/validate_quixbugs_python.py"
]

project = Path("/kaggle/working/MultiMend28")

for file in files:
    url = base_url + file
    path = project / file

    response = requests.get(url)
    response.raise_for_status()

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(response.text, encoding="utf-8")

    print(f"✓ Loaded: {file}")

print("✓ Hoàn tất load từ GitHub")

✓ Loaded: src/validators/validate_runbugrunjs.py
✓ Loaded: src/validators/validate_quixbugs_python.py
✓ Hoàn tất load từ GitHub

In [70]:
# Cell 7A — Clean stale validator state

import shutil
from pathlib import Path

QUIXBUGS_OUTPUT = REPO / "outputs" / "QuixBugs-Python"

for strategy in ("no_rag", "fixed_rag"):
    output_dir = (
        QUIXBUGS_OUTPUT
        / f"outputs-multimend-{strategy}"
    )

    save_state_dir = output_dir / "save-state"
    result_file = output_dir / "plausible_candidates_100.jsonl"

    if save_state_dir.exists():
        shutil.rmtree(save_state_dir)
        print(f"Removed save-state: {save_state_dir}")

    # Xóa kết quả cũ để validator chạy lại
    if result_file.exists():
        result_file.unlink()
        print(f"Removed result: {result_file}")

print("Old validator state cleaned.")

Removed save-state: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/outputs-multimend-no_rag/save-state
Removed result: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/outputs-multimend-no_rag/plausible_candidates_100.jsonl
Removed save-state: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/outputs-multimend-fixed_rag/save-state
Removed result: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/outputs-multimend-fixed_rag/plausible_candidates_100.jsonl
Old validator state cleaned.

In [42]:
from pathlib import Path

QUIXBUGS_OUTPUT = Path("/kaggle/working/MultiMend28/outputs/QuixBugs-Python")

METADATA_FILE = QUIXBUGS_OUTPUT / "QuixBugs_Python.jsonl"
BACKUP_FILE = QUIXBUGS_OUTPUT / "QuixBugs_Python.jsonl.backup"

print("METADATA_FILE:")
print(METADATA_FILE)
print("exists:", METADATA_FILE.exists())
print("size:", METADATA_FILE.stat().st_size if METADATA_FILE.exists() else "N/A")

print("\nBACKUP_FILE:")
print(BACKUP_FILE)
print("exists:", BACKUP_FILE.exists())
print("size:", BACKUP_FILE.stat().st_size if BACKUP_FILE.exists() else "N/A")

METADATA_FILE:
/kaggle/working/MultiMend28/outputs/QuixBugs-Python/QuixBugs_Python.jsonl
exists: True
size: 40806

BACKUP_FILE:
/kaggle/working/MultiMend28/outputs/QuixBugs-Python/QuixBugs_Python.jsonl.backup
exists: True
size: 40806

In [68]:
from pathlib import Path

VALIDATOR = Path(
    "/kaggle/working/MultiMend28/src/validators/validate_quixbugs_python.py"
)

text = VALIDATOR.read_text(encoding="utf-8")

print("skipped_programs" in text)
print("detect_cycle_test" in text)
print("shortest_path_length_test" in text)

print("\n--- VALIDATOR CONFIG SECTION ---")

lines = text.splitlines()

for i, line in enumerate(lines):
    if "metadata_programs = len(bugs_metadata)" in line:
        print("\n".join(lines[i-3:i+7]))
        break

False
False
False

--- VALIDATOR CONFIG SECTION ---
    # Validate ALL programs.
    # No programs are skipped.

    metadata_programs = len(bugs_metadata)

    print(f"Metadata programs: {metadata_programs}")
    print(f"Programs to validate: {len(bugs_metadata)}")

    candidate_patches_df = pd.read_json(
        output_dir / f"final_candidates_{output_size}.jsonl",

In [47]:
from pathlib import Path

BASE = Path("/kaggle/working/MultiMend28/outputs/QuixBugs-Python")

print("Các thư mục/file trong QuixBugs-Python:\n")

for p in sorted(BASE.iterdir()):
    if p.is_dir():
        print("[DIR ]", p.name)
    else:
        print("[FILE]", p.name)

Các thư mục/file trong QuixBugs-Python:

[FILE] QuixBugs_Python.jsonl
[FILE] QuixBugs_Python.jsonl.backup
[FILE] add.txt
[FILE] context.txt
[FILE] context_log_fixed_rag.jsonl
[FILE] context_log_no_rag.jsonl
[DIR ] outputs-multimend-fixed_rag
[DIR ] outputs-multimend-no_rag
[FILE] rem.txt

In [ ]:
import contextlib
import json
import os
import shutil
import subprocess
import threading
import time
import timeit
from collections import ChainMap
from copy import deepcopy
from enum import Enum, auto
from pathlib import Path
from typing import Optional

import joblib
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from tqdm import tqdm

from ..configs import quixbugs_dir, quixbugs_genpy_dir


# ============================================================
# CONFIG
# ============================================================

project_dir = quixbugs_dir
gen_dir = quixbugs_genpy_dir

bugs_metadata_file = "QuixBugs_Python.jsonl"

model = "multimend"

context_strategy = os.environ.get(
    "MULTIMEND_CONTEXT_STRATEGY",
    "fixed_rag",
)

if context_strategy not in {
    "no_rag",
    "fixed_rag",
}:
    raise ValueError(
        f"Unsupported context strategy: {context_strategy}"
    )

output_dir = (
    gen_dir
    / f"outputs-{model}-{context_strategy}"
)

temp_dir = output_dir / "temp"
save_state_dir = output_dir / "save-state"

output_size = 100

TEST_TIMEOUT = float(
    os.environ.get(
        "MULTIMEND_VALIDATION_TIMEOUT",
        "60",
    )
)

N_WORKERS = int(
    os.environ.get(
        "MULTIMEND_VALIDATION_JOBS",
        "6",
    )
)

VALIDATION_SLEEP = float(
    os.environ.get(
        "MULTIMEND_VALIDATION_SLEEP",
        "1.0",
    )
)

RESET_VALIDATION = (
    os.environ.get(
        "MULTIMEND_RESET_VALIDATION",
        "0",
    ).lower()
    in {"1", "true", "yes"}
)


# ============================================================
# STATUS
# ============================================================

class Status(Enum):
    PLAUSIBLE = auto()
    PARSABLE = auto()
    TIMEOUT = auto()
    UNPARSABLE = auto()


# ============================================================
# TQDM / JOBLIB
# ============================================================

@contextlib.contextmanager
def tqdm_joblib(tqdm_object):
    def tqdm_print_progress(self):
        if self.n_completed_tasks > tqdm_object.n:
            completed = (
                self.n_completed_tasks
                - tqdm_object.n
            )
            tqdm_object.update(
                n=completed
            )

    original_print_progress = (
        joblib.parallel.Parallel.print_progress
    )

    joblib.parallel.Parallel.print_progress = (
        tqdm_print_progress
    )

    try:
        yield tqdm_object
    finally:
        joblib.parallel.Parallel.print_progress = (
            original_print_progress
        )
        tqdm_object.close()


# ============================================================
# DATAFRAME HELPERS
# ============================================================

def get_hunk_candidates(
    df: pd.DataFrame,
    hunk: int,
) -> pd.DataFrame:
    return df.loc[
        df["hunk"] == hunk
    ]


def get_candidates(
    df: pd.DataFrame,
    bugid: str,
) -> pd.DataFrame:
    return df.loc[
        df["bugid"].astype(str)
        == str(bugid)
    ]


# ============================================================
# NORMALIZATION
# ============================================================

def normalize_patch(value) -> str:
    """
    Normalize generated patch and ground-truth patch
    before exact-match comparison.
    """

    if value is None:
        return ""

    return (
        str(value)
        .replace("\r\n", "\n")
        .replace("\r", "\n")
        .strip()
    )


# ============================================================
# GROUND TRUTH
# ============================================================

def load_ground_truth():
    """
    Build:

        (bugid, hunk) -> target patch

    from QuixBugs_Python.jsonl.
    """

    metadata_path = (
        gen_dir
        / bugs_metadata_file
    )

    with metadata_path.open(
        "r",
        encoding="utf-8",
    ) as meta_file:

        bugs_metadata = ChainMap(
            *[
                json.loads(line)
                for line in meta_file
            ][::-1]
        )

    ground_truth = {}

    for bugid, hunks in bugs_metadata.items():

        for hunk_id, hunk in enumerate(hunks):

            target = hunk.get(
                "added_lines",
                "",
            )

            if not target:
                target = hunk.get(
                    "target",
                    "",
                )

            ground_truth[
                (
                    str(bugid),
                    int(hunk_id),
                )
            ] = normalize_patch(
                target
            )

    return bugs_metadata, ground_truth


# ============================================================
# CORRECT
# ============================================================

def calculate_correct(
    df: pd.DataFrame,
    ground_truth: dict,
) -> pd.DataFrame:
    """
    Candidate is CORRECT iff its generated patch exactly
    matches the target patch in QuixBugs metadata.
    """

    def check_row(row):

        key = (
            str(row["bugid"]),
            int(row["hunk"]),
        )

        target = ground_truth.get(
            key,
            "",
        )

        generated = normalize_patch(
            row.get(
                "decoded_sequences",
                "",
            )
        )

        return (
            bool(target)
            and generated == target
        )

    df["correct"] = df.apply(
        check_row,
        axis=1,
    )

    return df


# ============================================================
# PATCH APPLICATION
# ============================================================

def insert_patch(
    patch,
    source_file_path,
    target_file_path,
    bug_line,
    bug_len,
    indent,
):
    """
    Apply one candidate to a clean copy of the buggy file.
    """

    with open(
        source_file_path,
        "r",
        encoding="utf-8",
    ) as file:
        lines = file.readlines()

    patch = normalize_patch(
        patch
    )

    replacement = (
        indent
        + patch
        + "\n"
    )

    if bug_len == 0:

        lines.insert(
            bug_line,
            replacement,
        )

    else:

        lines[
            bug_line - 1:
            (bug_line - 1) + bug_len
        ] = [
            replacement
        ]

    with open(
        target_file_path,
        "w",
        encoding="utf-8",
    ) as file:
        file.writelines(lines)


# ============================================================
# TEST EXECUTION
# ============================================================

def run_tests(
    bugid: str,
    project_copy_dir: Path,
) -> Status:

    tests_dir = (
        project_copy_dir
        / "python_testcases"
    )

    test_file = (
        tests_dir
        / f"test_{bugid}.py"
    )

    args = [
        "pytest",
        "-x",
        str(test_file),
    ]

    try:

        result = subprocess.run(
            args,
            capture_output=True,
            timeout=TEST_TIMEOUT,
        )

    except subprocess.TimeoutExpired:

        return Status.TIMEOUT

    if result.returncode == 0:
        return Status.PLAUSIBLE

    if result.returncode == 2:
        return Status.UNPARSABLE

    return Status.PARSABLE


# ============================================================
# DATASET COPY
# ============================================================

def copy_dataset_files(
    dataset_dir,
    temp_dataset_dir,
):

    shutil.copytree(
        dataset_dir,
        temp_dataset_dir,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns(
            ".*"
        ),
    )


# ============================================================
# SAVE VALIDATION STATE
# ============================================================

def save_validation_state(
    df: pd.DataFrame,
    bugid: str,
):

    save_state_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    save_path = (
        save_state_dir
        / f"{bugid}.jsonl"
    )

    temp_path = (
        save_state_dir
        / f"{bugid}.jsonl.tmp"
    )

    df.to_json(
        temp_path,
        orient="records",
        lines=True,
    )

    temp_path.replace(
        save_path
    )


# ============================================================
# VALIDATE ONE BUG
# ============================================================

def apply_patch(
    cp_df: pd.DataFrame,
    bugid: str,
    hunks: list,
) -> Optional[pd.DataFrame]:

    save_file_path = (
        save_state_dir
        / f"{bugid}.jsonl"
    )

    if save_file_path.exists():
        return None

    # --------------------------------------------------------
    # QuixBugs original validator validates one hunk here.
    # --------------------------------------------------------

    if len(hunks) != 1:
        return None

    hunk = hunks[0]

    pid = threading.get_ident()

    project_copy_dir = (
        temp_dir
        / str(pid)
        / "QuixBugs"
    )

    copy_dataset_files(
        project_dir,
        project_copy_dir,
    )

    target_file_path = (
        project_copy_dir
        / "python_programs"
        / f"{bugid}.py"
    )

    source_file_path = (
        temp_dir
        / str(pid)
        / "sources"
        / bugid
        / f"{bugid}.py"
    )

    source_file_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    shutil.copyfile(
        target_file_path,
        source_file_path,
    )

    bug_line, bug_len = (
        hunk[
            "removed_line_numbers_range"
        ]
    )

    # --------------------------------------------------------
    # Preserve original indentation.
    # --------------------------------------------------------

    added_lines = hunk.get(
        "added_lines",
        "",
    )

    indent_size = (
        len(added_lines)
        - len(
            added_lines.lstrip(
                " \t"
            )
        )
    )

    indent = added_lines[
        :indent_size
    ]

    # --------------------------------------------------------
    # Validate candidates.
    # --------------------------------------------------------

    bug_hunk_subset_df = (
        get_hunk_candidates(
            cp_df,
            0,
        )
    )

    for index, patch in (
        bug_hunk_subset_df[
            "decoded_sequences"
        ].items()
    ):

        # IMPORTANT:
        # Always restore the original buggy program
        # before testing the next candidate.

        shutil.copyfile(
            source_file_path,
            target_file_path,
        )

        insert_patch(
            patch,
            source_file_path,
            target_file_path,
            bug_line,
            bug_len,
            indent,
        )

        start_timer = (
            timeit.default_timer()
        )

        status = run_tests(
            bugid,
            project_copy_dir,
        )

        end_timer = (
            timeit.default_timer()
        )

        cp_df.at[
            index,
            "validation_time",
        ] = (
            end_timer
            - start_timer
        )

        if status is Status.PLAUSIBLE:

            cp_df.at[
                index,
                "plausible",
            ] = True

            cp_df.at[
                index,
                "parsable",
            ] = True

            # Paper-style validation:
            # stop after first plausible candidate.

            break

        elif status is Status.PARSABLE:

            cp_df.at[
                index,
                "parsable",
            ] = True

        elif status is Status.TIMEOUT:

            cp_df.at[
                index,
                "timeout",
            ] = True

            cp_df.at[
                index,
                "parsable",
            ] = True

        if VALIDATION_SLEEP > 0:
            time.sleep(
                VALIDATION_SLEEP
            )

    save_validation_state(
        cp_df,
        bugid,
    )

    return cp_df


# ============================================================
# RESET
# ============================================================

def reset_validation_state():

    if RESET_VALIDATION:

        shutil.rmtree(
            save_state_dir,
            ignore_errors=True,
        )


# ============================================================
# MAIN
# ============================================================

def main():

    print(
        "\n"
        + "=" * 70
    )

    print(
        "MultiMend QuixBugs-Python Validator"
    )

    print(
        "=" * 70
    )

    print(
        f"context strategy : {context_strategy}"
    )

    print(
        f"output directory  : {output_dir}"
    )

    print(
        f"candidate size    : {output_size}"
    )

    print(
        f"timeout           : {TEST_TIMEOUT}s"
    )

    print(
        f"workers           : {N_WORKERS}"
    )

    # ========================================================
    # METADATA + GROUND TRUTH
    # ========================================================

    bugs_metadata, ground_truth = (
        load_ground_truth()
    )

    print(
        f"metadata bugs     : "
        f"{len(bugs_metadata)}"
    )

    print(
        f"ground-truth hunks: "
        f"{len(ground_truth)}"
    )

    # ========================================================
    # CANDIDATES
    # ========================================================

    candidate_file = (
        output_dir
        / f"final_candidates_{output_size}.jsonl"
    )

    if not candidate_file.exists():

        raise FileNotFoundError(
            "Candidate file not found:\n"
            f"{candidate_file}"
        )

    candidate_patches_df = (
        pd.read_json(
            candidate_file,
            orient="records",
            lines=True,
        )
    )

    print(
        f"candidate rows    : "
        f"{len(candidate_patches_df)}"
    )

    # ========================================================
    # VALIDATION COLUMNS
    # ========================================================

    candidate_patches_df[
        "plausible"
    ] = False

    candidate_patches_df[
        "parsable"
    ] = False

    candidate_patches_df[
        "timeout"
    ] = False

    candidate_patches_df[
        "validation_time"
    ] = np.nan

    # ========================================================
    # RESET
    # ========================================================

    reset_validation_state()

    shutil.rmtree(
        temp_dir,
        ignore_errors=True,
    )

    save_state_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ========================================================
    # VALIDATE
    # ========================================================

    with tqdm_joblib(
        tqdm(
            total=len(bugs_metadata),
            desc=f"Validating {context_strategy}",
        )
    ):

        Parallel(
            n_jobs=N_WORKERS,
            backend="threading",
        )(
            delayed(apply_patch)(
                deepcopy(
                    get_candidates(
                        candidate_patches_df,
                        bugid,
                    )
                ),
                bugid,
                hunks,
            )
            for bugid, hunks
            in bugs_metadata.items()
        )

    # ========================================================
    # LOAD STATES
    # ========================================================

    state_files = sorted(
        save_state_dir.glob(
            "*.jsonl"
        )
    )

    if not state_files:

        raise RuntimeError(
            "No validation states were produced."
        )

    cp_dfs = []

    for state_file in state_files:

        state_df = pd.read_json(
            state_file,
            orient="records",
            lines=True,
        )

        cp_dfs.append(
            state_df
        )

    concatenated_cp_df = pd.concat(
        cp_dfs,
        ignore_index=True,
    )

    if len(candidate_patches_df) != len(
        concatenated_cp_df
    ):

        raise RuntimeError(
            "Candidate count changed during validation: "
            f"{len(candidate_patches_df)} -> "
            f"{len(concatenated_cp_df)}"
        )

    # ========================================================
    # CALCULATE CORRECT
    # ========================================================

    concatenated_cp_df = calculate_correct(
        concatenated_cp_df,
        ground_truth,
    )

    # ========================================================
    # SAVE CANDIDATE RESULTS
    # ========================================================

    result_file = (
        output_dir
        / f"plausible_candidates_{output_size}.jsonl"
    )

    concatenated_cp_df.to_json(
        result_file,
        orient="records",
        lines=True,
    )

    # ========================================================
    # HUNK LEVEL
    # ========================================================

    correct_hunks = (
        concatenated_cp_df
        .groupby(
            [
                "bugid",
                "hunk",
            ]
        )["correct"]
        .any()
    )

    plausible_hunks = (
        concatenated_cp_df
        .groupby(
            [
                "bugid",
                "hunk",
            ]
        )["plausible"]
        .any()
    )

    total_hunks = len(
        plausible_hunks
    )

    correct_hunk_count = int(
        correct_hunks.sum()
    )

    plausible_hunk_count = int(
        plausible_hunks.sum()
    )

    # ========================================================
    # BUG LEVEL
    # ========================================================
    #
    # A bug is CORRECT when ALL of its hunks have
    # at least one correct candidate.
    #
    # A bug is PLAUSIBLE when ALL of its hunks have
    # at least one plausible candidate.
    # ========================================================

    correct_bugs = (
        correct_hunks
        .groupby("bugid")
        .all()
    )

    plausible_bugs = (
        plausible_hunks
        .groupby("bugid")
        .all()
    )

    total_bugs = len(
        plausible_bugs
    )

    correct_bug_count = int(
        correct_bugs.sum()
    )

    plausible_bug_count = int(
        plausible_bugs.sum()
    )

    # ========================================================
    # CANDIDATE LEVEL
    # ========================================================

    total_candidates = len(
        concatenated_cp_df
    )

    correct_candidate_count = int(
        concatenated_cp_df[
            "correct"
        ].sum()
    )

    plausible_candidate_count = int(
        concatenated_cp_df[
            "plausible"
        ].sum()
    )

    correct_and_plausible_count = int(
        (
            concatenated_cp_df["correct"]
            &
            concatenated_cp_df["plausible"]
        ).sum()
    )

    # ========================================================
    # PAPER METRICS
    # ========================================================

    paper_metrics = pd.DataFrame(
        [
            {
                "strategy": context_strategy,

                "total_bugs": total_bugs,
                "correct_bugs": correct_bug_count,
                "plausible_bugs": plausible_bug_count,

                "total_hunks": total_hunks,
                "correct_hunks": correct_hunk_count,
                "plausible_hunks": plausible_hunk_count,

                "total_candidates": total_candidates,
                "correct_candidates":
                    correct_candidate_count,
                "plausible_candidates":
                    plausible_candidate_count,
                "correct_and_plausible_candidates":
                    correct_and_plausible_count,

                "correct_bug_rate":
                    (
                        correct_bug_count
                        / total_bugs
                        if total_bugs
                        else 0.0
                    ),

                "plausible_bug_rate":
                    (
                        plausible_bug_count
                        / total_bugs
                        if total_bugs
                        else 0.0
                    ),

                "correct_hunk_rate":
                    (
                        correct_hunk_count
                        / total_hunks
                        if total_hunks
                        else 0.0
                    ),

                "plausible_hunk_rate":
                    (
                        plausible_hunk_count
                        / total_hunks
                        if total_hunks
                        else 0.0
                    ),
            }
        ]
    )

    paper_metrics_file = (
        output_dir
        / f"paper_bug_metrics_{output_size}.jsonl"
    )

    paper_metrics.to_json(
        paper_metrics_file,
        orient="records",
        lines=True,
    )

    # ========================================================
    # PRINT RESULTS
    # ========================================================

    print()
    print(
        "=" * 70
    )

    print(
        f"RESULTS: {context_strategy}"
    )

    print(
        "=" * 70
    )

    print(
        f"BUGS       : {total_bugs}"
    )

    print(
        f"CORRECT    : "
        f"{correct_bug_count} / {total_bugs}"
        f" "
        f"({100 * correct_bug_count / total_bugs:.2f}%)"
        if total_bugs
        else "CORRECT    : 0 / 0"
    )

    print(
        f"PLAUSIBLE  : "
        f"{plausible_bug_count} / {total_bugs}"
        f" "
        f"({100 * plausible_bug_count / total_bugs:.2f}%)"
        if total_bugs
        else "PLAUSIBLE  : 0 / 0"
    )

    print()

    print(
        f"HUNKS      : {total_hunks}"
    )

    print(
        f"CORRECT    : "
        f"{correct_hunk_count} / {total_hunks}"
    )

    print(
        f"PLAUSIBLE  : "
        f"{plausible_hunk_count} / {total_hunks}"
    )

    print()

    print(
        f"CANDIDATES : {total_candidates}"
    )

    print(
        f"CORRECT    : "
        f"{correct_candidate_count}"
    )

    print(
        f"PLAUSIBLE  : "
        f"{plausible_candidate_count}"
    )

    print(
        f"CORRECT + PLAUSIBLE : "
        f"{correct_and_plausible_count}"
    )

    print()

    print(
        f"Candidates -> {result_file}"
    )

    print(
        f"Metrics    -> {paper_metrics_file}"
    )

    print(
        "=" * 70
    )


if __name__ == "__main__":
    main()

Metadata programs: 40
Programs to validate: 40
Skipped: []
Backed up metadata to: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/QuixBugs_Python.jsonl.backup

======================================================================
VALIDATING: no_rag
======================================================================
timeout per test : 10 seconds
sleep candidates : 0.05 seconds
workers          : 6
======================================================================
[VALIDATOR CONFIG] test_timeout=10.0s, candidate_sleep=0.05s, workers=6
Metadata programs: 40
Programs to validate: 40

  0%|          | 0/40 [00:00<?, ?it/s]

[VALIDATOR] bug=find_first_in_sorted candidates=240
[VALIDATOR] START index=1242
[VALIDATOR] bug=bucketsort candidates=241
[VALIDATOR] START index=464
[VALIDATOR] bug=depth_first_search candidates=282
[VALIDATOR] START index=705
[VALIDATOR] bug=breadth_first_search candidates=239
[VALIDATOR] START index=225
[VALIDATOR] bug=bitcount candidates=225
[VALIDATOR] START index=0
[VALIDATOR] bug=detect_cycle candidates=255
[VALIDATOR] START index=987
[VALIDATOR] START index=465
[VALIDATOR] START index=706
[VALIDATOR] START index=988
[VALIDATOR] START index=1243
[VALIDATOR] START index=226
[VALIDATOR] START index=466
[VALIDATOR] START index=989

  2%|▎         | 1/40 [00:07<04:33,  7.02s/it]

[VALIDATOR] bug=find_in_sorted candidates=237
[VALIDATOR] START index=1482
[VALIDATOR] START index=227
[VALIDATOR] START index=707
[VALIDATOR] START index=467

  5%|▌         | 2/40 [00:09<02:53,  4.57s/it]

[VALIDATOR] bug=flatten candidates=250
[VALIDATOR] START index=1719
[VALIDATOR] START index=990
[VALIDATOR] START index=1483
[VALIDATOR] START index=1
[VALIDATOR] START index=708
[VALIDATOR] START index=468
[VALIDATOR] START index=1720
[VALIDATOR] START index=991
[VALIDATOR] START index=1484
[VALIDATOR] START index=2
[VALIDATOR] START index=709
[VALIDATOR] START index=469
[VALIDATOR] START index=992
[VALIDATOR] START index=1721
[VALIDATOR] START index=1485
[VALIDATOR] START index=3
[VALIDATOR] START index=470
[VALIDATOR] START index=710
[VALIDATOR] START index=1722
[VALIDATOR] START index=993
[VALIDATOR] START index=1486
[VALIDATOR] START index=471
[VALIDATOR] START index=1723
[VALIDATOR] START index=711
[VALIDATOR] START index=994
[VALIDATOR] START index=1487
[VALIDATOR] START index=472
[VALIDATOR] START index=712
[VALIDATOR] bug=gcd candidates=229
[VALIDATOR] START index=1969
[VALIDATOR] START index=1724

  8%|▊         | 3/40 [00:24<05:41,  9.24s/it]

[VALIDATOR] START index=1488
[VALIDATOR] START index=473
[VALIDATOR] START index=4
[VALIDATOR] START index=713

 10%|█         | 4/40 [00:27<04:01,  6.70s/it]

[VALIDATOR] bug=get_factors candidates=248
[VALIDATOR] START index=2198

 12%|█▎        | 5/40 [00:27<02:35,  4.45s/it]

[VALIDATOR] bug=hanoi candidates=219
[VALIDATOR] START index=2446
[VALIDATOR] START index=1970
[VALIDATOR] START index=5
[VALIDATOR] START index=474
[VALIDATOR] START index=714
[VALIDATOR] START index=2199
[VALIDATOR] START index=1971
[VALIDATOR] START index=2447
[VALIDATOR] START index=6
[VALIDATOR] START index=475
[VALIDATOR] START index=715
[VALIDATOR] START index=2200
[VALIDATOR] START index=1972
[VALIDATOR] START index=2448
[VALIDATOR] START index=476

 15%|█▌        | 6/40 [00:36<03:15,  5.75s/it]

[VALIDATOR] bug=is_valid_parenthesization candidates=242
[VALIDATOR] START index=2665
[VALIDATOR] START index=716
[VALIDATOR] START index=1973
[VALIDATOR] START index=2449
[VALIDATOR] START index=477
[VALIDATOR] START index=2666
[VALIDATOR] START index=1974
[VALIDATOR] START index=717
[VALIDATOR] START index=2450
[VALIDATOR] START index=478
[VALIDATOR] START index=2667
[VALIDATOR] START index=7
[VALIDATOR] START index=2451
[VALIDATOR] START index=718
[VALIDATOR] START index=1975
[VALIDATOR] START index=479
[VALIDATOR] START index=2668
[VALIDATOR] START index=719
[VALIDATOR] START index=2452
[VALIDATOR] START index=1976
[VALIDATOR] START index=480
[VALIDATOR] START index=2669
[VALIDATOR] START index=2453
[VALIDATOR] START index=1977
[VALIDATOR] START index=720
[VALIDATOR] START index=481
[VALIDATOR] START index=2670
[VALIDATOR] START index=2454
[VALIDATOR] START index=1978
[VALIDATOR] START index=721
[VALIDATOR] START index=8
[VALIDATOR] START index=482
[VALIDATOR] START index=2671
[VALIDATOR] START index=2455
[VALIDATOR] START index=483
[VALIDATOR] START index=722
[VALIDATOR] START index=1979
[VALIDATOR] START index=2672
[VALIDATOR] START index=484
[VALIDATOR] START index=2456
[VALIDATOR] START index=723
[VALIDATOR] START index=1980
[VALIDATOR] START index=2673
[VALIDATOR] START index=2457
[VALIDATOR] START index=485
[VALIDATOR] START index=724
[VALIDATOR] START index=1981
[VALIDATOR] START index=2674
[VALIDATOR] START index=9
[VALIDATOR] START index=486
[VALIDATOR] START index=2458
[VALIDATOR] START index=1982
[VALIDATOR] START index=725

 18%|█▊        | 7/40 [01:05<07:22, 13.42s/it]

[VALIDATOR] START index=2675
[VALIDATOR] bug=kheapsort candidates=250
[VALIDATOR] START index=2907
[VALIDATOR] START index=487
[VALIDATOR] START index=2459
[VALIDATOR] START index=726
[VALIDATOR] START index=2676
[VALIDATOR] START index=1983
[VALIDATOR] START index=488
[VALIDATOR] START index=2908
[VALIDATOR] START index=2460
[VALIDATOR] START index=2677
[VALIDATOR] START index=727
[VALIDATOR] START index=1984
[VALIDATOR] START index=489
[VALIDATOR] START index=2909
[VALIDATOR] START index=2461
[VALIDATOR] START index=728
[VALIDATOR] START index=2678
[VALIDATOR] START index=1985
[VALIDATOR] START index=490
[VALIDATOR] START index=2910
[VALIDATOR] START index=2462
[VALIDATOR] START index=1986
[VALIDATOR] START index=729
[VALIDATOR] START index=2679
[VALIDATOR] START index=491
[VALIDATOR] START index=2463
[VALIDATOR] START index=2911
[VALIDATOR] START index=1987
[VALIDATOR] START index=730
[VALIDATOR] START index=2680
[VALIDATOR] START index=492
[VALIDATOR] START index=2912
[VALIDATOR] START index=2464
[VALIDATOR] START index=1988
[VALIDATOR] START index=2681
[VALIDATOR] START index=731
[VALIDATOR] START index=493
[VALIDATOR] START index=2913
[VALIDATOR] START index=2465
[VALIDATOR] START index=1989
[VALIDATOR] START index=2682
[VALIDATOR] START index=732
[VALIDATOR] START index=2914
[VALIDATOR] START index=2466
[VALIDATOR] START index=494
[VALIDATOR] START index=1990
[VALIDATOR] START index=2683
[VALIDATOR] START index=2915
[VALIDATOR] START index=2467
[VALIDATOR] START index=733
[VALIDATOR] START index=495
[VALIDATOR] START index=1991
[VALIDATOR] START index=2684
[VALIDATOR] START index=2916
[VALIDATOR] START index=496
[VALIDATOR] START index=2468
[VALIDATOR] START index=734
[VALIDATOR] START index=1992
[VALIDATOR] START index=2685
[VALIDATOR] START index=2917
[VALIDATOR] START index=497
[VALIDATOR] START index=2469
[VALIDATOR] START index=735
[VALIDATOR] START index=1993
[VALIDATOR] START index=2686
[VALIDATOR] START index=2918
[VALIDATOR] START index=2470
[VALIDATOR] START index=498
[VALIDATOR] START index=1994
[VALIDATOR] START index=2687
[VALIDATOR] START index=736
[VALIDATOR] START index=2919
[VALIDATOR] START index=2471
[VALIDATOR] START index=499
[VALIDATOR] START index=1995
[VALIDATOR] START index=737
[VALIDATOR] START index=2688
[VALIDATOR] START index=2920
[VALIDATOR] START index=2472
[VALIDATOR] START index=500
[VALIDATOR] START index=738
[VALIDATOR] START index=2689
[VALIDATOR] START index=2921
[VALIDATOR] START index=1996
[VALIDATOR] START index=2473
[VALIDATOR] START index=501
[VALIDATOR] START index=739
[VALIDATOR] START index=2922
[VALIDATOR] START index=1997
[VALIDATOR] START index=2690
[VALIDATOR] START index=2474
[VALIDATOR] START index=502
[VALIDATOR] START index=740
[VALIDATOR] START index=2923
[VALIDATOR] START index=2691
[VALIDATOR] START index=1998
[VALIDATOR] START index=2475
[VALIDATOR] START index=503
[VALIDATOR] START index=741
[VALIDATOR] START index=2924
[VALIDATOR] START index=2692
[VALIDATOR] START index=1999
[VALIDATOR] START index=2476
[VALIDATOR] START index=504
[VALIDATOR] START index=2925
[VALIDATOR] START index=742
[VALIDATOR] START index=2000
[VALIDATOR] START index=2693
[VALIDATOR] START index=2477
[VALIDATOR] START index=505
[VALIDATOR] START index=2926
[VALIDATOR] START index=2001
[VALIDATOR] START index=743
[VALIDATOR] bug=knapsack candidates=218
[VALIDATOR] START index=3157

 20%|██        | 8/40 [02:02<14:34, 27.34s/it]

[VALIDATOR] START index=2478
[VALIDATOR] START index=506
[VALIDATOR] START index=2927
[VALIDATOR] START index=2002
[VALIDATOR] START index=744
[VALIDATOR] START index=3158
[VALIDATOR] START index=2479
[VALIDATOR] START index=2928
[VALIDATOR] START index=507
[VALIDATOR] START index=2003
[VALIDATOR] START index=745

 22%|██▎       | 9/40 [02:08<10:41, 20.70s/it]

[VALIDATOR] bug=kth candidates=216
[VALIDATOR] START index=3375
[VALIDATOR] START index=2480
[VALIDATOR] START index=2929
[VALIDATOR] START index=2004
[VALIDATOR] START index=508
[VALIDATOR] START index=3376
[VALIDATOR] START index=746
[VALIDATOR] START index=2481

 25%|██▌       | 10/40 [02:13<07:51, 15.70s/it]

[VALIDATOR] bug=lcs_length candidates=215
[VALIDATOR] START index=3591
[VALIDATOR] START index=2005
[VALIDATOR] START index=509
[VALIDATOR] START index=3377
[VALIDATOR] START index=747
[VALIDATOR] START index=2482
[VALIDATOR] START index=3592
[VALIDATOR] START index=2006
[VALIDATOR] START index=510
[VALIDATOR] START index=3378
[VALIDATOR] START index=748
[VALIDATOR] START index=2483
[VALIDATOR] START index=3593
[VALIDATOR] START index=2007
[VALIDATOR] START index=511
[VALIDATOR] START index=3379
[VALIDATOR] START index=2484
[VALIDATOR] START index=749
[VALIDATOR] START index=3594
[VALIDATOR] START index=2008
[VALIDATOR] START index=512
[VALIDATOR] START index=3380
[VALIDATOR] START index=2485
[VALIDATOR] START index=750
[VALIDATOR] START index=3595
[VALIDATOR] START index=2009
[VALIDATOR] START index=513
[VALIDATOR] START index=3381
[VALIDATOR] START index=2486
[VALIDATOR] START index=3596
[VALIDATOR] START index=751
[VALIDATOR] START index=2010
[VALIDATOR] START index=514
[VALIDATOR] START index=3382
[VALIDATOR] START index=2487
[VALIDATOR] START index=752
[VALIDATOR] START index=2011
[VALIDATOR] START index=515
[VALIDATOR] START index=3597
[VALIDATOR] START index=3383
[VALIDATOR] START index=2488
[VALIDATOR] START index=3598
[VALIDATOR] START index=2012
[VALIDATOR] START index=516
[VALIDATOR] START index=753
[VALIDATOR] START index=3384
[VALIDATOR] START index=2489
[VALIDATOR] START index=517
[VALIDATOR] START index=2013
[VALIDATOR] START index=3599
[VALIDATOR] START index=3385
[VALIDATOR] START index=754
[VALIDATOR] START index=2490
[VALIDATOR] START index=2014
[VALIDATOR] START index=518
[VALIDATOR] START index=3600
[VALIDATOR] START index=3386
[VALIDATOR] START index=755
[VALIDATOR] START index=2491
[VALIDATOR] START index=2015
[VALIDATOR] START index=3601
[VALIDATOR] START index=519
[VALIDATOR] START index=3387
[VALIDATOR] START index=756
[VALIDATOR] START index=2492
[VALIDATOR] START index=2016

 28%|██▊       | 11/40 [02:45<10:01, 20.74s/it]

[VALIDATOR] bug=levenshtein candidates=289
[VALIDATOR] START index=3806
[VALIDATOR] START index=520
[VALIDATOR] START index=3388
[VALIDATOR] START index=757
[VALIDATOR] START index=2493
[VALIDATOR] START index=2017
[VALIDATOR] START index=3807
[VALIDATOR] START index=521
[VALIDATOR] START index=3389
[VALIDATOR] START index=758
[VALIDATOR] START index=2494
[VALIDATOR] START index=2018
[VALIDATOR] START index=3390
[VALIDATOR] START index=522
[VALIDATOR] START index=3808
[VALIDATOR] START index=2495
[VALIDATOR] START index=759
[VALIDATOR] START index=2019
[VALIDATOR] START index=3391
[VALIDATOR] START index=3809
[VALIDATOR] START index=523
[VALIDATOR] START index=2496
[VALIDATOR] START index=760
[VALIDATOR] START index=2020
[VALIDATOR] START index=3392
[VALIDATOR] START index=3810
[VALIDATOR] START index=524
[VALIDATOR] START index=2497
[VALIDATOR] START index=761
[VALIDATOR] START index=2021
[VALIDATOR] START index=3393
[VALIDATOR] START index=525
[VALIDATOR] START index=3811
[VALIDATOR] START index=2498
[VALIDATOR] START index=762
[VALIDATOR] START index=3394
[VALIDATOR] START index=2022
[VALIDATOR] START index=526
[VALIDATOR] START index=2499
[VALIDATOR] START index=763
[VALIDATOR] START index=2023
[VALIDATOR] START index=3395
[VALIDATOR] START index=527
[VALIDATOR] START index=2500
[VALIDATOR] START index=764
[VALIDATOR] START index=2024
[VALIDATOR] START index=3396
[VALIDATOR] START index=528
[VALIDATOR] START index=2501

 30%|███       | 12/40 [03:10<10:15, 21.99s/it]

[VALIDATOR] bug=lis candidates=246
[VALIDATOR] START index=4095
[VALIDATOR] START index=765
[VALIDATOR] START index=2025
[VALIDATOR] START index=529
[VALIDATOR] START index=3397
[VALIDATOR] START index=2502
[VALIDATOR] START index=4096
[VALIDATOR] START index=766
[VALIDATOR] START index=2026
[VALIDATOR] START index=530
[VALIDATOR] START index=3398
[VALIDATOR] START index=2503
[VALIDATOR] START index=4097
[VALIDATOR] START index=767
[VALIDATOR] START index=2027
[VALIDATOR] START index=531
[VALIDATOR] START index=3399
[VALIDATOR] START index=2504
[VALIDATOR] START index=4098
[VALIDATOR] START index=2028
[VALIDATOR] START index=768
[VALIDATOR] START index=532
[VALIDATOR] START index=3400

 32%|███▎      | 13/40 [03:21<08:27, 18.80s/it]

[VALIDATOR] bug=longest_common_subsequence candidates=251
[VALIDATOR] START index=4341
[VALIDATOR] START index=4099
[VALIDATOR] START index=769
[VALIDATOR] START index=2029
[VALIDATOR] START index=533
[VALIDATOR] START index=3401
[VALIDATOR] START index=4342
[VALIDATOR] START index=4100
[VALIDATOR] START index=770
[VALIDATOR] START index=2030
[VALIDATOR] START index=534
[VALIDATOR] START index=3402

 35%|███▌      | 14/40 [03:28<06:32, 15.09s/it]

[VALIDATOR] START index=4101
[VALIDATOR] bug=max_sublist_sum candidates=220
[VALIDATOR] START index=4592
[VALIDATOR] START index=2031
[VALIDATOR] START index=771
[VALIDATOR] START index=3403
[VALIDATOR] START index=535
[VALIDATOR] START index=4593
[VALIDATOR] START index=4102
[VALIDATOR] START index=2032
[VALIDATOR] START index=3404
[VALIDATOR] START index=536
[VALIDATOR] START index=772
[VALIDATOR] START index=4594
[VALIDATOR] START index=4103
[VALIDATOR] START index=2033
[VALIDATOR] START index=3405
[VALIDATOR] START index=773
[VALIDATOR] START index=537
[VALIDATOR] START index=4595
[VALIDATOR] START index=4104
[VALIDATOR] START index=3406
[VALIDATOR] START index=538
[VALIDATOR] START index=2034
[VALIDATOR] START index=774
[VALIDATOR] START index=4105
[VALIDATOR] START index=4596
[VALIDATOR] START index=3407
[VALIDATOR] START index=2035
[VALIDATOR] START index=539
[VALIDATOR] START index=4106
[VALIDATOR] START index=4597
[VALIDATOR] START index=775
[VALIDATOR] START index=3408
[VALIDATOR] START index=2036
[VALIDATOR] START index=540
[VALIDATOR] START index=4107
[VALIDATOR] START index=4598
[VALIDATOR] START index=3409
[VALIDATOR] START index=776
[VALIDATOR] START index=2037
[VALIDATOR] START index=541
[VALIDATOR] START index=4108
[VALIDATOR] START index=4599
[VALIDATOR] START index=3410
[VALIDATOR] START index=542
[VALIDATOR] START index=2038

 38%|███▊      | 15/40 [03:50<07:11, 17.27s/it]

[VALIDATOR] bug=mergesort candidates=254
[VALIDATOR] START index=4812
[VALIDATOR] START index=777
[VALIDATOR] START index=4600
[VALIDATOR] START index=3411
[VALIDATOR] START index=543
[VALIDATOR] START index=2039
[VALIDATOR] START index=4813
[VALIDATOR] START index=4601
[VALIDATOR] START index=778
[VALIDATOR] START index=3412
[VALIDATOR] START index=544
[VALIDATOR] START index=2040
[VALIDATOR] START index=4602
[VALIDATOR] START index=779
[VALIDATOR] START index=4814
[VALIDATOR] START index=3413
[VALIDATOR] START index=545
[VALIDATOR] START index=2041
[VALIDATOR] START index=780
[VALIDATOR] START index=4603
[VALIDATOR] START index=3414
[VALIDATOR] START index=4815
[VALIDATOR] START index=546
[VALIDATOR] START index=2042
[VALIDATOR] START index=3415
[VALIDATOR] START index=4816
[VALIDATOR] START index=4604
[VALIDATOR] START index=781
[VALIDATOR] START index=547
[VALIDATOR] START index=2043
[VALIDATOR] START index=3416
[VALIDATOR] START index=4605
[VALIDATOR] START index=548
[VALIDATOR] START index=4817
[VALIDATOR] START index=782
[VALIDATOR] START index=2044
[VALIDATOR] START index=3417
[VALIDATOR] START index=4606
[VALIDATOR] START index=783
[VALIDATOR] START index=549
[VALIDATOR] START index=2045
[VALIDATOR] START index=4818
[VALIDATOR] START index=4607
[VALIDATOR] START index=3418
[VALIDATOR] START index=784
[VALIDATOR] START index=550
[VALIDATOR] START index=2046
[VALIDATOR] START index=4819
[VALIDATOR] START index=3419
[VALIDATOR] START index=4608
[VALIDATOR] START index=551
[VALIDATOR] START index=785
[VALIDATOR] START index=2047
[VALIDATOR] START index=4820
[VALIDATOR] START index=4609
[VALIDATOR] START index=3420
[VALIDATOR] START index=552
[VALIDATOR] START index=786
[VALIDATOR] START index=2048
[VALIDATOR] START index=4821
[VALIDATOR] START index=3421
[VALIDATOR] START index=4610
[VALIDATOR] START index=553
[VALIDATOR] START index=787
[VALIDATOR] START index=2049
[VALIDATOR] START index=4611
[VALIDATOR] START index=4822
[VALIDATOR] START index=3422
[VALIDATOR] START index=554
[VALIDATOR] START index=2050
[VALIDATOR] START index=788

 40%|████      | 16/40 [04:26<09:08, 22.84s/it]

[VALIDATOR] bug=minimum_spanning_tree candidates=235
[VALIDATOR] START index=5066
[VALIDATOR] START index=4612
[VALIDATOR] START index=3423
[VALIDATOR] START index=555
[VALIDATOR] START index=789
[VALIDATOR] START index=2051
[VALIDATOR] START index=3424
[VALIDATOR] START index=4613
[VALIDATOR] START index=5067
[VALIDATOR] START index=556
[VALIDATOR] START index=2052
[VALIDATOR] START index=3425
[VALIDATOR] START index=4614
[VALIDATOR] START index=790
[VALIDATOR] START index=5068
[VALIDATOR] START index=557
[VALIDATOR] START index=4615
[VALIDATOR] START index=2053
[VALIDATOR] START index=3426
[VALIDATOR] START index=791
[VALIDATOR] START index=5069
[VALIDATOR] START index=4616
[VALIDATOR] START index=3427
[VALIDATOR] START index=2054
[VALIDATOR] START index=558
[VALIDATOR] START index=5070
[VALIDATOR] START index=792
[VALIDATOR] START index=4617
[VALIDATOR] START index=2055
[VALIDATOR] START index=3428
[VALIDATOR] START index=559
[VALIDATOR] START index=5071
[VALIDATOR] START index=793
[VALIDATOR] START index=2056
[VALIDATOR] START index=560
[VALIDATOR] START index=4618
[VALIDATOR] START index=3429
[VALIDATOR] START index=5072
[VALIDATOR] START index=794
[VALIDATOR] START index=561
[VALIDATOR] START index=4619
[VALIDATOR] START index=3430
[VALIDATOR] START index=2057
[VALIDATOR] START index=5073

 42%|████▎     | 17/40 [04:49<08:44, 22.82s/it]

[VALIDATOR] bug=next_palindrome candidates=263
[VALIDATOR] START index=5301
[VALIDATOR] START index=562
[VALIDATOR] START index=4620
[VALIDATOR] START index=3431

 45%|████▌     | 18/40 [04:49<05:55, 16.17s/it]

[VALIDATOR] START index=2058
[VALIDATOR] bug=next_permutation candidates=240
[VALIDATOR] START index=5564
[VALIDATOR] START index=5302
[VALIDATOR] START index=4621
[VALIDATOR] START index=563
[VALIDATOR] START index=3432
[VALIDATOR] START index=2059
[VALIDATOR] START index=5565
[VALIDATOR] START index=5303
[VALIDATOR] START index=4622
[VALIDATOR] START index=564
[VALIDATOR] START index=2060
[VALIDATOR] START index=5566
[VALIDATOR] START index=3433
[VALIDATOR] START index=4623
[VALIDATOR] START index=565
[VALIDATOR] START index=5304
[VALIDATOR] START index=5567
[VALIDATOR] START index=2061
[VALIDATOR] START index=3434
[VALIDATOR] START index=4624
[VALIDATOR] START index=5568
[VALIDATOR] START index=566
[VALIDATOR] START index=5305
[VALIDATOR] START index=2062
[VALIDATOR] START index=3435
[VALIDATOR] START index=4625

 48%|████▊     | 19/40 [05:04<05:28, 15.65s/it]

[VALIDATOR] START index=567
[VALIDATOR] bug=possible_change candidates=175
[VALIDATOR] START index=6000
[VALIDATOR] bug=pascal candidates=196
[VALIDATOR] START index=5804
[VALIDATOR] START index=2063
[VALIDATOR] START index=3436
[VALIDATOR] START index=568
[VALIDATOR] START index=4626
[VALIDATOR] START index=5805
[VALIDATOR] START index=2064
[VALIDATOR] START index=3437
[VALIDATOR] START index=6001
[VALIDATOR] START index=4627
[VALIDATOR] START index=569
[VALIDATOR] START index=5806
[VALIDATOR] START index=2065
[VALIDATOR] START index=3438
[VALIDATOR] START index=6002
[VALIDATOR] START index=570
[VALIDATOR] START index=4628
[VALIDATOR] START index=5807
[VALIDATOR] START index=2066
[VALIDATOR] START index=3439
[VALIDATOR] START index=571
[VALIDATOR] START index=5808
[VALIDATOR] START index=4629
[VALIDATOR] START index=2067
[VALIDATOR] START index=6003
[VALIDATOR] START index=3440
[VALIDATOR] START index=572
[VALIDATOR] START index=2068
[VALIDATOR] START index=4630
[VALIDATOR] START index=6004
[VALIDATOR] START index=5809
[VALIDATOR] START index=3441
[VALIDATOR] START index=573
[VALIDATOR] START index=2069
[VALIDATOR] START index=4631
[VALIDATOR] START index=6005
[VALIDATOR] START index=5810
[VALIDATOR] START index=3442
[VALIDATOR] START index=574
[VALIDATOR] START index=2070
[VALIDATOR] START index=4632
[VALIDATOR] START index=5811
[VALIDATOR] START index=6006
[VALIDATOR] START index=3443
[VALIDATOR] START index=575
[VALIDATOR] START index=4633
[VALIDATOR] START index=2071
[VALIDATOR] START index=5812
[VALIDATOR] START index=3444
[VALIDATOR] START index=6007
[VALIDATOR] START index=576
[VALIDATOR] START index=4634

 52%|█████▎    | 21/40 [05:30<04:36, 14.55s/it]

[VALIDATOR] START index=2072
[VALIDATOR] bug=powerset candidates=277
[VALIDATOR] START index=6175
[VALIDATOR] START index=3445
[VALIDATOR] START index=6008
[VALIDATOR] START index=577
[VALIDATOR] START index=6176
[VALIDATOR] START index=4635
[VALIDATOR] START index=2073
[VALIDATOR] START index=3446
[VALIDATOR] START index=6009
[VALIDATOR] START index=578
[VALIDATOR] START index=4636
[VALIDATOR] START index=2074
[VALIDATOR] START index=6177
[VALIDATOR] START index=3447
[VALIDATOR] START index=6010
[VALIDATOR] START index=2075
[VALIDATOR] START index=579
[VALIDATOR] START index=4637
[VALIDATOR] START index=6178
[VALIDATOR] START index=3448
[VALIDATOR] START index=6011
[VALIDATOR] START index=580
[VALIDATOR] START index=6179
[VALIDATOR] START index=2076
[VALIDATOR] START index=4638
[VALIDATOR] START index=3449
[VALIDATOR] START index=6012
[VALIDATOR] START index=581
[VALIDATOR] START index=2077
[VALIDATOR] START index=4639
[VALIDATOR] START index=6180
[VALIDATOR] START index=3450
[VALIDATOR] START index=6013
[VALIDATOR] START index=4640
[VALIDATOR] START index=6181
[VALIDATOR] START index=2078
[VALIDATOR] START index=3451
[VALIDATOR] START index=582
[VALIDATOR] START index=4641
[VALIDATOR] START index=6182
[VALIDATOR] START index=2079
[VALIDATOR] START index=6014
[VALIDATOR] START index=3452
[VALIDATOR] START index=583
[VALIDATOR] START index=4642
[VALIDATOR] START index=6183
[VALIDATOR] START index=2080
[VALIDATOR] START index=3453
[VALIDATOR] START index=6015
[VALIDATOR] START index=584
[VALIDATOR] START index=4643
[VALIDATOR] START index=2081
[VALIDATOR] START index=6184
[VALIDATOR] START index=3454
[VALIDATOR] START index=585
[VALIDATOR] START index=6016
[VALIDATOR] START index=4644
[VALIDATOR] START index=2082
[VALIDATOR] START index=3455
[VALIDATOR] START index=586
[VALIDATOR] START index=6185
[VALIDATOR] START index=6017
[VALIDATOR] START index=4645
[VALIDATOR] START index=2083
[VALIDATOR] START index=3456
[VALIDATOR] START index=587
[VALIDATOR] START index=6186
[VALIDATOR] START index=6018
[VALIDATOR] START index=4646
[VALIDATOR] START index=2084
[VALIDATOR] START index=3457
[VALIDATOR] START index=588
[VALIDATOR] START index=6187
[VALIDATOR] START index=6019
[VALIDATOR] START index=4647
[VALIDATOR] START index=2085
[VALIDATOR] START index=3458
[VALIDATOR] START index=589
[VALIDATOR] START index=6020
[VALIDATOR] START index=6188
[VALIDATOR] START index=4648
[VALIDATOR] START index=2086
[VALIDATOR] START index=3459
[VALIDATOR] START index=590
[VALIDATOR] START index=6189
[VALIDATOR] START index=6021
[VALIDATOR] START index=4649
[VALIDATOR] START index=2087
[VALIDATOR] START index=591
[VALIDATOR] START index=3460
[VALIDATOR] START index=6190
[VALIDATOR] START index=6022
[VALIDATOR] START index=4650
[VALIDATOR] START index=2088
[VALIDATOR] START index=3461
[VALIDATOR] START index=592
[VALIDATOR] START index=6191
[VALIDATOR] START index=4651
[VALIDATOR] START index=3462
[VALIDATOR] START index=2089
[VALIDATOR] START index=593
[VALIDATOR] START index=6023
[VALIDATOR] START index=6192
[VALIDATOR] START index=4652
[VALIDATOR] START index=3463
[VALIDATOR] START index=2090
[VALIDATOR] START index=594
[VALIDATOR] START index=6024
[VALIDATOR] START index=6193
[VALIDATOR] START index=4653
[VALIDATOR] START index=3464
[VALIDATOR] START index=6025
[VALIDATOR] START index=2091
[VALIDATOR] START index=595
[VALIDATOR] START index=6194
[VALIDATOR] START index=3465
[VALIDATOR] START index=4654
[VALIDATOR] START index=2092
[VALIDATOR] START index=6026
[VALIDATOR] START index=596
[VALIDATOR] START index=4655
[VALIDATOR] START index=6195
[VALIDATOR] START index=3466
[VALIDATOR] START index=2093
[VALIDATOR] START index=597
[VALIDATOR] START index=6027
[VALIDATOR] START index=4656
[VALIDATOR] START index=6196
[VALIDATOR] START index=3467
[VALIDATOR] START index=2094
[VALIDATOR] START index=598
[VALIDATOR] START index=6197
[VALIDATOR] START index=4657
[VALIDATOR] START index=3468
[VALIDATOR] START index=6028
[VALIDATOR] START index=599
[VALIDATOR] START index=2095
[VALIDATOR] START index=4658
[VALIDATOR] START index=6198
[VALIDATOR] START index=3469
[VALIDATOR] START index=6029
[VALIDATOR] START index=600
[VALIDATOR] START index=2096
[VALIDATOR] START index=4659
[VALIDATOR] START index=3470
[VALIDATOR] START index=6030
[VALIDATOR] START index=6199
[VALIDATOR] START index=601
[VALIDATOR] START index=2097
[VALIDATOR] START index=4660
[VALIDATOR] START index=6031
[VALIDATOR] START index=3471
[VALIDATOR] START index=6200
[VALIDATOR] START index=602
[VALIDATOR] START index=2098
[VALIDATOR] START index=6032
[VALIDATOR] START index=4661
[VALIDATOR] START index=3472
[VALIDATOR] START index=6201
[VALIDATOR] START index=603
[VALIDATOR] START index=2099
[VALIDATOR] START index=4662
[VALIDATOR] START index=3473
[VALIDATOR] START index=6202
[VALIDATOR] START index=604
[VALIDATOR] START index=6033
[VALIDATOR] START index=2100
[VALIDATOR] START index=4663
[VALIDATOR] START index=6203
[VALIDATOR] START index=3474
[VALIDATOR] START index=605
[VALIDATOR] START index=2101
[VALIDATOR] START index=6034
[VALIDATOR] START index=4664
[VALIDATOR] START index=6204
[VALIDATOR] START index=3475
[VALIDATOR] START index=606
[VALIDATOR] START index=2102
[VALIDATOR] START index=4665
[VALIDATOR] START index=6205
[VALIDATOR] START index=6035
[VALIDATOR] START index=3476
[VALIDATOR] START index=607
[VALIDATOR] START index=2103
[VALIDATOR] START index=4666
[VALIDATOR] START index=6206
[VALIDATOR] START index=3477

 55%|█████▌    | 22/40 [07:03<10:12, 34.03s/it]

[VALIDATOR] bug=quicksort candidates=258
[VALIDATOR] START index=6452
[VALIDATOR] START index=608
[VALIDATOR] START index=2104
[VALIDATOR] START index=4667
[VALIDATOR] START index=6207
[VALIDATOR] START index=3478
[VALIDATOR] START index=6453
[VALIDATOR] START index=609
[VALIDATOR] START index=2105
[VALIDATOR] START index=4668
[VALIDATOR] START index=6208
[VALIDATOR] START index=3479
[VALIDATOR] START index=6454
[VALIDATOR] START index=610
[VALIDATOR] START index=2106
[VALIDATOR] START index=6209
[VALIDATOR] START index=4669
[VALIDATOR] START index=3480
[VALIDATOR] START index=6455
[VALIDATOR] START index=611
[VALIDATOR] START index=2107
[VALIDATOR] START index=6210
[VALIDATOR] START index=4670
[VALIDATOR] START index=3481
[VALIDATOR] START index=612
[VALIDATOR] START index=6456
[VALIDATOR] START index=2108
[VALIDATOR] START index=6211
[VALIDATOR] START index=4671
[VALIDATOR] START index=3482
[VALIDATOR] START index=613
[VALIDATOR] START index=6457
[VALIDATOR] START index=2109
[VALIDATOR] START index=6212
[VALIDATOR] START index=4672
[VALIDATOR] START index=3483
[VALIDATOR] START index=614
[VALIDATOR] START index=6458
[VALIDATOR] START index=2110
[VALIDATOR] START index=4673
[VALIDATOR] START index=6213
[VALIDATOR] START index=3484
[VALIDATOR] START index=6459
[VALIDATOR] START index=615
[VALIDATOR] START index=4674
[VALIDATOR] START index=2111
[VALIDATOR] START index=6214
[VALIDATOR] START index=3485
[VALIDATOR] START index=6460
[VALIDATOR] START index=616
[VALIDATOR] START index=2112
[VALIDATOR] START index=4675
[VALIDATOR] START index=6215
[VALIDATOR] START index=3486
[VALIDATOR] START index=617
[VALIDATOR] START index=6461
[VALIDATOR] START index=2113
[VALIDATOR] START index=4676
[VALIDATOR] START index=6216
[VALIDATOR] START index=3487
[VALIDATOR] START index=618

 57%|█████▊    | 23/40 [07:33<09:17, 32.79s/it]

[VALIDATOR] bug=reverse_linked_list candidates=275
[VALIDATOR] START index=6710
[VALIDATOR] START index=2114
[VALIDATOR] START index=4677
[VALIDATOR] START index=6217
[VALIDATOR] START index=619
[VALIDATOR] START index=3488
[VALIDATOR] START index=6711
[VALIDATOR] START index=2115
[VALIDATOR] START index=4678
[VALIDATOR] START index=6218
[VALIDATOR] START index=3489
[VALIDATOR] START index=620
[VALIDATOR] START index=6712
[VALIDATOR] START index=4679
[VALIDATOR] START index=6219
[VALIDATOR] START index=621
[VALIDATOR] START index=3490
[VALIDATOR] START index=6713
[VALIDATOR] START index=6220
[VALIDATOR] START index=622
[VALIDATOR] START index=4680
[VALIDATOR] START index=3491
[VALIDATOR] START index=6714
[VALIDATOR] START index=6221
[VALIDATOR] START index=623
[VALIDATOR] START index=4681
[VALIDATOR] START index=2116
[VALIDATOR] START index=3492
[VALIDATOR] START index=6222
[VALIDATOR] START index=6715
[VALIDATOR] START index=4682
[VALIDATOR] START index=624
[VALIDATOR] START index=3493
[VALIDATOR] START index=2117
[VALIDATOR] START index=6223
[VALIDATOR] START index=625
[VALIDATOR] START index=6716
[VALIDATOR] START index=4683
[VALIDATOR] START index=3494
[VALIDATOR] START index=2118
[VALIDATOR] START index=626
[VALIDATOR] START index=6224
[VALIDATOR] START index=4684
[VALIDATOR] START index=6717
[VALIDATOR] START index=3495
[VALIDATOR] START index=2119
[VALIDATOR] START index=6225
[VALIDATOR] START index=4685
[VALIDATOR] START index=627
[VALIDATOR] START index=3496
[VALIDATOR] START index=6718
[VALIDATOR] START index=2120
[VALIDATOR] START index=4686
[VALIDATOR] START index=6226
[VALIDATOR] START index=3497
[VALIDATOR] START index=6719
[VALIDATOR] START index=628
[VALIDATOR] START index=2121
[VALIDATOR] START index=4687
[VALIDATOR] START index=6227
[VALIDATOR] START index=629
[VALIDATOR] START index=3498
[VALIDATOR] START index=6720
[VALIDATOR] START index=2122
[VALIDATOR] START index=6228
[VALIDATOR] START index=4688
[VALIDATOR] START index=630
[VALIDATOR] START index=3499
[VALIDATOR] START index=2123
[VALIDATOR] START index=6721
[VALIDATOR] START index=6229
[VALIDATOR] START index=4689
[VALIDATOR] START index=631
[VALIDATOR] START index=3500
[VALIDATOR] START index=2124
[VALIDATOR] START index=6722
[VALIDATOR] START index=6230
[VALIDATOR] START index=3501
[VALIDATOR] START index=4690
[VALIDATOR] START index=2125
[VALIDATOR] START index=632
[VALIDATOR] START index=6723
[VALIDATOR] START index=6231
[VALIDATOR] START index=3502
[VALIDATOR] START index=4691
[VALIDATOR] START index=2126
[VALIDATOR] START index=633
[VALIDATOR] START index=6724
[VALIDATOR] START index=4692
[VALIDATOR] START index=6232
[VALIDATOR] START index=2127
[VALIDATOR] START index=3503
[VALIDATOR] START index=634
[VALIDATOR] START index=6725
[VALIDATOR] START index=6233
[VALIDATOR] START index=2128
[VALIDATOR] START index=3504
[VALIDATOR] START index=635
[VALIDATOR] START index=4693
[VALIDATOR] START index=6726
[VALIDATOR] START index=6234
[VALIDATOR] START index=2129
[VALIDATOR] START index=3505
[VALIDATOR] START index=636
[VALIDATOR] START index=4694
[VALIDATOR] START index=6727
[VALIDATOR] START index=6235
[VALIDATOR] START index=637
[VALIDATOR] START index=4695
[VALIDATOR] START index=3506
[VALIDATOR] START index=2130
[VALIDATOR] START index=6728
[VALIDATOR] START index=6236
[VALIDATOR] START index=638
[VALIDATOR] START index=3507
[VALIDATOR] START index=4696
[VALIDATOR] START index=2131
[VALIDATOR] START index=6729
[VALIDATOR] START index=639
[VALIDATOR] START index=6237
[VALIDATOR] START index=3508
[VALIDATOR] START index=4697
[VALIDATOR] START index=2132
[VALIDATOR] START index=6730
[VALIDATOR] START index=640
[VALIDATOR] START index=6238
[VALIDATOR] START index=4698
[VALIDATOR] START index=3509
[VALIDATOR] START index=2133
[VALIDATOR] START index=641
[VALIDATOR] START index=6731
[VALIDATOR] START index=6239
[VALIDATOR] START index=4699
[VALIDATOR] START index=3510
[VALIDATOR] START index=2134
[VALIDATOR] START index=642
[VALIDATOR] START index=6240
[VALIDATOR] START index=6732
[VALIDATOR] START index=4700
[VALIDATOR] START index=3511
[VALIDATOR] START index=2135
[VALIDATOR] START index=6241
[VALIDATOR] START index=643
[VALIDATOR] START index=6733
[VALIDATOR] START index=4701
[VALIDATOR] START index=3512
[VALIDATOR] START index=2136
[VALIDATOR] START index=6242
[VALIDATOR] START index=644
[VALIDATOR] START index=6734
[VALIDATOR] START index=4702
[VALIDATOR] START index=3513
[VALIDATOR] START index=2137
[VALIDATOR] START index=645
[VALIDATOR] START index=6243
[VALIDATOR] START index=6735
[VALIDATOR] START index=3514
[VALIDATOR] START index=4703
[VALIDATOR] START index=2138
[VALIDATOR] START index=6736
[VALIDATOR] START index=6244
[VALIDATOR] START index=4704
[VALIDATOR] START index=646
[VALIDATOR] START index=3515
[VALIDATOR] START index=2139
[VALIDATOR] START index=4705
[VALIDATOR] START index=6737
[VALIDATOR] START index=6245
[VALIDATOR] START index=647
[VALIDATOR] START index=3516
[VALIDATOR] START index=2140
[VALIDATOR] START index=2141
[VALIDATOR] START index=6246
[VALIDATOR] START index=648
[VALIDATOR] START index=6738
[VALIDATOR] START index=3517
[VALIDATOR] START index=4706
[VALIDATOR] START index=2142
[VALIDATOR] START index=649
[VALIDATOR] START index=6739
[VALIDATOR] START index=4707
[VALIDATOR] START index=3518
[VALIDATOR] START index=6247
[VALIDATOR] START index=2143
[VALIDATOR] START index=650
[VALIDATOR] START index=6740
[VALIDATOR] START index=6248
[VALIDATOR] START index=4708
[VALIDATOR] START index=3519
[VALIDATOR] START index=2144
[VALIDATOR] START index=651
[VALIDATOR] START index=4709
[VALIDATOR] START index=6249
[VALIDATOR] START index=3520
[VALIDATOR] START index=6741
[VALIDATOR] START index=2145
[VALIDATOR] START index=4710
[VALIDATOR] START index=652
[VALIDATOR] START index=3521
[VALIDATOR] START index=6250
[VALIDATOR] START index=6742
[VALIDATOR] START index=653
[VALIDATOR] START index=2146
[VALIDATOR] START index=4711
[VALIDATOR] START index=3522
[VALIDATOR] START index=6251
[VALIDATOR] START index=6743
[VALIDATOR] START index=654
[VALIDATOR] START index=2147
[VALIDATOR] START index=3523
[VALIDATOR] START index=4712
[VALIDATOR] START index=6252
[VALIDATOR] START index=6744
[VALIDATOR] START index=2148
[VALIDATOR] START index=655
[VALIDATOR] START index=3524
[VALIDATOR] START index=4713
[VALIDATOR] START index=6253
[VALIDATOR] START index=6745
[VALIDATOR] START index=2149
[VALIDATOR] START index=656
[VALIDATOR] START index=3525
[VALIDATOR] START index=4714
[VALIDATOR] START index=6254
[VALIDATOR] START index=6746
[VALIDATOR] START index=2150
[VALIDATOR] START index=657
[VALIDATOR] START index=3526
[VALIDATOR] START index=4715
[VALIDATOR] START index=6255
[VALIDATOR] START index=6747
[VALIDATOR] START index=3527
[VALIDATOR] START index=658
[VALIDATOR] START index=4716
[VALIDATOR] START index=6256
[VALIDATOR] START index=6748
[VALIDATOR] START index=659
[VALIDATOR] START index=3528
[VALIDATOR] START index=4717
[VALIDATOR] START index=6257
[VALIDATOR] START index=2151
[VALIDATOR] START index=6749
[VALIDATOR] START index=660
[VALIDATOR] START index=3529
[VALIDATOR] START index=4718
[VALIDATOR] START index=6258
[VALIDATOR] START index=2152
[VALIDATOR] START index=6750
[VALIDATOR] START index=661
[VALIDATOR] START index=3530
[VALIDATOR] START index=4719
[VALIDATOR] START index=2153
[VALIDATOR] START index=6259
[VALIDATOR] START index=662
[VALIDATOR] START index=6751
[VALIDATOR] START index=3531
[VALIDATOR] START index=4720
[VALIDATOR] START index=2154
[VALIDATOR] START index=6260
[VALIDATOR] START index=663
[VALIDATOR] START index=6752
[VALIDATOR] START index=3532
[VALIDATOR] START index=4721
[VALIDATOR] START index=2155
[VALIDATOR] START index=664
[VALIDATOR] START index=6261
[VALIDATOR] START index=6753
[VALIDATOR] START index=3533
[VALIDATOR] START index=4722
[VALIDATOR] START index=2156
[VALIDATOR] START index=665
[VALIDATOR] START index=3534
[VALIDATOR] START index=6754
[VALIDATOR] START index=6262
[VALIDATOR] START index=4723
[VALIDATOR] START index=2157
[VALIDATOR] START index=3535
[VALIDATOR] START index=666
[VALIDATOR] START index=6755
[VALIDATOR] START index=6263
[VALIDATOR] START index=4724
[VALIDATOR] START index=2158
[VALIDATOR] START index=3536
[VALIDATOR] START index=667
[VALIDATOR] START index=6264
[VALIDATOR] START index=6756
[VALIDATOR] START index=4725
[VALIDATOR] START index=2159
[VALIDATOR] START index=668
[VALIDATOR] START index=3537
[VALIDATOR] START index=6265
[VALIDATOR] START index=6757
[VALIDATOR] START index=4726
[VALIDATOR] START index=3538
[VALIDATOR] START index=2160
[VALIDATOR] START index=669
[VALIDATOR] START index=6266
[VALIDATOR] START index=6758
[VALIDATOR] START index=2161
[VALIDATOR] START index=4727
[VALIDATOR] START index=670
[VALIDATOR] START index=3539
[VALIDATOR] START index=6267
[VALIDATOR] START index=6759
[VALIDATOR] START index=2162
[VALIDATOR] START index=671
[VALIDATOR] START index=4728
[VALIDATOR] START index=3540
[VALIDATOR] START index=6268
[VALIDATOR] START index=6760
[VALIDATOR] START index=2163
[VALIDATOR] START index=4729
[VALIDATOR] START index=672
[VALIDATOR] START index=3541
[VALIDATOR] START index=6269
[VALIDATOR] START index=6761
[VALIDATOR] START index=4730
[VALIDATOR] START index=2164
[VALIDATOR] START index=673
[VALIDATOR] START index=3542
[VALIDATOR] START index=6270
[VALIDATOR] START index=2165
[VALIDATOR] START index=6762
[VALIDATOR] START index=4731
[VALIDATOR] START index=674
[VALIDATOR] START index=3543
[VALIDATOR] START index=6271
[VALIDATOR] START index=2166
[VALIDATOR] START index=6763
[VALIDATOR] START index=4732
[VALIDATOR] START index=675
[VALIDATOR] START index=3544
[VALIDATOR] START index=6272
[VALIDATOR] START index=2167
[VALIDATOR] START index=4733
[VALIDATOR] START index=6764
[VALIDATOR] START index=3545
[VALIDATOR] START index=676
[VALIDATOR] START index=6273
[VALIDATOR] START index=2168
[VALIDATOR] START index=4734
[VALIDATOR] START index=6765
[VALIDATOR] START index=3546
[VALIDATOR] START index=677
[VALIDATOR] START index=6274
[VALIDATOR] START index=2169
[VALIDATOR] START index=6766
[VALIDATOR] START index=4735
[VALIDATOR] START index=3547
[VALIDATOR] START index=678
[VALIDATOR] START index=6275
[VALIDATOR] START index=6767
[VALIDATOR] START index=2170
[VALIDATOR] START index=4736
[VALIDATOR] START index=3548
[VALIDATOR] START index=679
[VALIDATOR] START index=6768
[VALIDATOR] START index=6276
[VALIDATOR] START index=2171
[VALIDATOR] START index=4737
[VALIDATOR] START index=3549
[VALIDATOR] START index=680
[VALIDATOR] START index=2172
[VALIDATOR] START index=6769
[VALIDATOR] START index=3550
[VALIDATOR] START index=6277
[VALIDATOR] START index=4738
[VALIDATOR] START index=681
[VALIDATOR] START index=2173
[VALIDATOR] START index=6770
[VALIDATOR] START index=6278
[VALIDATOR] START index=3551
[VALIDATOR] START index=4739
[VALIDATOR] START index=682
[VALIDATOR] START index=6771
[VALIDATOR] START index=2174
[VALIDATOR] START index=6279
[VALIDATOR] START index=4740
[VALIDATOR] START index=3552
[VALIDATOR] START index=683
[VALIDATOR] START index=6772
[VALIDATOR] START index=4741
[VALIDATOR] START index=2175
[VALIDATOR] START index=6280
[VALIDATOR] START index=3553
[VALIDATOR] START index=684
[VALIDATOR] START index=2176
[VALIDATOR] START index=6281
[VALIDATOR] START index=4742
[VALIDATOR] START index=6773
[VALIDATOR] START index=3554
[VALIDATOR] START index=685
[VALIDATOR] START index=2177
[VALIDATOR] START index=4743
[VALIDATOR] START index=6282
[VALIDATOR] START index=3555
[VALIDATOR] START index=686
[VALIDATOR] START index=6774
[VALIDATOR] START index=2178
[VALIDATOR] START index=4744
[VALIDATOR] START index=6283
[VALIDATOR] START index=3556
[VALIDATOR] START index=687
[VALIDATOR] START index=6775
[VALIDATOR] START index=3557
[VALIDATOR] START index=4745
[VALIDATOR] START index=2179
[VALIDATOR] START index=688
[VALIDATOR] START index=6284
[VALIDATOR] START index=6776
[VALIDATOR] START index=3558
[VALIDATOR] START index=4746
[VALIDATOR] START index=689
[VALIDATOR] START index=2180
[VALIDATOR] START index=6285
[VALIDATOR] START index=6777
[VALIDATOR] START index=3559
[VALIDATOR] START index=690
[VALIDATOR] START index=4747
[VALIDATOR] START index=2181
[VALIDATOR] START index=6286
[VALIDATOR] START index=6778
[VALIDATOR] START index=3560
[VALIDATOR] START index=4748
[VALIDATOR] START index=2182
[VALIDATOR] START index=691
[VALIDATOR] START index=6287
[VALIDATOR] START index=6779
[VALIDATOR] START index=3561
[VALIDATOR] START index=4749
[VALIDATOR] START index=2183
[VALIDATOR] START index=692
[VALIDATOR] START index=6288
[VALIDATOR] START index=6780
[VALIDATOR] START index=3562
[VALIDATOR] START index=4750
[VALIDATOR] START index=2184
[VALIDATOR] START index=693
[VALIDATOR] START index=6289
[VALIDATOR] START index=6781
[VALIDATOR] START index=3563
[VALIDATOR] START index=4751
[VALIDATOR] START index=2185
[VALIDATOR] START index=694
[VALIDATOR] START index=6290
[VALIDATOR] START index=3564
[VALIDATOR] START index=6782
[VALIDATOR] START index=4752
[VALIDATOR] START index=2186
[VALIDATOR] START index=695
[VALIDATOR] START index=6291
[VALIDATOR] START index=3565
[VALIDATOR] START index=6783
[VALIDATOR] START index=4753
[VALIDATOR] START index=696
[VALIDATOR] START index=2187
[VALIDATOR] START index=6292
[VALIDATOR] START index=3566
[VALIDATOR] START index=6784
[VALIDATOR] START index=4754
[VALIDATOR] START index=697
[VALIDATOR] START index=2188
[VALIDATOR] START index=6293
[VALIDATOR] START index=3567
[VALIDATOR] START index=6785
[VALIDATOR] START index=4755
[VALIDATOR] START index=698
[VALIDATOR] START index=2189
[VALIDATOR] START index=6294
[VALIDATOR] START index=6786
[VALIDATOR] START index=3568
[VALIDATOR] START index=4756
[VALIDATOR] START index=699
[VALIDATOR] START index=2190
[VALIDATOR] START index=6295
[VALIDATOR] START index=6787
[VALIDATOR] START index=3569
[VALIDATOR] START index=4757
[VALIDATOR] START index=700
[VALIDATOR] START index=2191
[VALIDATOR] START index=6788
[VALIDATOR] START index=6296
[VALIDATOR] START index=3570
[VALIDATOR] START index=4758
[VALIDATOR] START index=701
[VALIDATOR] START index=2192
[VALIDATOR] START index=6789
[VALIDATOR] START index=6297
[VALIDATOR] START index=4759
[VALIDATOR] START index=3571
[VALIDATOR] START index=702
[VALIDATOR] START index=2193
[VALIDATOR] START index=6790
[VALIDATOR] START index=4760
[VALIDATOR] START index=6298
[VALIDATOR] START index=3572
[VALIDATOR] START index=703
[VALIDATOR] START index=2194
[VALIDATOR] START index=6791
[VALIDATOR] START index=4761
[VALIDATOR] START index=6299
[VALIDATOR] START index=3573
[VALIDATOR] START index=704
[VALIDATOR] START index=2195
[VALIDATOR] START index=6792
[VALIDATOR] START index=4762
[VALIDATOR] START index=6300
[VALIDATOR] START index=3574

 60%|██████    | 24/40 [11:46<24:44, 92.81s/it]

[VALIDATOR] bug=rpn_eval candidates=213
[VALIDATOR] START index=6985
[VALIDATOR] START index=2196
[VALIDATOR] START index=6793
[VALIDATOR] START index=4763
[VALIDATOR] START index=6301
[VALIDATOR] START index=3575
[VALIDATOR] START index=2197
[VALIDATOR] START index=6986
[VALIDATOR] START index=6794
[VALIDATOR] START index=6302
[VALIDATOR] START index=4764
[VALIDATOR] START index=3576

 62%|██████▎   | 25/40 [11:52<17:07, 68.47s/it]

[VALIDATOR] bug=shortest_path_length candidates=246
[VALIDATOR] START index=7198
[VALIDATOR] START index=6987
[VALIDATOR] START index=6795
[VALIDATOR] START index=3577
[VALIDATOR] START index=4765
[VALIDATOR] START index=6303
[VALIDATOR] START index=7199
[VALIDATOR] START index=6988
[VALIDATOR] START index=6796
[VALIDATOR] START index=3578
[VALIDATOR] START index=4766
[VALIDATOR] START index=6304
[VALIDATOR] START index=7200
[VALIDATOR] START index=6989
[VALIDATOR] START index=6305
[VALIDATOR] START index=6797
[VALIDATOR] START index=4767
[VALIDATOR] START index=7201
[VALIDATOR] START index=3579
[VALIDATOR] START index=6990
[VALIDATOR] START index=4768
[VALIDATOR] START index=6306
[VALIDATOR] START index=6798
[VALIDATOR] START index=7202
[VALIDATOR] START index=3580
[VALIDATOR] START index=6991
[VALIDATOR] START index=6799
[VALIDATOR] START index=4769
[VALIDATOR] START index=7203
[VALIDATOR] START index=6307
[VALIDATOR] START index=3581
[VALIDATOR] START index=6992
[VALIDATOR] START index=4770
[VALIDATOR] START index=7204
[VALIDATOR] START index=6800
[VALIDATOR] START index=6308
[VALIDATOR] START index=6993
[VALIDATOR] START index=3582
[VALIDATOR] START index=4771
[VALIDATOR] START index=7205
[VALIDATOR] START index=6801
[VALIDATOR] START index=6994
[VALIDATOR] START index=6309
[VALIDATOR] START index=3583
[VALIDATOR] START index=7206
[VALIDATOR] START index=4772
[VALIDATOR] START index=6802
[VALIDATOR] START index=3584
[VALIDATOR] START index=6310
[VALIDATOR] START index=6995
[VALIDATOR] START index=7207
[VALIDATOR] START index=4773
[VALIDATOR] START index=3585
[VALIDATOR] START index=6803
[VALIDATOR] START index=6311
[VALIDATOR] START index=6996
[VALIDATOR] START index=7208
[VALIDATOR] START index=3586
[VALIDATOR] START index=4774
[VALIDATOR] START index=6804
[VALIDATOR] START index=6312
[VALIDATOR] START index=6997
[VALIDATOR] START index=7209
[VALIDATOR] START index=3587
[VALIDATOR] START index=4775
[VALIDATOR] START index=6805
[VALIDATOR] START index=6998
[VALIDATOR] START index=6313
[VALIDATOR] START index=7210
[VALIDATOR] START index=3588
[VALIDATOR] START index=4776
[VALIDATOR] START index=6806
[VALIDATOR] START index=6999
[VALIDATOR] START index=6314
[VALIDATOR] START index=4777
[VALIDATOR] START index=3589
[VALIDATOR] START index=7211
[VALIDATOR] START index=7000
[VALIDATOR] START index=6807
[VALIDATOR] START index=6315
[VALIDATOR] START index=4778
[VALIDATOR] START index=7212
[VALIDATOR] START index=3590
[VALIDATOR] START index=7001
[VALIDATOR] START index=6808
[VALIDATOR] START index=6316
[VALIDATOR] START index=4779
[VALIDATOR] START index=7213

 65%|██████▌   | 26/40 [12:36<14:19, 61.40s/it]

[VALIDATOR] START index=7002
[VALIDATOR] bug=shortest_path_lengths candidates=267
[VALIDATOR] START index=7444
[VALIDATOR] START index=6809
[VALIDATOR] START index=6317
[VALIDATOR] START index=7214
[VALIDATOR] START index=4780
[VALIDATOR] START index=7003
[VALIDATOR] START index=7445
[VALIDATOR] START index=6810
[VALIDATOR] START index=6318
[VALIDATOR] START index=4781
[VALIDATOR] START index=7215
[VALIDATOR] START index=7004
[VALIDATOR] START index=7446
[VALIDATOR] START index=6811
[VALIDATOR] START index=6319
[VALIDATOR] START index=4782
[VALIDATOR] START index=7005
[VALIDATOR] START index=7447
[VALIDATOR] START index=7216
[VALIDATOR] START index=6812
[VALIDATOR] START index=6320
[VALIDATOR] START index=4783
[VALIDATOR] START index=7006
[VALIDATOR] START index=6813
[VALIDATOR] START index=7217
[VALIDATOR] START index=7448
[VALIDATOR] START index=6321
[VALIDATOR] START index=4784
[VALIDATOR] START index=7007
[VALIDATOR] START index=6814
[VALIDATOR] START index=7218
[VALIDATOR] START index=7449
[VALIDATOR] START index=6322
[VALIDATOR] START index=4785
[VALIDATOR] START index=6815
[VALIDATOR] START index=7008
[VALIDATOR] START index=7450
[VALIDATOR] START index=7219
[VALIDATOR] START index=6323
[VALIDATOR] START index=4786
[VALIDATOR] START index=6816
[VALIDATOR] START index=7009
[VALIDATOR] START index=7451
[VALIDATOR] START index=7220
[VALIDATOR] START index=6324
[VALIDATOR] START index=4787
[VALIDATOR] START index=6817
[VALIDATOR] START index=7010
[VALIDATOR] START index=7452
[VALIDATOR] START index=7221
[VALIDATOR] START index=6325
[VALIDATOR] START index=4788
[VALIDATOR] START index=7011
[VALIDATOR] START index=6818
[VALIDATOR] START index=7453
[VALIDATOR] START index=7222
[VALIDATOR] START index=6326
[VALIDATOR] START index=4789
[VALIDATOR] START index=7012
[VALIDATOR] START index=7454
[VALIDATOR] START index=6819
[VALIDATOR] START index=7223
[VALIDATOR] START index=4790
[VALIDATOR] START index=6327
[VALIDATOR] START index=7013
[VALIDATOR] START index=7455
[VALIDATOR] START index=7224
[VALIDATOR] START index=6820
[VALIDATOR] START index=4791
[VALIDATOR] START index=6328
[VALIDATOR] START index=7014
[VALIDATOR] START index=7456
[VALIDATOR] START index=7225
[VALIDATOR] START index=6821
[VALIDATOR] START index=4792
[VALIDATOR] START index=6329
[VALIDATOR] START index=7015
[VALIDATOR] START index=7226
[VALIDATOR] START index=7457
[VALIDATOR] START index=6822
[VALIDATOR] START index=4793
[VALIDATOR] START index=6330
[VALIDATOR] START index=7016
[VALIDATOR] START index=7227
[VALIDATOR] START index=7458
[VALIDATOR] START index=6823
[VALIDATOR] START index=4794
[VALIDATOR] START index=7017
[VALIDATOR] START index=6331
[VALIDATOR] START index=7228
[VALIDATOR] START index=7459
[VALIDATOR] START index=6824
[VALIDATOR] START index=4795
[VALIDATOR] START index=6332
[VALIDATOR] START index=7018
[VALIDATOR] START index=7229
[VALIDATOR] START index=7460
[VALIDATOR] START index=6825
[VALIDATOR] START index=4796
[VALIDATOR] START index=6333
[VALIDATOR] START index=7230
[VALIDATOR] START index=7019
[VALIDATOR] START index=7461
[VALIDATOR] START index=6826
[VALIDATOR] START index=4797
[VALIDATOR] START index=6334
[VALIDATOR] START index=7020
[VALIDATOR] START index=7231
[VALIDATOR] START index=7462
[VALIDATOR] START index=6827
[VALIDATOR] START index=4798
[VALIDATOR] START index=6335
[VALIDATOR] START index=7232
[VALIDATOR] START index=7021
[VALIDATOR] START index=7463
[VALIDATOR] START index=6828
[VALIDATOR] START index=4799
[VALIDATOR] START index=6336
[VALIDATOR] START index=7022
[VALIDATOR] START index=7233
[VALIDATOR] START index=7464
[VALIDATOR] START index=4800
[VALIDATOR] START index=6829

 68%|██████▊   | 27/40 [13:37<13:19, 61.53s/it]

[VALIDATOR] bug=shortest_paths candidates=229
[VALIDATOR] START index=7711
[VALIDATOR] START index=6337
[VALIDATOR] START index=7234
[VALIDATOR] START index=7465
[VALIDATOR] START index=4801
[VALIDATOR] START index=6830
[VALIDATOR] START index=6338
[VALIDATOR] START index=7712
[VALIDATOR] START index=7235
[VALIDATOR] START index=7466
[VALIDATOR] START index=6831
[VALIDATOR] START index=4802
[VALIDATOR] START index=6339
[VALIDATOR] START index=7713
[VALIDATOR] START index=7236
[VALIDATOR] START index=7467
[VALIDATOR] START index=6832
[VALIDATOR] START index=4803
[VALIDATOR] START index=6340
[VALIDATOR] START index=7714
[VALIDATOR] START index=7237
[VALIDATOR] START index=7468
[VALIDATOR] START index=6833
[VALIDATOR] START index=4804
[VALIDATOR] START index=6341
[VALIDATOR] START index=7715
[VALIDATOR] START index=7238
[VALIDATOR] START index=7469
[VALIDATOR] START index=6834
[VALIDATOR] START index=4805
[VALIDATOR] START index=7716
[VALIDATOR] START index=6342
[VALIDATOR] START index=7239
[VALIDATOR] START index=7470
[VALIDATOR] START index=4806
[VALIDATOR] START index=6835
[VALIDATOR] START index=7717
[VALIDATOR] START index=6343
[VALIDATOR] START index=7471
[VALIDATOR] START index=7240
[VALIDATOR] START index=4807
[VALIDATOR] START index=6836
[VALIDATOR] START index=7718
[VALIDATOR] START index=6344
[VALIDATOR] START index=7472
[VALIDATOR] START index=7241
[VALIDATOR] START index=4808
[VALIDATOR] START index=7719
[VALIDATOR] START index=6837
[VALIDATOR] START index=6345
[VALIDATOR] START index=7473
[VALIDATOR] START index=7242
[VALIDATOR] START index=4809
[VALIDATOR] START index=7720
[VALIDATOR] START index=6346
[VALIDATOR] START index=7474
[VALIDATOR] START index=7243
[VALIDATOR] START index=7721
[VALIDATOR] START index=4810
[VALIDATOR] START index=7475
[VALIDATOR] START index=6347
[VALIDATOR] START index=7244
[VALIDATOR] START index=4811
[VALIDATOR] START index=7722
[VALIDATOR] START index=6838
[VALIDATOR] START index=7476
[VALIDATOR] START index=6348
[VALIDATOR] START index=7245
[VALIDATOR] START index=7723

 70%|███████   | 28/40 [14:12<10:43, 53.59s/it]

[VALIDATOR] bug=shunting_yard candidates=294
[VALIDATOR] START index=7940
[VALIDATOR] START index=6839
[VALIDATOR] START index=7477
[VALIDATOR] START index=7246
[VALIDATOR] START index=6349
[VALIDATOR] START index=7724
[VALIDATOR] START index=7941
[VALIDATOR] START index=6840
[VALIDATOR] START index=7478
[VALIDATOR] START index=7247
[VALIDATOR] START index=7725
[VALIDATOR] START index=6350
[VALIDATOR] START index=7942
[VALIDATOR] START index=6841
[VALIDATOR] START index=7479
[VALIDATOR] START index=7726
[VALIDATOR] START index=6351
[VALIDATOR] START index=7248
[VALIDATOR] START index=7943
[VALIDATOR] START index=6842
[VALIDATOR] START index=7480
[VALIDATOR] START index=7727
[VALIDATOR] START index=7249
[VALIDATOR] START index=6352
[VALIDATOR] START index=7944
[VALIDATOR] START index=6843
[VALIDATOR] START index=7481
[VALIDATOR] START index=7728
[VALIDATOR] START index=6353
[VALIDATOR] START index=7250
[VALIDATOR] START index=7945
[VALIDATOR] START index=6844
[VALIDATOR] START index=7482
[VALIDATOR] START index=7251
[VALIDATOR] START index=7729
[VALIDATOR] START index=6354
[VALIDATOR] START index=6845
[VALIDATOR] START index=7946
[VALIDATOR] START index=7252
[VALIDATOR] START index=7483
[VALIDATOR] START index=7730
[VALIDATOR] START index=6355
[VALIDATOR] START index=6846
[VALIDATOR] START index=7947
[VALIDATOR] START index=7484
[VALIDATOR] START index=7253
[VALIDATOR] START index=7731
[VALIDATOR] START index=6356
[VALIDATOR] START index=6847
[VALIDATOR] START index=7948
[VALIDATOR] START index=7485
[VALIDATOR] START index=7254
[VALIDATOR] START index=7732
[VALIDATOR] START index=6357
[VALIDATOR] START index=6848
[VALIDATOR] START index=7486
[VALIDATOR] START index=7255
[VALIDATOR] START index=7949
[VALIDATOR] START index=7733
[VALIDATOR] START index=6358
[VALIDATOR] START index=6849
[VALIDATOR] START index=7487
[VALIDATOR] START index=7256
[VALIDATOR] START index=7950
[VALIDATOR] START index=7734
[VALIDATOR] START index=6359
[VALIDATOR] START index=6850
[VALIDATOR] START index=7488
[VALIDATOR] START index=7257
[VALIDATOR] START index=7951
[VALIDATOR] START index=6360
[VALIDATOR] START index=7735
[VALIDATOR] START index=6851
[VALIDATOR] START index=7258
[VALIDATOR] START index=7489
[VALIDATOR] START index=7952
[VALIDATOR] START index=6361
[VALIDATOR] START index=7736
[VALIDATOR] START index=6852
[VALIDATOR] START index=7953
[VALIDATOR] START index=7259
[VALIDATOR] START index=7490
[VALIDATOR] START index=6362
[VALIDATOR] START index=7737
[VALIDATOR] START index=6853
[VALIDATOR] START index=7491
[VALIDATOR] START index=7954
[VALIDATOR] START index=7260
[VALIDATOR] START index=6363
[VALIDATOR] START index=7738
[VALIDATOR] START index=6854
[VALIDATOR] START index=7261
[VALIDATOR] START index=7955
[VALIDATOR] START index=7492
[VALIDATOR] START index=6364
[VALIDATOR] START index=7739
[VALIDATOR] START index=6855
[VALIDATOR] START index=7262
[VALIDATOR] START index=7493
[VALIDATOR] START index=7956
[VALIDATOR] START index=6365
[VALIDATOR] START index=7740
[VALIDATOR] START index=6856
[VALIDATOR] START index=7957
[VALIDATOR] START index=7263
[VALIDATOR] START index=7494
[VALIDATOR] START index=6366
[VALIDATOR] START index=7741
[VALIDATOR] START index=6857
[VALIDATOR] START index=7958
[VALIDATOR] START index=7495
[VALIDATOR] START index=7264
[VALIDATOR] START index=6367
[VALIDATOR] START index=6858
[VALIDATOR] START index=7742
[VALIDATOR] START index=7959
[VALIDATOR] START index=7496
[VALIDATOR] START index=6368
[VALIDATOR] START index=7265
[VALIDATOR] START index=6859
[VALIDATOR] START index=7743
[VALIDATOR] START index=7960
[VALIDATOR] START index=7497
[VALIDATOR] START index=7266
[VALIDATOR] START index=6369
[VALIDATOR] START index=7744
[VALIDATOR] START index=6860
[VALIDATOR] START index=7498
[VALIDATOR] START index=7961
[VALIDATOR] START index=7267
[VALIDATOR] START index=6370
[VALIDATOR] START index=7745
[VALIDATOR] START index=6861
[VALIDATOR] START index=7499
[VALIDATOR] START index=7268
[VALIDATOR] START index=7962
[VALIDATOR] START index=6371
[VALIDATOR] START index=6862
[VALIDATOR] START index=7746
[VALIDATOR] START index=7500
[VALIDATOR] START index=7269
[VALIDATOR] START index=7963
[VALIDATOR] START index=6372
[VALIDATOR] START index=7747
[VALIDATOR] START index=6863
[VALIDATOR] START index=7501
[VALIDATOR] START index=7964
[VALIDATOR] START index=7270
[VALIDATOR] START index=7748
[VALIDATOR] START index=6864
[VALIDATOR] START index=6373
[VALIDATOR] START index=7502
[VALIDATOR] START index=7965
[VALIDATOR] START index=7271
[VALIDATOR] START index=6374
[VALIDATOR] START index=7749
[VALIDATOR] START index=6865
[VALIDATOR] START index=7503
[VALIDATOR] START index=7966
[VALIDATOR] START index=7272
[VALIDATOR] START index=6375
[VALIDATOR] START index=6866
[VALIDATOR] START index=7750
[VALIDATOR] START index=7504
[VALIDATOR] START index=6376
[VALIDATOR] START index=7273
[VALIDATOR] START index=7967
[VALIDATOR] START index=6867
[VALIDATOR] START index=7751
[VALIDATOR] START index=7505
[VALIDATOR] START index=6377
[VALIDATOR] START index=7274
[VALIDATOR] START index=7968
[VALIDATOR] START index=6868
[VALIDATOR] START index=7752
[VALIDATOR] START index=7506
[VALIDATOR] START index=6378
[VALIDATOR] START index=7753
[VALIDATOR] START index=7969
[VALIDATOR] START index=7275
[VALIDATOR] START index=6869
[VALIDATOR] START index=7507
[VALIDATOR] START index=6379
[VALIDATOR] START index=7970
[VALIDATOR] START index=7754
[VALIDATOR] START index=7276
[VALIDATOR] START index=6870
[VALIDATOR] START index=7508
[VALIDATOR] START index=6380
[VALIDATOR] START index=7755
[VALIDATOR] START index=7277
[VALIDATOR] START index=7971
[VALIDATOR] START index=7509
[VALIDATOR] START index=6871
[VALIDATOR] START index=7756
[VALIDATOR] START index=6381
[VALIDATOR] START index=7510
[VALIDATOR] START index=7972
[VALIDATOR] START index=6872
[VALIDATOR] START index=7278
[VALIDATOR] START index=7757
[VALIDATOR] START index=7511
[VALIDATOR] START index=6382
[VALIDATOR] START index=7973
[VALIDATOR] START index=6873
[VALIDATOR] START index=7279
[VALIDATOR] START index=7758
[VALIDATOR] START index=7512
[VALIDATOR] START index=6383
[VALIDATOR] START index=7974
[VALIDATOR] START index=6874
[VALIDATOR] START index=7280
[VALIDATOR] START index=7759
[VALIDATOR] START index=7513
[VALIDATOR] START index=6384
[VALIDATOR] START index=7975
[VALIDATOR] START index=7281
[VALIDATOR] START index=7514
[VALIDATOR] START index=7760
[VALIDATOR] START index=6385
[VALIDATOR] START index=7282
[VALIDATOR] START index=7976
[VALIDATOR] START index=7761
[VALIDATOR] START index=7515
[VALIDATOR] START index=6386
[VALIDATOR] START index=7283
[VALIDATOR] START index=7977
[VALIDATOR] START index=6875
[VALIDATOR] START index=7762
[VALIDATOR] START index=7516
[VALIDATOR] START index=7284
[VALIDATOR] START index=6387
[VALIDATOR] START index=7978
[VALIDATOR] START index=6876
[VALIDATOR] START index=7763
[VALIDATOR] START index=7517
[VALIDATOR] START index=6388
[VALIDATOR] START index=7285
[VALIDATOR] START index=6877
[VALIDATOR] START index=7979
[VALIDATOR] START index=7764
[VALIDATOR] START index=7518
[VALIDATOR] START index=6389
[VALIDATOR] START index=7286
[VALIDATOR] START index=6878
[VALIDATOR] START index=7980
[VALIDATOR] START index=7765
[VALIDATOR] START index=7519
[VALIDATOR] START index=6390
[VALIDATOR] START index=7287
[VALIDATOR] START index=6879
[VALIDATOR] START index=7981
[VALIDATOR] START index=7766
[VALIDATOR] START index=7520
[VALIDATOR] START index=7288
[VALIDATOR] START index=6391
[VALIDATOR] START index=6880
[VALIDATOR] START index=7767
[VALIDATOR] START index=7982
[VALIDATOR] START index=7521
[VALIDATOR] START index=6392
[VALIDATOR] START index=7289
[VALIDATOR] START index=6881
[VALIDATOR] START index=7768
[VALIDATOR] START index=7522
[VALIDATOR] START index=7983
[VALIDATOR] START index=6393
[VALIDATOR] START index=7290
[VALIDATOR] START index=6882
[VALIDATOR] START index=7769
[VALIDATOR] START index=7523
[VALIDATOR] START index=7984
[VALIDATOR] START index=6394
[VALIDATOR] START index=7291
[VALIDATOR] START index=6883
[VALIDATOR] START index=7524
[VALIDATOR] START index=7770
[VALIDATOR] START index=7985
[VALIDATOR] START index=6395
[VALIDATOR] START index=7292
[VALIDATOR] START index=6884
[VALIDATOR] START index=7771
[VALIDATOR] START index=7986
[VALIDATOR] START index=7525
[VALIDATOR] START index=6396
[VALIDATOR] START index=6885
[VALIDATOR] START index=7293
[VALIDATOR] START index=7772
[VALIDATOR] START index=7526
[VALIDATOR] START index=7987
[VALIDATOR] START index=7294
[VALIDATOR] START index=6397
[VALIDATOR] START index=6886
[VALIDATOR] START index=7773
[VALIDATOR] START index=7527
[VALIDATOR] START index=7988
[VALIDATOR] START index=7295
[VALIDATOR] START index=6887
[VALIDATOR] START index=6398
[VALIDATOR] START index=7774
[VALIDATOR] START index=7528
[VALIDATOR] START index=7989
[VALIDATOR] START index=6888
[VALIDATOR] START index=7296
[VALIDATOR] START index=7775
[VALIDATOR] START index=6399
[VALIDATOR] START index=7529
[VALIDATOR] START index=7990
[VALIDATOR] START index=6889
[VALIDATOR] START index=7776
[VALIDATOR] START index=7297
[VALIDATOR] START index=6400
[VALIDATOR] START index=7530
[VALIDATOR] START index=7991
[VALIDATOR] START index=6890
[VALIDATOR] START index=7777
[VALIDATOR] START index=7298
[VALIDATOR] START index=6401
[VALIDATOR] START index=7531
[VALIDATOR] START index=7992
[VALIDATOR] START index=6891
[VALIDATOR] START index=6402
[VALIDATOR] START index=7778
[VALIDATOR] START index=7299
[VALIDATOR] START index=7532
[VALIDATOR] START index=7993
[VALIDATOR] START index=6892
[VALIDATOR] START index=6403
[VALIDATOR] START index=7779
[VALIDATOR] START index=7300
[VALIDATOR] START index=7533
[VALIDATOR] START index=7780
[VALIDATOR] START index=6893
[VALIDATOR] START index=7301
[VALIDATOR] START index=7994
[VALIDATOR] START index=6404
[VALIDATOR] START index=7534
[VALIDATOR] START index=6894
[VALIDATOR] START index=7781
[VALIDATOR] START index=7302
[VALIDATOR] START index=7995
[VALIDATOR] START index=6405
[VALIDATOR] START index=7535
[VALIDATOR] START index=7782
[VALIDATOR] START index=7303
[VALIDATOR] START index=7996
[VALIDATOR] START index=6406
[VALIDATOR] START index=7536
[VALIDATOR] START index=7783
[VALIDATOR] START index=7304
[VALIDATOR] START index=7997
[VALIDATOR] START index=6407
[VALIDATOR] START index=7784
[VALIDATOR] START index=7305
[VALIDATOR] START index=7537
[VALIDATOR] START index=6895
[VALIDATOR] START index=7998
[VALIDATOR] START index=6408
[VALIDATOR] START index=7785
[VALIDATOR] START index=7306
[VALIDATOR] START index=7538
[VALIDATOR] START index=6896
[VALIDATOR] START index=7999
[VALIDATOR] START index=6409
[VALIDATOR] START index=7786
[VALIDATOR] START index=7539
[VALIDATOR] START index=7307
[VALIDATOR] START index=6897
[VALIDATOR] START index=8000
[VALIDATOR] START index=6410
[VALIDATOR] START index=7787
[VALIDATOR] START index=7308
[VALIDATOR] START index=7540
[VALIDATOR] START index=6898
[VALIDATOR] START index=8001
[VALIDATOR] START index=6411
[VALIDATOR] START index=7788
[VALIDATOR] START index=7541
[VALIDATOR] START index=7309
[VALIDATOR] START index=6899
[VALIDATOR] START index=8002
[VALIDATOR] START index=6412
[VALIDATOR] START index=7789
[VALIDATOR] START index=7542
[VALIDATOR] START index=7310
[VALIDATOR] START index=6900
[VALIDATOR] START index=6413
[VALIDATOR] START index=8003
[VALIDATOR] START index=7790
[VALIDATOR] START index=7543
[VALIDATOR] START index=7311
[VALIDATOR] START index=6901
[VALIDATOR] START index=6414
[VALIDATOR] START index=7791
[VALIDATOR] START index=8004
[VALIDATOR] START index=7312
[VALIDATOR] START index=7544
[VALIDATOR] START index=6415
[VALIDATOR] START index=6902
[VALIDATOR] START index=8005
[VALIDATOR] START index=7792
[VALIDATOR] START index=7313
[VALIDATOR] START index=7545
[VALIDATOR] START index=6903
[VALIDATOR] START index=7793
[VALIDATOR] START index=8006
[VALIDATOR] START index=6416
[VALIDATOR] START index=7546
[VALIDATOR] START index=7314
[VALIDATOR] START index=6904
[VALIDATOR] START index=8007
[VALIDATOR] START index=6417
[VALIDATOR] START index=7794
[VALIDATOR] START index=7547
[VALIDATOR] START index=7315
[VALIDATOR] START index=6905
[VALIDATOR] START index=6418
[VALIDATOR] START index=8008
[VALIDATOR] START index=7795
[VALIDATOR] START index=7548
[VALIDATOR] START index=7316
[VALIDATOR] START index=6906
[VALIDATOR] START index=6419
[VALIDATOR] START index=8009
[VALIDATOR] START index=7549
[VALIDATOR] START index=7796
[VALIDATOR] START index=7317
[VALIDATOR] START index=6907
[VALIDATOR] START index=6420
[VALIDATOR] START index=7797
[VALIDATOR] START index=7550
[VALIDATOR] START index=8010
[VALIDATOR] START index=7318
[VALIDATOR] START index=7551
[VALIDATOR] START index=7798
[VALIDATOR] START index=6421
[VALIDATOR] START index=8011
[VALIDATOR] START index=7319
[VALIDATOR] START index=6422
[VALIDATOR] START index=7552
[VALIDATOR] START index=7799
[VALIDATOR] START index=7320
[VALIDATOR] START index=8012
[VALIDATOR] START index=6423
[VALIDATOR] START index=7553
[VALIDATOR] START index=7800
[VALIDATOR] START index=7321
[VALIDATOR] START index=8013
[VALIDATOR] START index=6908
[VALIDATOR] START index=7554
[VALIDATOR] START index=6424
[VALIDATOR] START index=7801
[VALIDATOR] START index=7322
[VALIDATOR] START index=8014
[VALIDATOR] START index=6909
[VALIDATOR] START index=7555
[VALIDATOR] START index=6425
[VALIDATOR] START index=7802
[VALIDATOR] START index=7323
[VALIDATOR] START index=8015
[VALIDATOR] START index=6910
[VALIDATOR] START index=6426
[VALIDATOR] START index=7556
[VALIDATOR] START index=7803
[VALIDATOR] START index=7324
[VALIDATOR] START index=8016
[VALIDATOR] START index=6911
[VALIDATOR] START index=7557
[VALIDATOR] START index=6427
[VALIDATOR] START index=7804
[VALIDATOR] START index=7325
[VALIDATOR] START index=6912
[VALIDATOR] START index=8017
[VALIDATOR] START index=7326
[VALIDATOR] START index=7805
[VALIDATOR] START index=6428
[VALIDATOR] START index=7558
[VALIDATOR] START index=6913
[VALIDATOR] START index=8018
[VALIDATOR] START index=7806
[VALIDATOR] START index=7327
[VALIDATOR] START index=6429
[VALIDATOR] START index=7559
[VALIDATOR] START index=6914
[VALIDATOR] START index=8019
[VALIDATOR] START index=7807
[VALIDATOR] START index=7328
[VALIDATOR] START index=6430
[VALIDATOR] START index=7560
[VALIDATOR] START index=6915
[VALIDATOR] START index=8020
[VALIDATOR] START index=7808
[VALIDATOR] START index=7329
[VALIDATOR] START index=7561
[VALIDATOR] START index=6431
[VALIDATOR] START index=6916
[VALIDATOR] START index=7809
[VALIDATOR] START index=8021
[VALIDATOR] START index=7562
[VALIDATOR] START index=7330
[VALIDATOR] START index=6432
[VALIDATOR] START index=6917
[VALIDATOR] START index=8022
[VALIDATOR] START index=7563
[VALIDATOR] START index=7810
[VALIDATOR] START index=7331
[VALIDATOR] START index=6433
[VALIDATOR] START index=6918
[VALIDATOR] START index=8023
[VALIDATOR] START index=7564
[VALIDATOR] START index=7811
[VALIDATOR] START index=7332
[VALIDATOR] START index=6434
[VALIDATOR] START index=6919
[VALIDATOR] START index=8024
[VALIDATOR] START index=7812
[VALIDATOR] START index=7565
[VALIDATOR] START index=7333
[VALIDATOR] START index=6435
[VALIDATOR] START index=6920
[VALIDATOR] START index=8025
[VALIDATOR] START index=7334
[VALIDATOR] START index=7566
[VALIDATOR] START index=7813
[VALIDATOR] START index=6436
[VALIDATOR] START index=6921
[VALIDATOR] START index=8026
[VALIDATOR] START index=7567
[VALIDATOR] START index=7814
[VALIDATOR] START index=6437
[VALIDATOR] START index=7335
[VALIDATOR] START index=6922
[VALIDATOR] START index=8027
[VALIDATOR] START index=6438
[VALIDATOR] START index=7568
[VALIDATOR] START index=7815
[VALIDATOR] START index=7336
[VALIDATOR] START index=6923
[VALIDATOR] START index=8028
[VALIDATOR] START index=7569
[VALIDATOR] START index=7816
[VALIDATOR] START index=6439
[VALIDATOR] START index=7337
[VALIDATOR] START index=6924
[VALIDATOR] START index=8029
[VALIDATOR] START index=7570
[VALIDATOR] START index=7817
[VALIDATOR] START index=6440
[VALIDATOR] START index=7338
[VALIDATOR] START index=6925
[VALIDATOR] START index=8030
[VALIDATOR] START index=7571
[VALIDATOR] START index=7818
[VALIDATOR] START index=6926
[VALIDATOR] START index=7339
[VALIDATOR] START index=6441
[VALIDATOR] START index=7819
[VALIDATOR] START index=8031
[VALIDATOR] START index=7572
[VALIDATOR] START index=6442
[VALIDATOR] START index=6927
[VALIDATOR] START index=7340
[VALIDATOR] START index=7820
[VALIDATOR] START index=7573
[VALIDATOR] START index=8032
[VALIDATOR] START index=6928
[VALIDATOR] START index=6443
[VALIDATOR] START index=7341
[VALIDATOR] START index=7821
[VALIDATOR] START index=7574
[VALIDATOR] START index=6444
[VALIDATOR] START index=7342
[VALIDATOR] START index=6929
[VALIDATOR] START index=8033
[VALIDATOR] START index=7575
[VALIDATOR] START index=7822
[VALIDATOR] START index=6445
[VALIDATOR] START index=6930
[VALIDATOR] START index=8034
[VALIDATOR] START index=7343
[VALIDATOR] START index=7576
[VALIDATOR] START index=6446
[VALIDATOR] START index=7823
[VALIDATOR] START index=6931
[VALIDATOR] START index=7344
[VALIDATOR] START index=8035
[VALIDATOR] START index=7824
[VALIDATOR] START index=7577
[VALIDATOR] START index=6932
[VALIDATOR] START index=6447
[VALIDATOR] START index=7345
[VALIDATOR] START index=8036
[VALIDATOR] START index=7825
[VALIDATOR] START index=7578
[VALIDATOR] START index=6448
[VALIDATOR] START index=7346
[VALIDATOR] START index=6933
[VALIDATOR] START index=8037
[VALIDATOR] START index=7826
[VALIDATOR] START index=7579
[VALIDATOR] START index=6449
[VALIDATOR] START index=6934
[VALIDATOR] START index=7347
[VALIDATOR] START index=8038
[VALIDATOR] START index=7827
[VALIDATOR] START index=7580
[VALIDATOR] START index=6450
[VALIDATOR] START index=6935
[VALIDATOR] START index=7348
[VALIDATOR] START index=8039
[VALIDATOR] START index=7581
[VALIDATOR] START index=7828
[VALIDATOR] START index=6451
[VALIDATOR] START index=6936
[VALIDATOR] START index=7349
[VALIDATOR] START index=8040
[VALIDATOR] START index=7582
[VALIDATOR] START index=7829
[VALIDATOR] START index=6937

 72%|███████▎  | 29/40 [19:23<23:46, 129.67s/it]

[VALIDATOR] START index=7350
[VALIDATOR] bug=sieve candidates=234
[VALIDATOR] START index=8234
[VALIDATOR] START index=8041
[VALIDATOR] START index=7583
[VALIDATOR] START index=7830
[VALIDATOR] START index=6938
[VALIDATOR] START index=8235
[VALIDATOR] START index=7351
[VALIDATOR] START index=8042
[VALIDATOR] START index=7584
[VALIDATOR] START index=7831
[VALIDATOR] START index=6939
[VALIDATOR] START index=8236
[VALIDATOR] START index=7352
[VALIDATOR] START index=7585
[VALIDATOR] START index=8043
[VALIDATOR] START index=7832
[VALIDATOR] START index=6940
[VALIDATOR] START index=8237
[VALIDATOR] START index=7353
[VALIDATOR] START index=7586
[VALIDATOR] START index=8044
[VALIDATOR] START index=7833
[VALIDATOR] START index=8238
[VALIDATOR] START index=6941
[VALIDATOR] START index=7354
[VALIDATOR] START index=7587
[VALIDATOR] START index=8045
[VALIDATOR] START index=7834
[VALIDATOR] START index=8239
[VALIDATOR] START index=6942
[VALIDATOR] START index=7355
[VALIDATOR] START index=7588
[VALIDATOR] START index=8046
[VALIDATOR] START index=7835
[VALIDATOR] START index=8240
[VALIDATOR] START index=6943
[VALIDATOR] START index=7356
[VALIDATOR] START index=8047
[VALIDATOR] START index=7589
[VALIDATOR] START index=7836
[VALIDATOR] START index=8241
[VALIDATOR] START index=6944
[VALIDATOR] START index=7357
[VALIDATOR] START index=8048
[VALIDATOR] START index=7590
[VALIDATOR] START index=6945
[VALIDATOR] START index=7358
[VALIDATOR] START index=7837
[VALIDATOR] START index=8242
[VALIDATOR] START index=7591
[VALIDATOR] START index=8049
[VALIDATOR] START index=7359
[VALIDATOR] START index=7838
[VALIDATOR] START index=8243
[VALIDATOR] START index=7592
[VALIDATOR] START index=8050
[VALIDATOR] START index=7360
[VALIDATOR] START index=8244
[VALIDATOR] START index=7839
[VALIDATOR] START index=7593
[VALIDATOR] START index=8051
[VALIDATOR] START index=8245
[VALIDATOR] START index=7361
[VALIDATOR] START index=7840
[VALIDATOR] START index=6946
[VALIDATOR] START index=7594
[VALIDATOR] START index=8246
[VALIDATOR] START index=8052
[VALIDATOR] START index=7362
[VALIDATOR] START index=7841
[VALIDATOR] START index=6947
[VALIDATOR] START index=7595
[VALIDATOR] START index=7363
[VALIDATOR] START index=8247
[VALIDATOR] START index=8053
[VALIDATOR] START index=7842
[VALIDATOR] START index=6948
[VALIDATOR] START index=7596
[VALIDATOR] START index=7364
[VALIDATOR] START index=8248
[VALIDATOR] START index=8054
[VALIDATOR] START index=7843
[VALIDATOR] START index=6949
[VALIDATOR] START index=7597
[VALIDATOR] START index=8249
[VALIDATOR] START index=7365

 75%|███████▌  | 30/40 [20:08<17:24, 104.43s/it]

[VALIDATOR] START index=7844
[VALIDATOR] bug=sqrt candidates=254
[VALIDATOR] START index=8468
[VALIDATOR] START index=8055
[VALIDATOR] START index=8250
[VALIDATOR] START index=7366
[VALIDATOR] START index=7598
[VALIDATOR] START index=7845
[VALIDATOR] START index=8469
[VALIDATOR] START index=8056

 78%|███████▊  | 31/40 [20:13<11:14, 74.90s/it]

[VALIDATOR] START index=7367
[VALIDATOR] bug=subsequences candidates=204
[VALIDATOR] START index=8722
[VALIDATOR] START index=7599
[VALIDATOR] START index=7846
[VALIDATOR] START index=8057
[VALIDATOR] START index=7368
[VALIDATOR] START index=8723
[VALIDATOR] START index=7600
[VALIDATOR] START index=7847
[VALIDATOR] START index=8058
[VALIDATOR] START index=7369
[VALIDATOR] START index=7848
[VALIDATOR] START index=8724
[VALIDATOR] START index=7601
[VALIDATOR] START index=8059
[VALIDATOR] START index=8470
[VALIDATOR] START index=7370
[VALIDATOR] START index=7849
[VALIDATOR] START index=7602
[VALIDATOR] START index=8725
[VALIDATOR] START index=8060
[VALIDATOR] START index=7371
[VALIDATOR] START index=7850
[VALIDATOR] START index=7603
[VALIDATOR] START index=8726
[VALIDATOR] START index=8061
[VALIDATOR] START index=7372
[VALIDATOR] START index=7851
[VALIDATOR] START index=7604
[VALIDATOR] START index=8727
[VALIDATOR] START index=8062
[VALIDATOR] START index=7852
[VALIDATOR] START index=7373
[VALIDATOR] START index=7605
[VALIDATOR] START index=8471
[VALIDATOR] START index=8728
[VALIDATOR] START index=8063
[VALIDATOR] START index=7853
[VALIDATOR] START index=7374
[VALIDATOR] START index=8472
[VALIDATOR] START index=7606
[VALIDATOR] START index=8729
[VALIDATOR] START index=8064
[VALIDATOR] START index=7854
[VALIDATOR] START index=7375
[VALIDATOR] START index=7607
[VALIDATOR] START index=8730
[VALIDATOR] START index=8065
[VALIDATOR] START index=7376
[VALIDATOR] START index=7855
[VALIDATOR] START index=8731
[VALIDATOR] START index=7608
[VALIDATOR] START index=8066
[VALIDATOR] START index=7377
[VALIDATOR] START index=7856
[VALIDATOR] START index=8732
[VALIDATOR] START index=7609
[VALIDATOR] START index=8473
[VALIDATOR] START index=7378
[VALIDATOR] START index=8067
[VALIDATOR] START index=7857
[VALIDATOR] START index=8733
[VALIDATOR] START index=7610
[VALIDATOR] START index=7379
[VALIDATOR] START index=8068
[VALIDATOR] START index=7858
[VALIDATOR] START index=8734
[VALIDATOR] START index=7611
[VALIDATOR] START index=7380
[VALIDATOR] START index=7859
[VALIDATOR] START index=8069
[VALIDATOR] START index=8735
[VALIDATOR] START index=7612
[VALIDATOR] START index=8070
[VALIDATOR] START index=7381
[VALIDATOR] START index=8474
[VALIDATOR] START index=7860
[VALIDATOR] START index=8736
[VALIDATOR] START index=7613
[VALIDATOR] START index=8071
[VALIDATOR] START index=7861
[VALIDATOR] START index=7382
[VALIDATOR] START index=8475
[VALIDATOR] START index=8737
[VALIDATOR] START index=7614
[VALIDATOR] START index=8072
[VALIDATOR] START index=7862
[VALIDATOR] START index=7383
[VALIDATOR] START index=8738
[VALIDATOR] START index=7615
[VALIDATOR] START index=8073
[VALIDATOR] START index=7384
[VALIDATOR] START index=7863
[VALIDATOR] START index=8739
[VALIDATOR] START index=7616
[VALIDATOR] START index=8074
[VALIDATOR] START index=7385
[VALIDATOR] START index=7864
[VALIDATOR] START index=8740
[VALIDATOR] START index=8476
[VALIDATOR] START index=7617
[VALIDATOR] START index=8075
[VALIDATOR] START index=7386
[VALIDATOR] START index=7865
[VALIDATOR] START index=8741
[VALIDATOR] START index=8477
[VALIDATOR] START index=7618
[VALIDATOR] START index=7387
[VALIDATOR] START index=8076
[VALIDATOR] START index=8742
[VALIDATOR] START index=7866
[VALIDATOR] START index=8478
[VALIDATOR] START index=7619
[VALIDATOR] START index=8077
[VALIDATOR] START index=7388
[VALIDATOR] START index=8743
[VALIDATOR] START index=7867
[VALIDATOR] START index=7620
[VALIDATOR] START index=8078
[VALIDATOR] START index=7389
[VALIDATOR] START index=8744
[VALIDATOR] START index=7868
[VALIDATOR] START index=7621
[VALIDATOR] START index=8079
[VALIDATOR] START index=8745
[VALIDATOR] START index=7390
[VALIDATOR] START index=7869
[VALIDATOR] START index=7622
[VALIDATOR] START index=8479
[VALIDATOR] START index=8080
[VALIDATOR] START index=8746
[VALIDATOR] START index=7870
[VALIDATOR] START index=7391
[VALIDATOR] START index=7623
[VALIDATOR] START index=8480
[VALIDATOR] START index=8081
[VALIDATOR] START index=8747
[VALIDATOR] START index=7871
[VALIDATOR] START index=7392
[VALIDATOR] START index=7624
[VALIDATOR] START index=8082
[VALIDATOR] START index=8748
[VALIDATOR] START index=7872
[VALIDATOR] START index=7393
[VALIDATOR] START index=7625
[VALIDATOR] START index=8083
[VALIDATOR] START index=8749
[VALIDATOR] START index=7873
[VALIDATOR] START index=7394
[VALIDATOR] START index=7626
[VALIDATOR] START index=8084
[VALIDATOR] START index=8750
[VALIDATOR] START index=8481
[VALIDATOR] START index=7874
[VALIDATOR] START index=7395
[VALIDATOR] START index=7627
[VALIDATOR] START index=8085
[VALIDATOR] START index=8751
[VALIDATOR] START index=7875
[VALIDATOR] START index=7396
[VALIDATOR] START index=7628
[VALIDATOR] START index=8086
[VALIDATOR] START index=8752
[VALIDATOR] START index=7876
[VALIDATOR] START index=7397
[VALIDATOR] START index=7629
[VALIDATOR] START index=8087
[VALIDATOR] START index=8753
[VALIDATOR] START index=7877
[VALIDATOR] START index=7398
[VALIDATOR] START index=7630
[VALIDATOR] START index=8482
[VALIDATOR] START index=8088
[VALIDATOR] START index=7878
[VALIDATOR] START index=7399
[VALIDATOR] START index=8754
[VALIDATOR] START index=7631
[VALIDATOR] START index=8483
[VALIDATOR] START index=8755
[VALIDATOR] START index=7879
[VALIDATOR] START index=7400
[VALIDATOR] START index=8089
[VALIDATOR] START index=7632
[VALIDATOR] START index=8756
[VALIDATOR] START index=7401
[VALIDATOR] START index=8090
[VALIDATOR] START index=7880
[VALIDATOR] START index=7633
[VALIDATOR] START index=8757
[VALIDATOR] START index=7881
[VALIDATOR] START index=8091
[VALIDATOR] START index=7402
[VALIDATOR] START index=7634
[VALIDATOR] START index=8484
[VALIDATOR] START index=7403
[VALIDATOR] START index=8758
[VALIDATOR] START index=7882
[VALIDATOR] START index=8092
[VALIDATOR] START index=7635
[VALIDATOR] START index=8759
[VALIDATOR] START index=7404
[VALIDATOR] START index=7883
[VALIDATOR] START index=8093
[VALIDATOR] START index=7636
[VALIDATOR] START index=8760
[VALIDATOR] START index=7405
[VALIDATOR] START index=7884
[VALIDATOR] START index=7637
[VALIDATOR] START index=8094
[VALIDATOR] START index=8761
[VALIDATOR] START index=7406
[VALIDATOR] START index=7638
[VALIDATOR] START index=8095
[VALIDATOR] START index=7885
[VALIDATOR] START index=8485
[VALIDATOR] START index=8762
[VALIDATOR] START index=7639
[VALIDATOR] START index=7886
[VALIDATOR] START index=7407
[VALIDATOR] START index=8096
[VALIDATOR] START index=8763
[VALIDATOR] START index=7640
[VALIDATOR] START index=7887
[VALIDATOR] START index=7408
[VALIDATOR] START index=8097
[VALIDATOR] START index=8764
[VALIDATOR] START index=7641
[VALIDATOR] START index=7409
[VALIDATOR] START index=7888
[VALIDATOR] START index=8098
[VALIDATOR] START index=7642
[VALIDATOR] START index=8765
[VALIDATOR] START index=8486
[VALIDATOR] START index=7410
[VALIDATOR] START index=7889
[VALIDATOR] START index=8099
[VALIDATOR] START index=7643
[VALIDATOR] START index=8766
[VALIDATOR] START index=7411
[VALIDATOR] START index=7890
[VALIDATOR] START index=8100
[VALIDATOR] START index=7644
[VALIDATOR] START index=8767
[VALIDATOR] START index=7891
[VALIDATOR] START index=7412
[VALIDATOR] START index=8101
[VALIDATOR] START index=7645

 80%|████████  | 32/40 [22:28<12:22, 92.79s/it]

[VALIDATOR] bug=to_base candidates=257
[VALIDATOR] START index=8926
[VALIDATOR] START index=7892
[VALIDATOR] START index=7413
[VALIDATOR] START index=8487
[VALIDATOR] START index=8102
[VALIDATOR] START index=7646
[VALIDATOR] START index=8927
[VALIDATOR] START index=7893
[VALIDATOR] START index=7414
[VALIDATOR] START index=8103
[VALIDATOR] START index=7647
[VALIDATOR] START index=8928
[VALIDATOR] START index=7894
[VALIDATOR] START index=7415
[VALIDATOR] START index=8104
[VALIDATOR] START index=7648
[VALIDATOR] START index=7895
[VALIDATOR] START index=8929
[VALIDATOR] START index=7416
[VALIDATOR] START index=8105
[VALIDATOR] START index=8488
[VALIDATOR] START index=7649
[VALIDATOR] START index=7896
[VALIDATOR] START index=8930
[VALIDATOR] START index=7417
[VALIDATOR] START index=8106
[VALIDATOR] START index=8489
[VALIDATOR] START index=7650
[VALIDATOR] START index=7897
[VALIDATOR] START index=8931
[VALIDATOR] START index=7418
[VALIDATOR] START index=8107
[VALIDATOR] START index=8490
[VALIDATOR] START index=7651
[VALIDATOR] START index=7898
[VALIDATOR] START index=8932
[VALIDATOR] START index=8108
[VALIDATOR] START index=7419
[VALIDATOR] START index=7652
[VALIDATOR] START index=7899
[VALIDATOR] START index=8933
[VALIDATOR] START index=7420
[VALIDATOR] START index=8109
[VALIDATOR] START index=7653
[VALIDATOR] START index=7900
[VALIDATOR] START index=8934
[VALIDATOR] START index=7421
[VALIDATOR] START index=8110
[VALIDATOR] START index=7654
[VALIDATOR] START index=7901
[VALIDATOR] START index=8935
[VALIDATOR] START index=8491
[VALIDATOR] START index=8111
[VALIDATOR] START index=7422
[VALIDATOR] START index=7655
[VALIDATOR] START index=7902
[VALIDATOR] START index=8936
[VALIDATOR] START index=8112
[VALIDATOR] START index=7423
[VALIDATOR] START index=7903
[VALIDATOR] START index=7656
[VALIDATOR] START index=8937
[VALIDATOR] START index=8113
[VALIDATOR] START index=7424
[VALIDATOR] START index=7904
[VALIDATOR] START index=7657
[VALIDATOR] START index=8938
[VALIDATOR] START index=8114
[VALIDATOR] START index=8492
[VALIDATOR] START index=7425
[VALIDATOR] START index=7905
[VALIDATOR] START index=8939
[VALIDATOR] START index=7658
[VALIDATOR] START index=8115
[VALIDATOR] START index=7426
[VALIDATOR] START index=7906
[VALIDATOR] START index=8940
[VALIDATOR] START index=7659
[VALIDATOR] START index=8116
[VALIDATOR] START index=7427
[VALIDATOR] START index=7907
[VALIDATOR] START index=7660
[VALIDATOR] START index=8941
[VALIDATOR] START index=7428
[VALIDATOR] START index=7908
[VALIDATOR] START index=8117
[VALIDATOR] START index=8942
[VALIDATOR] START index=8493
[VALIDATOR] START index=7661
[VALIDATOR] START index=7909
[VALIDATOR] START index=7429
[VALIDATOR] START index=8118
[VALIDATOR] START index=8943
[VALIDATOR] START index=7662
[VALIDATOR] START index=7910
[VALIDATOR] START index=8119
[VALIDATOR] START index=8944
[VALIDATOR] START index=7430
[VALIDATOR] START index=7663
[VALIDATOR] START index=7911
[VALIDATOR] START index=8120
[VALIDATOR] START index=8945
[VALIDATOR] START index=7664
[VALIDATOR] START index=7431
[VALIDATOR] START index=8494
[VALIDATOR] START index=7912
[VALIDATOR] START index=8946
[VALIDATOR] START index=8121
[VALIDATOR] START index=7665
[VALIDATOR] START index=7432
[VALIDATOR] START index=7913
[VALIDATOR] START index=8947
[VALIDATOR] START index=8122
[VALIDATOR] START index=7666
[VALIDATOR] START index=7433
[VALIDATOR] START index=7914
[VALIDATOR] START index=8948
[VALIDATOR] START index=7667
[VALIDATOR] START index=8123
[VALIDATOR] START index=7434
[VALIDATOR] START index=7915
[VALIDATOR] START index=7668
[VALIDATOR] START index=8949
[VALIDATOR] START index=8495
[VALIDATOR] START index=8124
[VALIDATOR] START index=7435
[VALIDATOR] START index=7669
[VALIDATOR] START index=8950
[VALIDATOR] START index=7916
[VALIDATOR] START index=8125
[VALIDATOR] START index=7436
[VALIDATOR] START index=7670
[VALIDATOR] START index=8951
[VALIDATOR] START index=7917
[VALIDATOR] START index=8126
[VALIDATOR] START index=7437
[VALIDATOR] START index=8952
[VALIDATOR] START index=7671
[VALIDATOR] START index=7918
[VALIDATOR] START index=8127
[VALIDATOR] START index=7438
[VALIDATOR] START index=8496
[VALIDATOR] START index=8953
[VALIDATOR] START index=7672
[VALIDATOR] START index=7919
[VALIDATOR] START index=8128
[VALIDATOR] START index=7439
[VALIDATOR] START index=8497
[VALIDATOR] START index=8954
[VALIDATOR] START index=7673
[VALIDATOR] START index=7920
[VALIDATOR] START index=8129
[VALIDATOR] START index=7440
[VALIDATOR] START index=8498
[VALIDATOR] START index=8955
[VALIDATOR] START index=7674
[VALIDATOR] START index=7921
[VALIDATOR] START index=8130
[VALIDATOR] START index=7441
[VALIDATOR] START index=8499
[VALIDATOR] START index=8956
[VALIDATOR] START index=7922
[VALIDATOR] START index=7675
[VALIDATOR] START index=8131
[VALIDATOR] START index=7442
[VALIDATOR] START index=8500
[VALIDATOR] START index=8957
[VALIDATOR] START index=7923
[VALIDATOR] START index=7676
[VALIDATOR] START index=8132
[VALIDATOR] START index=7443
[VALIDATOR] START index=8501
[VALIDATOR] START index=8958
[VALIDATOR] START index=7924
[VALIDATOR] START index=7677
[VALIDATOR] START index=8133

 82%|████████▎ | 33/40 [24:03<10:53, 93.41s/it]

[VALIDATOR] bug=topological_ordering candidates=240
[VALIDATOR] START index=9183
[VALIDATOR] START index=8959
[VALIDATOR] START index=7925
[VALIDATOR] START index=7678
[VALIDATOR] START index=8134
[VALIDATOR] START index=9184
[VALIDATOR] START index=8960
[VALIDATOR] START index=7926
[VALIDATOR] START index=7679
[VALIDATOR] START index=8135

 85%|████████▌ | 34/40 [24:09<06:43, 67.24s/it]

[VALIDATOR] bug=wrap candidates=286
[VALIDATOR] START index=9423
[VALIDATOR] START index=8961
[VALIDATOR] START index=7927
[VALIDATOR] START index=8502
[VALIDATOR] START index=7680
[VALIDATOR] START index=8136
[VALIDATOR] START index=9424
[VALIDATOR] START index=8962
[VALIDATOR] START index=7928
[VALIDATOR] START index=8503
[VALIDATOR] START index=7681
[VALIDATOR] START index=8137
[VALIDATOR] START index=8963
[VALIDATOR] START index=9425
[VALIDATOR] START index=8504
[VALIDATOR] START index=7929
[VALIDATOR] START index=7682
[VALIDATOR] START index=8138
[VALIDATOR] START index=8964
[VALIDATOR] START index=9426
[VALIDATOR] START index=7930
[VALIDATOR] START index=7683
[VALIDATOR] START index=8139
[VALIDATOR] START index=8965
[VALIDATOR] START index=9427
[VALIDATOR] START index=7684
[VALIDATOR] START index=7931
[VALIDATOR] START index=8140
[VALIDATOR] START index=8966
[VALIDATOR] START index=9428
[VALIDATOR] START index=7685
[VALIDATOR] START index=7932
[VALIDATOR] START index=8141
[VALIDATOR] START index=8505
[VALIDATOR] START index=8967
[VALIDATOR] START index=9429
[VALIDATOR] START index=7686
[VALIDATOR] START index=7933
[VALIDATOR] START index=8506
[VALIDATOR] START index=8968
[VALIDATOR] START index=8142
[VALIDATOR] START index=9430
[VALIDATOR] START index=7687
[VALIDATOR] START index=8143
[VALIDATOR] START index=8969
[VALIDATOR] START index=7934
[VALIDATOR] START index=9431
[VALIDATOR] START index=7688
[VALIDATOR] START index=7935
[VALIDATOR] START index=8144
[VALIDATOR] START index=8970
[VALIDATOR] START index=9432
[VALIDATOR] START index=7689
[VALIDATOR] START index=8145
[VALIDATOR] START index=8971
[VALIDATOR] START index=7936
[VALIDATOR] START index=8507
[VALIDATOR] START index=9433
[VALIDATOR] START index=7690
[VALIDATOR] START index=8146
[VALIDATOR] START index=8972
[VALIDATOR] START index=7937
[VALIDATOR] START index=8508
[VALIDATOR] START index=9434
[VALIDATOR] START index=7691
[VALIDATOR] START index=8973
[VALIDATOR] START index=8147
[VALIDATOR] START index=8509
[VALIDATOR] START index=7938
[VALIDATOR] START index=9435
[VALIDATOR] START index=7692
[VALIDATOR] START index=8974
[VALIDATOR] START index=8148
[VALIDATOR] START index=7939
[VALIDATOR] START index=9436
[VALIDATOR] START index=7693
[VALIDATOR] START index=8975
[VALIDATOR] START index=8149

 88%|████████▊ | 35/40 [24:51<04:58, 59.76s/it]

[VALIDATOR] START index=9437
[VALIDATOR] START index=7694
[VALIDATOR] START index=8976
[VALIDATOR] START index=8150
[VALIDATOR] START index=9438
[VALIDATOR] START index=7695
[VALIDATOR] START index=8977
[VALIDATOR] START index=8151
[VALIDATOR] START index=8510
[VALIDATOR] START index=9439
[VALIDATOR] START index=7696
[VALIDATOR] START index=8978
[VALIDATOR] START index=8152
[VALIDATOR] START index=9440
[VALIDATOR] START index=8153
[VALIDATOR] START index=8979
[VALIDATOR] START index=7697
[VALIDATOR] START index=9441
[VALIDATOR] START index=8154
[VALIDATOR] START index=8980
[VALIDATOR] START index=7698
[VALIDATOR] START index=8155
[VALIDATOR] START index=9442
[VALIDATOR] START index=8981
[VALIDATOR] START index=7699
[VALIDATOR] START index=8511
[VALIDATOR] START index=8156
[VALIDATOR] START index=8982
[VALIDATOR] START index=7700
[VALIDATOR] START index=8157
[VALIDATOR] START index=8983
[VALIDATOR] START index=7701
[VALIDATOR] START index=8158
[VALIDATOR] START index=8984
[VALIDATOR] START index=7702
[VALIDATOR] START index=8985
[VALIDATOR] START index=8159
[VALIDATOR] START index=7703
[VALIDATOR] START index=9443
[VALIDATOR] START index=8986
[VALIDATOR] START index=8512
[VALIDATOR] START index=8160
[VALIDATOR] START index=7704
[VALIDATOR] START index=9444
[VALIDATOR] START index=8987
[VALIDATOR] START index=8513
[VALIDATOR] START index=7705

 90%|█████████ | 36/40 [25:18<03:20, 50.01s/it]

[VALIDATOR] START index=8988
[VALIDATOR] START index=8514
[VALIDATOR] START index=7706
[VALIDATOR] START index=8989
[VALIDATOR] START index=8515
[VALIDATOR] START index=7707
[VALIDATOR] START index=8990
[VALIDATOR] START index=8516
[VALIDATOR] START index=7708
[VALIDATOR] START index=8991
[VALIDATOR] START index=8517
[VALIDATOR] START index=8161
[VALIDATOR] START index=7709
[VALIDATOR] START index=8992
[VALIDATOR] START index=8518
[VALIDATOR] START index=8162
[VALIDATOR] START index=7710
[VALIDATOR] START index=8993
[VALIDATOR] START index=8163

 92%|█████████▎| 37/40 [25:29<01:54, 38.33s/it]

[VALIDATOR] START index=8994
[VALIDATOR] START index=8164
[VALIDATOR] START index=8995
[VALIDATOR] START index=8165
[VALIDATOR] START index=8996
[VALIDATOR] START index=8166
[VALIDATOR] START index=8997
[VALIDATOR] START index=8167
[VALIDATOR] START index=8998
[VALIDATOR] START index=8519
[VALIDATOR] START index=8168
[VALIDATOR] START index=8520
[VALIDATOR] START index=8999
[VALIDATOR] START index=8169
[VALIDATOR] START index=9000
[VALIDATOR] START index=8170
[VALIDATOR] START index=9001
[VALIDATOR] START index=8171
[VALIDATOR] START index=9002
[VALIDATOR] START index=8172
[VALIDATOR] START index=9003
[VALIDATOR] START index=8173
[VALIDATOR] START index=9004
[VALIDATOR] START index=8174
[VALIDATOR] START index=9005
[VALIDATOR] START index=8521
[VALIDATOR] START index=9006
[VALIDATOR] START index=8175
[VALIDATOR] START index=9007
[VALIDATOR] START index=8176
[VALIDATOR] START index=9008
[VALIDATOR] START index=8177
[VALIDATOR] START index=9009
[VALIDATOR] START index=8178
[VALIDATOR] START index=9010
[VALIDATOR] START index=8179
[VALIDATOR] START index=9011
[VALIDATOR] START index=8180
[VALIDATOR] START index=9012
[VALIDATOR] START index=8522
[VALIDATOR] START index=8181
[VALIDATOR] START index=9013
[VALIDATOR] START index=8182
[VALIDATOR] START index=9014
[VALIDATOR] START index=8183
[VALIDATOR] START index=9015
[VALIDATOR] START index=8184
[VALIDATOR] START index=9016
[VALIDATOR] START index=8185
[VALIDATOR] START index=9017
[VALIDATOR] START index=8186
[VALIDATOR] START index=9018
[VALIDATOR] START index=8187
[VALIDATOR] START index=8523
[VALIDATOR] START index=8188
[VALIDATOR] START index=9019
[VALIDATOR] START index=8524
[VALIDATOR] START index=8189
[VALIDATOR] START index=9020
[VALIDATOR] START index=8190
[VALIDATOR] START index=9021
[VALIDATOR] START index=8191
[VALIDATOR] START index=9022
[VALIDATOR] START index=8192
[VALIDATOR] START index=9023
[VALIDATOR] START index=8193
[VALIDATOR] START index=9024
[VALIDATOR] START index=8194
[VALIDATOR] START index=8525
[VALIDATOR] START index=9025
[VALIDATOR] START index=8195
[VALIDATOR] START index=8526
[VALIDATOR] START index=9026
[VALIDATOR] START index=8196
[VALIDATOR] START index=9027
[VALIDATOR] START index=8197
[VALIDATOR] START index=9028
[VALIDATOR] START index=8198
[VALIDATOR] START index=9029
[VALIDATOR] START index=8199
[VALIDATOR] START index=9030
[VALIDATOR] START index=8200
[VALIDATOR] START index=9031
[VALIDATOR] START index=8527
[VALIDATOR] START index=8201
[VALIDATOR] START index=9032
[VALIDATOR] START index=8202
[VALIDATOR] START index=9033
[VALIDATOR] START index=8203
[VALIDATOR] START index=9034
[VALIDATOR] START index=8204
[VALIDATOR] START index=9035
[VALIDATOR] START index=8205
[VALIDATOR] START index=9036
[VALIDATOR] START index=8206
[VALIDATOR] START index=8528
[VALIDATOR] START index=9037
[VALIDATOR] START index=8207
[VALIDATOR] START index=8529
[VALIDATOR] START index=9038
[VALIDATOR] START index=8208
[VALIDATOR] START index=8530
[VALIDATOR] START index=9039
[VALIDATOR] START index=8209
[VALIDATOR] START index=9040
[VALIDATOR] START index=8531
[VALIDATOR] START index=9041
[VALIDATOR] START index=8210
[VALIDATOR] START index=9042
[VALIDATOR] START index=8211
[VALIDATOR] START index=9043
[VALIDATOR] START index=8212
[VALIDATOR] START index=9044
[VALIDATOR] START index=8213
[VALIDATOR] START index=9045
[VALIDATOR] START index=8214
[VALIDATOR] START index=9046
[VALIDATOR] START index=8532
[VALIDATOR] START index=8215
[VALIDATOR] START index=8533
[VALIDATOR] START index=9047
[VALIDATOR] START index=8216
[VALIDATOR] START index=9048
[VALIDATOR] START index=8217
[VALIDATOR] START index=9049
[VALIDATOR] START index=8218
[VALIDATOR] START index=9050
[VALIDATOR] START index=8219
[VALIDATOR] START index=9051
[VALIDATOR] START index=8220
[VALIDATOR] START index=9052
[VALIDATOR] START index=8534
[VALIDATOR] START index=8221
[VALIDATOR] START index=9053
[VALIDATOR] START index=8222
[VALIDATOR] START index=9054
[VALIDATOR] START index=8223
[VALIDATOR] START index=9055
[VALIDATOR] START index=8224
[VALIDATOR] START index=9056
[VALIDATOR] START index=8225
[VALIDATOR] START index=9057
[VALIDATOR] START index=8226
[VALIDATOR] START index=9058
[VALIDATOR] START index=8535
[VALIDATOR] START index=8227
[VALIDATOR] START index=8536
[VALIDATOR] START index=9059
[VALIDATOR] START index=8228
[VALIDATOR] START index=8537
[VALIDATOR] START index=9060
[VALIDATOR] START index=8229
[VALIDATOR] START index=8538
[VALIDATOR] START index=9061
[VALIDATOR] START index=8230
[VALIDATOR] START index=8539
[VALIDATOR] START index=9062
[VALIDATOR] START index=8231
[VALIDATOR] START index=9063
[VALIDATOR] START index=8232
[VALIDATOR] START index=9064
[VALIDATOR] START index=8233
[VALIDATOR] START index=9065

 95%|█████████▌| 38/40 [27:30<02:06, 63.08s/it]

[VALIDATOR] START index=9066
[VALIDATOR] START index=9067
[VALIDATOR] START index=9068
[VALIDATOR] START index=9069
[VALIDATOR] START index=8540
[VALIDATOR] START index=9070
[VALIDATOR] START index=8541
[VALIDATOR] START index=9071
[VALIDATOR] START index=9072
[VALIDATOR] START index=9073
[VALIDATOR] START index=9074
[VALIDATOR] START index=9075
[VALIDATOR] START index=9076
[VALIDATOR] START index=9077
[VALIDATOR] START index=9078
[VALIDATOR] START index=8542
[VALIDATOR] START index=9079
[VALIDATOR] START index=9080
[VALIDATOR] START index=9081
[VALIDATOR] START index=9082
[VALIDATOR] START index=9083
[VALIDATOR] START index=9084
[VALIDATOR] START index=9085
[VALIDATOR] START index=9086
[VALIDATOR] START index=8543
[VALIDATOR] START index=9087
[VALIDATOR] START index=8544
[VALIDATOR] START index=9088
[VALIDATOR] START index=9089
[VALIDATOR] START index=9090
[VALIDATOR] START index=9091
[VALIDATOR] START index=9092
[VALIDATOR] START index=9093
[VALIDATOR] START index=9094
[VALIDATOR] START index=9095
[VALIDATOR] START index=8545
[VALIDATOR] START index=9096
[VALIDATOR] START index=8546
[VALIDATOR] START index=9097
[VALIDATOR] START index=8547
[VALIDATOR] START index=9098
[VALIDATOR] START index=9099
[VALIDATOR] START index=9100
[VALIDATOR] START index=9101
[VALIDATOR] START index=9102
[VALIDATOR] START index=9103
[VALIDATOR] START index=9104
[VALIDATOR] START index=9105
[VALIDATOR] START index=9106
[VALIDATOR] START index=8548
[VALIDATOR] START index=9107
[VALIDATOR] START index=9108
[VALIDATOR] START index=9109
[VALIDATOR] START index=9110
[VALIDATOR] START index=9111
[VALIDATOR] START index=9112
[VALIDATOR] START index=9113
[VALIDATOR] START index=9114
[VALIDATOR] START index=8549
[VALIDATOR] START index=9115
[VALIDATOR] START index=8550
[VALIDATOR] START index=9116
[VALIDATOR] START index=9117
[VALIDATOR] START index=9118
[VALIDATOR] START index=9119
[VALIDATOR] START index=9120
[VALIDATOR] START index=9121
[VALIDATOR] START index=9122
[VALIDATOR] START index=9123
[VALIDATOR] START index=8551
[VALIDATOR] START index=9124
[VALIDATOR] START index=9125
[VALIDATOR] START index=9126
[VALIDATOR] START index=9127
[VALIDATOR] START index=9128
[VALIDATOR] START index=9129
[VALIDATOR] START index=9130
[VALIDATOR] START index=9131
[VALIDATOR] START index=9132
[VALIDATOR] START index=8552
[VALIDATOR] START index=9133
[VALIDATOR] START index=8553
[VALIDATOR] START index=9134
[VALIDATOR] START index=9135
[VALIDATOR] START index=9136
[VALIDATOR] START index=9137
[VALIDATOR] START index=9138
[VALIDATOR] START index=9139
[VALIDATOR] START index=9140
[VALIDATOR] START index=9141
[VALIDATOR] START index=8554
[VALIDATOR] START index=9142
[VALIDATOR] START index=9143
[VALIDATOR] START index=9144
[VALIDATOR] START index=9145
[VALIDATOR] START index=9146
[VALIDATOR] START index=9147
[VALIDATOR] START index=9148
[VALIDATOR] START index=9149
[VALIDATOR] START index=8555
[VALIDATOR] START index=9150
[VALIDATOR] START index=8556
[VALIDATOR] START index=9151
[VALIDATOR] START index=8557
[VALIDATOR] START index=9152
[VALIDATOR] START index=8558
[VALIDATOR] START index=9153
[VALIDATOR] START index=9154
[VALIDATOR] START index=9155
[VALIDATOR] START index=9156
[VALIDATOR] START index=9157
[VALIDATOR] START index=9158
[VALIDATOR] START index=9159
[VALIDATOR] START index=9160
[VALIDATOR] START index=8559
[VALIDATOR] START index=9161
[VALIDATOR] START index=9162
[VALIDATOR] START index=9163
[VALIDATOR] START index=9164
[VALIDATOR] START index=9165
[VALIDATOR] START index=9166
[VALIDATOR] START index=9167
[VALIDATOR] START index=9168
[VALIDATOR] START index=9169
[VALIDATOR] START index=8560
[VALIDATOR] START index=9170
[VALIDATOR] START index=8561
[VALIDATOR] START index=9171
[VALIDATOR] START index=9172
[VALIDATOR] START index=9173
[VALIDATOR] START index=9174
[VALIDATOR] START index=9175
[VALIDATOR] START index=9176
[VALIDATOR] START index=9177
[VALIDATOR] START index=9178
[VALIDATOR] START index=8562
[VALIDATOR] START index=9179
[VALIDATOR] START index=9180
[VALIDATOR] START index=9181
[VALIDATOR] START index=9182

 98%|█████████▊| 39/40 [29:53<01:26, 86.91s/it]

[VALIDATOR] START index=8563
[VALIDATOR] START index=8564
[VALIDATOR] START index=8565
[VALIDATOR] START index=8566
[VALIDATOR] START index=8567
[VALIDATOR] START index=8568
[VALIDATOR] START index=8569
[VALIDATOR] START index=8570
[VALIDATOR] START index=8571
[VALIDATOR] START index=8572
[VALIDATOR] START index=8573
[VALIDATOR] START index=8574
[VALIDATOR] START index=8575
[VALIDATOR] START index=8576
[VALIDATOR] START index=8577
[VALIDATOR] START index=8578
[VALIDATOR] START index=8579
[VALIDATOR] START index=8580
[VALIDATOR] START index=8581
[VALIDATOR] START index=8582
[VALIDATOR] START index=8583
[VALIDATOR] START index=8584
[VALIDATOR] START index=8585
[VALIDATOR] START index=8586
[VALIDATOR] START index=8587
[VALIDATOR] START index=8588
[VALIDATOR] START index=8589
[VALIDATOR] START index=8590
[VALIDATOR] START index=8591
[VALIDATOR] START index=8592
[VALIDATOR] START index=8593
[VALIDATOR] START index=8594
[VALIDATOR] START index=8595
[VALIDATOR] START index=8596
[VALIDATOR] START index=8597
[VALIDATOR] START index=8598
[VALIDATOR] START index=8599
[VALIDATOR] START index=8600
[VALIDATOR] START index=8601
[VALIDATOR] START index=8602
[VALIDATOR] START index=8603
[VALIDATOR] START index=8604
[VALIDATOR] START index=8605
[VALIDATOR] START index=8606
[VALIDATOR] START index=8607
[VALIDATOR] START index=8608
[VALIDATOR] START index=8609
[VALIDATOR] START index=8610
[VALIDATOR] START index=8611
[VALIDATOR] START index=8612
[VALIDATOR] START index=8613
[VALIDATOR] START index=8614
[VALIDATOR] START index=8615
[VALIDATOR] START index=8616
[VALIDATOR] START index=8617
[VALIDATOR] START index=8618
[VALIDATOR] START index=8619
[VALIDATOR] START index=8620
[VALIDATOR] START index=8621
[VALIDATOR] START index=8622
[VALIDATOR] START index=8623
[VALIDATOR] START index=8624
[VALIDATOR] START index=8625
[VALIDATOR] START index=8626
[VALIDATOR] START index=8627
[VALIDATOR] START index=8628
[VALIDATOR] START index=8629
[VALIDATOR] START index=8630
[VALIDATOR] START index=8631
[VALIDATOR] START index=8632
[VALIDATOR] START index=8633
[VALIDATOR] START index=8634
[VALIDATOR] START index=8635
[VALIDATOR] START index=8636
[VALIDATOR] START index=8637
[VALIDATOR] START index=8638
[VALIDATOR] START index=8639
[VALIDATOR] START index=8640
[VALIDATOR] START index=8641
[VALIDATOR] START index=8642
[VALIDATOR] START index=8643
[VALIDATOR] START index=8644
[VALIDATOR] START index=8645
[VALIDATOR] START index=8646
[VALIDATOR] START index=8647
[VALIDATOR] START index=8648
[VALIDATOR] START index=8649
[VALIDATOR] START index=8650
[VALIDATOR] START index=8651
[VALIDATOR] START index=8652
[VALIDATOR] START index=8653
[VALIDATOR] START index=8654
[VALIDATOR] START index=8655
[VALIDATOR] START index=8656
[VALIDATOR] START index=8657
[VALIDATOR] START index=8658
[VALIDATOR] START index=8659
[VALIDATOR] START index=8660
[VALIDATOR] START index=8661
[VALIDATOR] START index=8662
[VALIDATOR] START index=8663
[VALIDATOR] START index=8664
[VALIDATOR] START index=8665
[VALIDATOR] START index=8666
[VALIDATOR] START index=8667
[VALIDATOR] START index=8668
[VALIDATOR] START index=8669
[VALIDATOR] START index=8670
[VALIDATOR] START index=8671
[VALIDATOR] START index=8672
[VALIDATOR] START index=8673
[VALIDATOR] START index=8674
[VALIDATOR] START index=8675
[VALIDATOR] START index=8676
[VALIDATOR] START index=8677
[VALIDATOR] START index=8678
[VALIDATOR] START index=8679
[VALIDATOR] START index=8680
[VALIDATOR] START index=8681
[VALIDATOR] START index=8682
[VALIDATOR] START index=8683
[VALIDATOR] START index=8684
[VALIDATOR] START index=8685
[VALIDATOR] START index=8686
[VALIDATOR] START index=8687
[VALIDATOR] START index=8688
[VALIDATOR] START index=8689
[VALIDATOR] START index=8690
[VALIDATOR] START index=8691
[VALIDATOR] START index=8692
[VALIDATOR] START index=8693
[VALIDATOR] START index=8694
[VALIDATOR] START index=8695
[VALIDATOR] START index=8696
[VALIDATOR] START index=8697
[VALIDATOR] START index=8698
[VALIDATOR] START index=8699
[VALIDATOR] START index=8700
[VALIDATOR] START index=8701
[VALIDATOR] START index=8702
[VALIDATOR] START index=8703
[VALIDATOR] START index=8704
[VALIDATOR] START index=8705
[VALIDATOR] START index=8706
[VALIDATOR] START index=8707
[VALIDATOR] START index=8708
[VALIDATOR] START index=8709
[VALIDATOR] START index=8710
[VALIDATOR] START index=8711
[VALIDATOR] START index=8712
[VALIDATOR] START index=8713
[VALIDATOR] START index=8714
[VALIDATOR] START index=8715
[VALIDATOR] START index=8716
[VALIDATOR] START index=8717
[VALIDATOR] START index=8718
[VALIDATOR] START index=8719
[VALIDATOR] START index=8720
[VALIDATOR] START index=8721

100%|██████████| 40/40 [44:21<00:00, 66.54s/it]

===== PLAUSIBLE =====
bugid
bitcount                       True
breadth_first_search           True
bucketsort                    False
depth_first_search             True
detect_cycle                   True
find_first_in_sorted           True
find_in_sorted                 True
flatten                        True
gcd                           False
get_factors                    True
hanoi                          True
is_valid_parenthesization      True
kheapsort                      True
knapsack                       True
kth                           False
lcs_length                     True
levenshtein                    True
lis                            True
longest_common_subsequence     True
max_sublist_sum               False
mergesort                      True
minimum_spanning_tree          True
next_palindrome                True
next_permutation               True
pascal                         True
possible_change                True
powerset                      False
quicksort                      True
reverse_linked_list            True
rpn_eval                       True
shortest_path_length          False
shortest_path_lengths         False
shortest_paths                False
shunting_yard                 False
sieve                          True
sqrt                          False
subsequences                   True
to_base                       False
topological_ordering           True
wrap                           True
Name: plausible, dtype: bool
plausible
True     29
False    11
Name: count, dtype: int64

===== CORRECT =====
bugid
bitcount                       True
breadth_first_search           True
bucketsort                    False
depth_first_search             True
detect_cycle                   True
find_first_in_sorted           True
find_in_sorted                 True
flatten                        True
gcd                           False
get_factors                    True
hanoi                          True
is_valid_parenthesization      True
kheapsort                      True
knapsack                       True
kth                           False
lcs_length                     True
levenshtein                    True
lis                           False
longest_common_subsequence     True
max_sublist_sum               False
mergesort                      True
minimum_spanning_tree          True
next_palindrome               False
next_permutation               True
pascal                         True
possible_change                True
powerset                      False
quicksort                      True
reverse_linked_list            True
rpn_eval                       True
shortest_path_length          False
shortest_path_lengths         False
shortest_paths                False
shunting_yard                 False
sieve                          True
sqrt                          False
subsequences                   True
to_base                       False
topological_ordering           True
wrap                           True
Name: correct, dtype: bool
correct
True     27
False    13
Name: count, dtype: int64

no_rag: validation complete
Output: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/outputs-multimend-no_rag/plausible_candidates_100.jsonl
Columns verified: plausible, correct

======================================================================
VALIDATING: fixed_rag
======================================================================
timeout per test : 10 seconds
sleep candidates : 0.05 seconds
workers          : 6
======================================================================
[VALIDATOR CONFIG] test_timeout=10.0s, candidate_sleep=0.05s, workers=6
Metadata programs: 40
Programs to validate: 40

  0%|          | 0/40 [00:00<?, ?it/s]

[VALIDATOR] bug=bucketsort candidates=241
[VALIDATOR] START index=464
[VALIDATOR] bug=depth_first_search candidates=282
[VALIDATOR] START index=705
[VALIDATOR] bug=find_first_in_sorted candidates=240
[VALIDATOR] START index=1242
[VALIDATOR] bug=detect_cycle candidates=255
[VALIDATOR] START index=987
[VALIDATOR] bug=breadth_first_search candidates=239
[VALIDATOR] START index=225
[VALIDATOR] bug=bitcount candidates=225
[VALIDATOR] START index=0
[VALIDATOR] START index=465
[VALIDATOR] START index=1243
[VALIDATOR] START index=706
[VALIDATOR] START index=226
[VALIDATOR] START index=988

  2%|▎         | 1/40 [00:06<04:18,  6.62s/it]

[VALIDATOR] bug=find_in_sorted candidates=239
[VALIDATOR] START index=1482
[VALIDATOR] START index=989
[VALIDATOR] START index=227
[VALIDATOR] START index=466
[VALIDATOR] START index=707
[VALIDATOR] START index=990
[VALIDATOR] START index=1483
[VALIDATOR] START index=467

  5%|▌         | 2/40 [00:09<02:57,  4.67s/it]

[VALIDATOR] bug=flatten candidates=218
[VALIDATOR] START index=1721
[VALIDATOR] START index=1
[VALIDATOR] START index=708
[VALIDATOR] START index=991
[VALIDATOR] START index=1484
[VALIDATOR] START index=468
[VALIDATOR] START index=1722
[VALIDATOR] START index=2
[VALIDATOR] START index=709
[VALIDATOR] START index=992
[VALIDATOR] START index=1723
[VALIDATOR] START index=469
[VALIDATOR] START index=1485
[VALIDATOR] START index=3
[VALIDATOR] START index=710
[VALIDATOR] START index=993
[VALIDATOR] START index=1724
[VALIDATOR] START index=470
[VALIDATOR] START index=1486
[VALIDATOR] START index=471
[VALIDATOR] START index=1725
[VALIDATOR] START index=994
[VALIDATOR] START index=711
[VALIDATOR] START index=1487
[VALIDATOR] START index=472
[VALIDATOR] START index=1726
[VALIDATOR] START index=1488

  8%|▊         | 3/40 [00:24<05:38,  9.15s/it]

[VALIDATOR] bug=gcd candidates=241
[VALIDATOR] START index=1939
[VALIDATOR] START index=712
[VALIDATOR] START index=473
[VALIDATOR] START index=4
[VALIDATOR] START index=1489
[VALIDATOR] START index=1727
[VALIDATOR] START index=713
[VALIDATOR] START index=1940
[VALIDATOR] START index=474
[VALIDATOR] START index=1490
[VALIDATOR] START index=1728
[VALIDATOR] START index=714
[VALIDATOR] START index=1941
[VALIDATOR] START index=5
[VALIDATOR] START index=475
[VALIDATOR] START index=1729
[VALIDATOR] START index=1491
[VALIDATOR] START index=6
[VALIDATOR] START index=1942
[VALIDATOR] START index=715
[VALIDATOR] START index=476
[VALIDATOR] START index=1730

 10%|█         | 4/40 [00:35<06:02, 10.08s/it]

[VALIDATOR] bug=get_factors candidates=248
[VALIDATOR] START index=2180
[VALIDATOR] START index=1943
[VALIDATOR] START index=716
[VALIDATOR] START index=477
[VALIDATOR] START index=1731
[VALIDATOR] START index=1944
[VALIDATOR] START index=2181
[VALIDATOR] START index=717
[VALIDATOR] START index=478
[VALIDATOR] START index=1732
[VALIDATOR] START index=2182
[VALIDATOR] START index=1945
[VALIDATOR] START index=718
[VALIDATOR] START index=7
[VALIDATOR] START index=479
[VALIDATOR] START index=1733

 12%|█▎        | 5/40 [00:44<05:34,  9.56s/it]

[VALIDATOR] bug=hanoi candidates=219
[VALIDATOR] START index=2428
[VALIDATOR] START index=1946
[VALIDATOR] START index=719
[VALIDATOR] START index=480
[VALIDATOR] START index=1734
[VALIDATOR] START index=1947
[VALIDATOR] START index=2429
[VALIDATOR] START index=720
[VALIDATOR] START index=481
[VALIDATOR] START index=1735
[VALIDATOR] START index=2430
[VALIDATOR] START index=482
[VALIDATOR] START index=721
[VALIDATOR] START index=1948
[VALIDATOR] START index=1736
[VALIDATOR] START index=8
[VALIDATOR] START index=2431
[VALIDATOR] START index=483
[VALIDATOR] START index=722
[VALIDATOR] START index=1949
[VALIDATOR] START index=1737
[VALIDATOR] START index=2432
[VALIDATOR] START index=484
[VALIDATOR] START index=1950
[VALIDATOR] START index=723
[VALIDATOR] START index=1738
[VALIDATOR] START index=2433
[VALIDATOR] START index=485
[VALIDATOR] START index=1951
[VALIDATOR] START index=724
[VALIDATOR] START index=1739
[VALIDATOR] START index=2434
[VALIDATOR] START index=486
[VALIDATOR] START index=1952
[VALIDATOR] START index=9
[VALIDATOR] START index=725
[VALIDATOR] START index=1740
[VALIDATOR] START index=2435
[VALIDATOR] START index=487
[VALIDATOR] START index=1953
[VALIDATOR] START index=726

 15%|█▌        | 6/40 [01:06<07:47, 13.75s/it]

[VALIDATOR] bug=is_valid_parenthesization candidates=242
[VALIDATOR] START index=2647
[VALIDATOR] START index=1741
[VALIDATOR] START index=2436
[VALIDATOR] START index=488
[VALIDATOR] START index=2648
[VALIDATOR] START index=1954
[VALIDATOR] START index=1742
[VALIDATOR] START index=727
[VALIDATOR] START index=2437
[VALIDATOR] START index=489
[VALIDATOR] START index=2649
[VALIDATOR] START index=1743
[VALIDATOR] START index=1955
[VALIDATOR] START index=728
[VALIDATOR] START index=2438
[VALIDATOR] START index=490
[VALIDATOR] START index=2650
[VALIDATOR] START index=1744
[VALIDATOR] START index=729
[VALIDATOR] START index=1956
[VALIDATOR] START index=2439
[VALIDATOR] START index=491
[VALIDATOR] START index=2651
[VALIDATOR] START index=1745
[VALIDATOR] START index=730
[VALIDATOR] START index=1957
[VALIDATOR] START index=2440
[VALIDATOR] START index=492
[VALIDATOR] START index=1746
[VALIDATOR] START index=2652
[VALIDATOR] START index=1958
[VALIDATOR] START index=2441
[VALIDATOR] START index=731
[VALIDATOR] START index=493
[VALIDATOR] START index=2653
[VALIDATOR] START index=1747
[VALIDATOR] START index=1959
[VALIDATOR] START index=2442
[VALIDATOR] START index=732
[VALIDATOR] START index=494
[VALIDATOR] START index=1748
[VALIDATOR] START index=2654
[VALIDATOR] START index=1960
[VALIDATOR] START index=2443
[VALIDATOR] START index=495
[VALIDATOR] START index=733
[VALIDATOR] START index=1749
[VALIDATOR] START index=2655
[VALIDATOR] START index=1961
[VALIDATOR] START index=2444
[VALIDATOR] START index=496
[VALIDATOR] START index=734
[VALIDATOR] START index=1750
[VALIDATOR] START index=2656
[VALIDATOR] START index=1962
[VALIDATOR] START index=2445
[VALIDATOR] START index=497
[VALIDATOR] START index=735
[VALIDATOR] START index=1751
[VALIDATOR] START index=2657
[VALIDATOR] START index=1963
[VALIDATOR] START index=2446
[VALIDATOR] START index=498
[VALIDATOR] START index=1752
[VALIDATOR] START index=736
[VALIDATOR] START index=2658
[VALIDATOR] START index=1964
[VALIDATOR] START index=2447
[VALIDATOR] START index=499
[VALIDATOR] START index=1753
[VALIDATOR] START index=737
[VALIDATOR] START index=2659
[VALIDATOR] START index=1965
[VALIDATOR] START index=2448
[VALIDATOR] START index=500
[VALIDATOR] START index=1754
[VALIDATOR] START index=738
[VALIDATOR] START index=2660
[VALIDATOR] START index=1966
[VALIDATOR] START index=501
[VALIDATOR] START index=2449
[VALIDATOR] START index=1755
[VALIDATOR] START index=739
[VALIDATOR] START index=2661
[VALIDATOR] START index=502
[VALIDATOR] START index=1967
[VALIDATOR] START index=2450
[VALIDATOR] START index=1756
[VALIDATOR] START index=740
[VALIDATOR] START index=503
[VALIDATOR] START index=2662
[VALIDATOR] START index=1968
[VALIDATOR] START index=2451
[VALIDATOR] START index=1757
[VALIDATOR] START index=504
[VALIDATOR] START index=2663
[VALIDATOR] START index=741
[VALIDATOR] START index=1969
[VALIDATOR] START index=2452
[VALIDATOR] START index=1758
[VALIDATOR] START index=505
[VALIDATOR] START index=2664
[VALIDATOR] START index=1970
[VALIDATOR] START index=742
[VALIDATOR] START index=2453
[VALIDATOR] START index=1759
[VALIDATOR] START index=506
[VALIDATOR] START index=2665
[VALIDATOR] START index=1971
[VALIDATOR] START index=2454
[VALIDATOR] START index=743
[VALIDATOR] START index=1760
[VALIDATOR] START index=1972
[VALIDATOR] START index=507
[VALIDATOR] START index=2455
[VALIDATOR] START index=2666
[VALIDATOR] START index=1761
[VALIDATOR] START index=744
[VALIDATOR] START index=508
[VALIDATOR] START index=2456
[VALIDATOR] START index=2667
[VALIDATOR] START index=1973
[VALIDATOR] START index=1762
[VALIDATOR] START index=745
[VALIDATOR] START index=509
[VALIDATOR] START index=2457
[VALIDATOR] START index=1763
[VALIDATOR] START index=2668
[VALIDATOR] START index=1974
[VALIDATOR] START index=510
[VALIDATOR] START index=2669
[VALIDATOR] START index=2458
[VALIDATOR] START index=746
[VALIDATOR] START index=1764
[VALIDATOR] START index=1975
[VALIDATOR] START index=511
[VALIDATOR] START index=2670
[VALIDATOR] START index=747
[VALIDATOR] START index=1765
[VALIDATOR] START index=2459
[VALIDATOR] START index=1976
[VALIDATOR] START index=2671
[VALIDATOR] START index=512
[VALIDATOR] START index=1766
[VALIDATOR] START index=748
[VALIDATOR] START index=2460
[VALIDATOR] START index=1977
[VALIDATOR] START index=513
[VALIDATOR] START index=2672
[VALIDATOR] START index=1767
[VALIDATOR] START index=2461
[VALIDATOR] START index=749
[VALIDATOR] START index=514
[VALIDATOR] START index=1978
[VALIDATOR] START index=2673
[VALIDATOR] START index=1768
[VALIDATOR] START index=2462
[VALIDATOR] START index=750
[VALIDATOR] START index=515
[VALIDATOR] START index=1979
[VALIDATOR] START index=1769
[VALIDATOR] START index=2674
[VALIDATOR] START index=2463
[VALIDATOR] START index=751
[VALIDATOR] START index=516
[VALIDATOR] START index=1980
[VALIDATOR] START index=1770
[VALIDATOR] START index=2675
[VALIDATOR] START index=2464
[VALIDATOR] START index=517
[VALIDATOR] START index=752

 18%|█▊        | 7/40 [02:32<20:30, 37.30s/it]

[VALIDATOR] START index=1981
[VALIDATOR] bug=kheapsort candidates=235
[VALIDATOR] START index=2889
[VALIDATOR] START index=1771
[VALIDATOR] START index=2465
[VALIDATOR] START index=518
[VALIDATOR] START index=753
[VALIDATOR] START index=1982
[VALIDATOR] START index=2890
[VALIDATOR] START index=2466
[VALIDATOR] START index=1772
[VALIDATOR] START index=519
[VALIDATOR] START index=754
[VALIDATOR] START index=1983
[VALIDATOR] START index=2891
[VALIDATOR] START index=1773
[VALIDATOR] START index=2467
[VALIDATOR] START index=520
[VALIDATOR] START index=755
[VALIDATOR] START index=1984
[VALIDATOR] START index=2892
[VALIDATOR] START index=1774
[VALIDATOR] START index=2468
[VALIDATOR] START index=521
[VALIDATOR] START index=756
[VALIDATOR] START index=1985
[VALIDATOR] START index=2893
[VALIDATOR] START index=1775
[VALIDATOR] START index=2469
[VALIDATOR] START index=757
[VALIDATOR] START index=522
[VALIDATOR] START index=2894
[VALIDATOR] START index=1986
[VALIDATOR] START index=1776
[VALIDATOR] START index=2470
[VALIDATOR] START index=758
[VALIDATOR] START index=2895
[VALIDATOR] START index=523
[VALIDATOR] START index=1987
[VALIDATOR] START index=1777
[VALIDATOR] START index=2471
[VALIDATOR] START index=2896
[VALIDATOR] START index=524
[VALIDATOR] START index=1778
[VALIDATOR] START index=1988
[VALIDATOR] START index=759
[VALIDATOR] START index=2472
[VALIDATOR] START index=2897
[VALIDATOR] START index=525
[VALIDATOR] START index=1989
[VALIDATOR] START index=1779
[VALIDATOR] START index=760
[VALIDATOR] START index=2473
[VALIDATOR] START index=2898
[VALIDATOR] START index=1780
[VALIDATOR] START index=526
[VALIDATOR] START index=1990
[VALIDATOR] START index=2474
[VALIDATOR] START index=761
[VALIDATOR] START index=2899
[VALIDATOR] START index=527
[VALIDATOR] START index=1991
[VALIDATOR] START index=1781
[VALIDATOR] START index=2475
[VALIDATOR] START index=762
[VALIDATOR] START index=2900
[VALIDATOR] START index=528
[VALIDATOR] START index=1782
[VALIDATOR] START index=1992
[VALIDATOR] START index=2476
[VALIDATOR] START index=763
[VALIDATOR] START index=2901
[VALIDATOR] START index=529
[VALIDATOR] START index=1993
[VALIDATOR] START index=1783
[VALIDATOR] START index=2477
[VALIDATOR] START index=764
[VALIDATOR] START index=2902
[VALIDATOR] START index=530
[VALIDATOR] START index=1784
[VALIDATOR] START index=1994
[VALIDATOR] START index=2478
[VALIDATOR] START index=2903
[VALIDATOR] START index=765
[VALIDATOR] START index=531
[VALIDATOR] START index=1785
[VALIDATOR] START index=1995
[VALIDATOR] START index=2479
[VALIDATOR] START index=2904
[VALIDATOR] START index=766
[VALIDATOR] START index=532
[VALIDATOR] START index=1996
[VALIDATOR] START index=1786
[VALIDATOR] START index=2480
[VALIDATOR] START index=2905
[VALIDATOR] START index=533
[VALIDATOR] START index=1997
[VALIDATOR] START index=767
[VALIDATOR] START index=1787
[VALIDATOR] START index=2481
[VALIDATOR] START index=2906
[VALIDATOR] START index=768
[VALIDATOR] START index=1998
[VALIDATOR] START index=534
[VALIDATOR] START index=2482
[VALIDATOR] START index=1788
[VALIDATOR] START index=2907
[VALIDATOR] START index=769
[VALIDATOR] START index=1999
[VALIDATOR] START index=2483
[VALIDATOR] START index=535
[VALIDATOR] START index=1789
[VALIDATOR] START index=2908
[VALIDATOR] START index=770
[VALIDATOR] START index=2000
[VALIDATOR] START index=1790
[VALIDATOR] START index=2484
[VALIDATOR] START index=536
[VALIDATOR] START index=2909
[VALIDATOR] START index=1791
[VALIDATOR] START index=2485
[VALIDATOR] START index=537
[VALIDATOR] START index=771
[VALIDATOR] START index=2001
[VALIDATOR] START index=2910
[VALIDATOR] START index=1792
[VALIDATOR] START index=538
[VALIDATOR] START index=772
[VALIDATOR] START index=2486
[VALIDATOR] START index=2002
[VALIDATOR] START index=2911

 20%|██        | 8/40 [03:35<24:21, 45.68s/it]

[VALIDATOR] START index=539
[VALIDATOR] START index=773
[VALIDATOR] bug=knapsack candidates=218
[VALIDATOR] START index=3124

 22%|██▎       | 9/40 [03:36<16:20, 31.62s/it]

[VALIDATOR] START index=2003
[VALIDATOR] bug=kth candidates=208
[VALIDATOR] START index=3342
[VALIDATOR] START index=2912
[VALIDATOR] START index=540
[VALIDATOR] START index=2004
[VALIDATOR] START index=3125
[VALIDATOR] START index=2913
[VALIDATOR] START index=774
[VALIDATOR] START index=3343
[VALIDATOR] START index=541
[VALIDATOR] START index=2005
[VALIDATOR] START index=2914

 25%|██▌       | 10/40 [03:42<11:49, 23.66s/it]

[VALIDATOR] bug=lcs_length candidates=215
[VALIDATOR] START index=3550
[VALIDATOR] START index=3344
[VALIDATOR] START index=775
[VALIDATOR] START index=542
[VALIDATOR] START index=2006
[VALIDATOR] START index=2915
[VALIDATOR] START index=3345
[VALIDATOR] START index=3551
[VALIDATOR] START index=776
[VALIDATOR] START index=543
[VALIDATOR] START index=2007
[VALIDATOR] bug=levenshtein candidates=291
[VALIDATOR] START index=3765

 28%|██▊       | 11/40 [03:48<08:46, 18.15s/it]

[VALIDATOR] START index=3346
[VALIDATOR] START index=3552
[VALIDATOR] START index=544
[VALIDATOR] START index=2008
[VALIDATOR] START index=777
[VALIDATOR] START index=3347
[VALIDATOR] START index=3766
[VALIDATOR] START index=3553
[VALIDATOR] START index=545
[VALIDATOR] START index=2009
[VALIDATOR] START index=3348
[VALIDATOR] START index=778
[VALIDATOR] START index=3767
[VALIDATOR] START index=3554
[VALIDATOR] START index=546
[VALIDATOR] START index=2010
[VALIDATOR] START index=3349
[VALIDATOR] START index=779
[VALIDATOR] START index=3768
[VALIDATOR] START index=3555
[VALIDATOR] START index=547
[VALIDATOR] START index=2011
[VALIDATOR] START index=3350
[VALIDATOR] START index=780
[VALIDATOR] START index=3769
[VALIDATOR] START index=3556
[VALIDATOR] START index=548
[VALIDATOR] START index=2012
[VALIDATOR] START index=3770
[VALIDATOR] START index=3351
[VALIDATOR] START index=781
[VALIDATOR] START index=3557
[VALIDATOR] START index=549
[VALIDATOR] START index=2013
[VALIDATOR] START index=3352
[VALIDATOR] START index=3771
[VALIDATOR] START index=3558
[VALIDATOR] START index=782
[VALIDATOR] START index=2014
[VALIDATOR] START index=550
[VALIDATOR] START index=3353
[VALIDATOR] START index=3559
[VALIDATOR] START index=3772
[VALIDATOR] START index=783
[VALIDATOR] START index=551
[VALIDATOR] START index=2015
[VALIDATOR] START index=3560
[VALIDATOR] START index=3354
[VALIDATOR] START index=3773
[VALIDATOR] START index=784
[VALIDATOR] START index=2016
[VALIDATOR] START index=552
[VALIDATOR] START index=3355

 30%|███       | 12/40 [04:15<09:44, 20.89s/it]

[VALIDATOR] bug=lis candidates=246
[VALIDATOR] START index=4056
[VALIDATOR] START index=785
[VALIDATOR] START index=2017
[VALIDATOR] START index=553
[VALIDATOR] START index=3356
[VALIDATOR] START index=4057
[VALIDATOR] START index=786
[VALIDATOR] START index=2018
[VALIDATOR] START index=554
[VALIDATOR] START index=3357
[VALIDATOR] START index=4058

 32%|███▎      | 13/40 [04:21<07:22, 16.38s/it]

[VALIDATOR] bug=longest_common_subsequence candidates=236
[VALIDATOR] START index=4302
[VALIDATOR] START index=787
[VALIDATOR] START index=555
[VALIDATOR] START index=3358
[VALIDATOR] START index=2019
[VALIDATOR] START index=4059
[VALIDATOR] START index=4303
[VALIDATOR] START index=788
[VALIDATOR] START index=2020
[VALIDATOR] START index=556
[VALIDATOR] START index=3359
[VALIDATOR] START index=4060

 35%|███▌      | 14/40 [04:28<05:51, 13.53s/it]

[VALIDATOR] bug=max_sublist_sum candidates=220
[VALIDATOR] START index=4538
[VALIDATOR] START index=789
[VALIDATOR] START index=4061
[VALIDATOR] START index=3360
[VALIDATOR] START index=2021
[VALIDATOR] START index=557
[VALIDATOR] START index=4539
[VALIDATOR] START index=3361
[VALIDATOR] START index=4062
[VALIDATOR] START index=558
[VALIDATOR] START index=790
[VALIDATOR] START index=2022
[VALIDATOR] START index=4540
[VALIDATOR] START index=3362
[VALIDATOR] START index=559
[VALIDATOR] START index=4063
[VALIDATOR] START index=791
[VALIDATOR] START index=4541
[VALIDATOR] START index=2023
[VALIDATOR] START index=4064
[VALIDATOR] START index=3363
[VALIDATOR] START index=560
[VALIDATOR] START index=792
[VALIDATOR] START index=4542
[VALIDATOR] START index=2024
[VALIDATOR] START index=561
[VALIDATOR] START index=3364
[VALIDATOR] START index=4065
[VALIDATOR] START index=4543
[VALIDATOR] START index=2025
[VALIDATOR] START index=793
[VALIDATOR] START index=3365
[VALIDATOR] START index=562
[VALIDATOR] START index=4066
[VALIDATOR] START index=4544
[VALIDATOR] START index=2026
[VALIDATOR] START index=3366
[VALIDATOR] START index=563
[VALIDATOR] START index=794
[VALIDATOR] START index=4067
[VALIDATOR] START index=4545
[VALIDATOR] START index=2027
[VALIDATOR] START index=564
[VALIDATOR] bug=mergesort candidates=254
[VALIDATOR] START index=4758

 38%|███▊      | 15/40 [04:49<06:39, 15.98s/it]

[VALIDATOR] START index=3367
[VALIDATOR] START index=4068
[VALIDATOR] START index=4546
[VALIDATOR] START index=2028
[VALIDATOR] START index=565
[VALIDATOR] START index=3368
[VALIDATOR] START index=4759
[VALIDATOR] START index=4069
[VALIDATOR] START index=4547
[VALIDATOR] START index=2029
[VALIDATOR] START index=566
[VALIDATOR] START index=3369

 40%|████      | 16/40 [04:55<05:11, 13.00s/it]

[VALIDATOR] bug=minimum_spanning_tree candidates=235
[VALIDATOR] START index=5012
[VALIDATOR] START index=4548
[VALIDATOR] START index=4760
[VALIDATOR] START index=2030
[VALIDATOR] START index=567
[VALIDATOR] START index=3370
[VALIDATOR] START index=5013
[VALIDATOR] START index=4549
[VALIDATOR] START index=4761
[VALIDATOR] START index=2031
[VALIDATOR] START index=568
[VALIDATOR] START index=3371
[VALIDATOR] START index=5014
[VALIDATOR] START index=4550
[VALIDATOR] START index=4762
[VALIDATOR] START index=2032
[VALIDATOR] START index=569
[VALIDATOR] START index=3372
[VALIDATOR] START index=5015
[VALIDATOR] START index=4551
[VALIDATOR] START index=2033
[VALIDATOR] START index=570
[VALIDATOR] START index=3373
[VALIDATOR] START index=4763
[VALIDATOR] START index=5016
[VALIDATOR] START index=4552
[VALIDATOR] START index=571
[VALIDATOR] START index=3374
[VALIDATOR] START index=2034
[VALIDATOR] START index=5017
[VALIDATOR] START index=4553
[VALIDATOR] START index=4764
[VALIDATOR] START index=3375
[VALIDATOR] START index=572
[VALIDATOR] START index=2035
[VALIDATOR] START index=5018
[VALIDATOR] START index=4554
[VALIDATOR] START index=4765
[VALIDATOR] START index=3376
[VALIDATOR] START index=573
[VALIDATOR] START index=2036
[VALIDATOR] START index=5019
[VALIDATOR] START index=4555
[VALIDATOR] START index=4766
[VALIDATOR] START index=2037
[VALIDATOR] START index=3377
[VALIDATOR] START index=574

 42%|████▎     | 17/40 [05:18<06:08, 16.00s/it]

[VALIDATOR] bug=next_palindrome candidates=254
[VALIDATOR] START index=5247
[VALIDATOR] START index=4556
[VALIDATOR] START index=4767
[VALIDATOR] START index=575
[VALIDATOR] START index=2038
[VALIDATOR] START index=3378
[VALIDATOR] START index=5248
[VALIDATOR] START index=4557
[VALIDATOR] START index=4768
[VALIDATOR] START index=576
[VALIDATOR] START index=2039
[VALIDATOR] START index=3379
[VALIDATOR] START index=5249
[VALIDATOR] START index=4558

 45%|████▌     | 18/40 [05:26<04:53, 13.35s/it]

[VALIDATOR] bug=next_permutation candidates=257
[VALIDATOR] START index=5501
[VALIDATOR] START index=577
[VALIDATOR] START index=2040
[VALIDATOR] START index=3380

 48%|████▊     | 19/40 [05:27<03:27,  9.88s/it]

[VALIDATOR] bug=pascal candidates=196
[VALIDATOR] START index=5758
[VALIDATOR] START index=4559
[VALIDATOR] START index=5502
[VALIDATOR] START index=578
[VALIDATOR] START index=2041
[VALIDATOR] START index=3381
[VALIDATOR] START index=5759
[VALIDATOR] START index=4560
[VALIDATOR] START index=5503
[VALIDATOR] START index=579
[VALIDATOR] START index=2042
[VALIDATOR] START index=3382
[VALIDATOR] START index=5760
[VALIDATOR] START index=4561
[VALIDATOR] START index=5504
[VALIDATOR] START index=580
[VALIDATOR] START index=3383
[VALIDATOR] START index=2043
[VALIDATOR] START index=5761
[VALIDATOR] START index=4562
[VALIDATOR] START index=5505
[VALIDATOR] START index=581
[VALIDATOR] START index=3384
[VALIDATOR] START index=2044
[VALIDATOR] START index=5762
[VALIDATOR] START index=4563

 50%|█████     | 20/40 [05:40<03:36, 10.83s/it]

[VALIDATOR] bug=possible_change candidates=170
[VALIDATOR] START index=5954
[VALIDATOR] START index=3385
[VALIDATOR] START index=582
[VALIDATOR] START index=2045
[VALIDATOR] START index=5763
[VALIDATOR] START index=4564
[VALIDATOR] START index=2046
[VALIDATOR] START index=3386
[VALIDATOR] START index=583
[VALIDATOR] START index=5955
[VALIDATOR] START index=5764
[VALIDATOR] START index=4565
[VALIDATOR] START index=3387
[VALIDATOR] START index=2047
[VALIDATOR] START index=584
[VALIDATOR] START index=4566
[VALIDATOR] START index=5956
[VALIDATOR] START index=5765
[VALIDATOR] START index=2048
[VALIDATOR] START index=3388
[VALIDATOR] START index=585
[VALIDATOR] START index=4567
[VALIDATOR] START index=5766
[VALIDATOR] START index=5957
[VALIDATOR] START index=2049
[VALIDATOR] START index=3389
[VALIDATOR] START index=586
[VALIDATOR] bug=powerset candidates=277
[VALIDATOR] START index=6124

 52%|█████▎    | 21/40 [05:54<03:39, 11.53s/it]

[VALIDATOR] START index=4568
[VALIDATOR] START index=5958
[VALIDATOR] START index=3390
[VALIDATOR] START index=2050
[VALIDATOR] START index=587
[VALIDATOR] START index=6125
[VALIDATOR] START index=4569
[VALIDATOR] START index=5959
[VALIDATOR] START index=2051
[VALIDATOR] START index=3391
[VALIDATOR] START index=588
[VALIDATOR] START index=4570
[VALIDATOR] START index=6126
[VALIDATOR] START index=5960
[VALIDATOR] START index=2052
[VALIDATOR] START index=3392
[VALIDATOR] START index=589
[VALIDATOR] START index=4571
[VALIDATOR] START index=6127
[VALIDATOR] START index=5961
[VALIDATOR] START index=2053
[VALIDATOR] START index=3393
[VALIDATOR] START index=590
[VALIDATOR] START index=4572
[VALIDATOR] START index=6128
[VALIDATOR] START index=5962
[VALIDATOR] START index=2054
[VALIDATOR] START index=3394
[VALIDATOR] START index=591
[VALIDATOR] START index=4573
[VALIDATOR] START index=6129
[VALIDATOR] START index=5963
[VALIDATOR] START index=2055
[VALIDATOR] START index=592
[VALIDATOR] START index=3395
[VALIDATOR] START index=4574
[VALIDATOR] START index=6130
[VALIDATOR] START index=2056
[VALIDATOR] START index=593
[VALIDATOR] START index=5964
[VALIDATOR] START index=3396
[VALIDATOR] START index=6131
[VALIDATOR] START index=4575
[VALIDATOR] START index=2057
[VALIDATOR] START index=594
[VALIDATOR] START index=3397
[VALIDATOR] START index=6132
[VALIDATOR] START index=5965
[VALIDATOR] START index=4576
[VALIDATOR] START index=2058
[VALIDATOR] START index=595
[VALIDATOR] START index=3398
[VALIDATOR] START index=6133
[VALIDATOR] START index=5966
[VALIDATOR] START index=4577
[VALIDATOR] START index=596
[VALIDATOR] START index=2059
[VALIDATOR] START index=3399
[VALIDATOR] START index=5967
[VALIDATOR] START index=4578
[VALIDATOR] START index=6134
[VALIDATOR] START index=597
[VALIDATOR] START index=2060
[VALIDATOR] START index=3400
[VALIDATOR] START index=6135
[VALIDATOR] START index=4579
[VALIDATOR] START index=5968
[VALIDATOR] START index=598
[VALIDATOR] START index=2061
[VALIDATOR] START index=3401
[VALIDATOR] START index=4580
[VALIDATOR] START index=5969
[VALIDATOR] START index=6136
[VALIDATOR] START index=2062
[VALIDATOR] START index=599
[VALIDATOR] START index=3402
[VALIDATOR] START index=4581
[VALIDATOR] START index=5970
[VALIDATOR] START index=6137
[VALIDATOR] START index=2063
[VALIDATOR] START index=3403
[VALIDATOR] START index=600
[VALIDATOR] START index=4582
[VALIDATOR] START index=6138
[VALIDATOR] START index=5971
[VALIDATOR] START index=2064
[VALIDATOR] START index=601
[VALIDATOR] START index=3404
[VALIDATOR] START index=4583
[VALIDATOR] START index=5972
[VALIDATOR] START index=6139
[VALIDATOR] START index=2065
[VALIDATOR] START index=3405
[VALIDATOR] START index=602
[VALIDATOR] START index=4584
[VALIDATOR] START index=5973
[VALIDATOR] START index=6140
[VALIDATOR] START index=2066
[VALIDATOR] START index=603
[VALIDATOR] START index=3406
[VALIDATOR] START index=4585
[VALIDATOR] START index=2067
[VALIDATOR] START index=6141
[VALIDATOR] START index=5974
[VALIDATOR] START index=604
[VALIDATOR] START index=3407
[VALIDATOR] START index=4586
[VALIDATOR] START index=2068
[VALIDATOR] START index=6142
[VALIDATOR] START index=5975
[VALIDATOR] START index=605
[VALIDATOR] START index=3408
[VALIDATOR] START index=4587
[VALIDATOR] START index=2069
[VALIDATOR] START index=6143
[VALIDATOR] START index=5976
[VALIDATOR] START index=3409
[VALIDATOR] START index=606
[VALIDATOR] START index=4588
[VALIDATOR] START index=2070
[VALIDATOR] START index=5977
[VALIDATOR] START index=6144
[VALIDATOR] START index=607
[VALIDATOR] START index=3410
[VALIDATOR] START index=4589
[VALIDATOR] START index=2071
[VALIDATOR] START index=6145
[VALIDATOR] START index=3411
[VALIDATOR] START index=5978
[VALIDATOR] START index=608
[VALIDATOR] START index=2072
[VALIDATOR] START index=4590
[VALIDATOR] START index=6146
[VALIDATOR] START index=3412
[VALIDATOR] START index=609
[VALIDATOR] START index=5979
[VALIDATOR] START index=4591
[VALIDATOR] START index=2073
[VALIDATOR] START index=6147
[VALIDATOR] START index=3413
[VALIDATOR] START index=610
[VALIDATOR] START index=5980
[VALIDATOR] START index=2074
[VALIDATOR] START index=4592
[VALIDATOR] START index=6148
[VALIDATOR] START index=611
[VALIDATOR] START index=3414
[VALIDATOR] START index=4593
[VALIDATOR] START index=2075
[VALIDATOR] START index=5981
[VALIDATOR] START index=612
[VALIDATOR] START index=6149
[VALIDATOR] START index=3415
[VALIDATOR] START index=2076
[VALIDATOR] START index=4594
[VALIDATOR] START index=5982
[VALIDATOR] START index=613
[VALIDATOR] START index=6150
[VALIDATOR] START index=3416
[VALIDATOR] START index=2077
[VALIDATOR] START index=4595
[VALIDATOR] START index=5983
[VALIDATOR] START index=614
[VALIDATOR] START index=6151
[VALIDATOR] START index=3417
[VALIDATOR] START index=2078
[VALIDATOR] START index=4596
[VALIDATOR] START index=5984
[VALIDATOR] START index=6152
[VALIDATOR] START index=615
[VALIDATOR] START index=3418
[VALIDATOR] START index=2079
[VALIDATOR] START index=4597
[VALIDATOR] START index=5985
[VALIDATOR] START index=6153
[VALIDATOR] START index=616
[VALIDATOR] START index=3419
[VALIDATOR] START index=2080
[VALIDATOR] START index=5986
[VALIDATOR] START index=6154
[VALIDATOR] START index=4598
[VALIDATOR] START index=617
[VALIDATOR] START index=3420
[VALIDATOR] START index=2081
[VALIDATOR] START index=618
[VALIDATOR] START index=5987
[VALIDATOR] START index=6155
[VALIDATOR] START index=4599
[VALIDATOR] START index=3421
[VALIDATOR] START index=2082
[VALIDATOR] START index=619
[VALIDATOR] START index=6156
[VALIDATOR] START index=4600
[VALIDATOR] START index=5988
[VALIDATOR] START index=3422
[VALIDATOR] START index=2083
[VALIDATOR] START index=620
[VALIDATOR] START index=6157
[VALIDATOR] START index=4601
[VALIDATOR] START index=3423
[VALIDATOR] START index=5989
[VALIDATOR] START index=621
[VALIDATOR] START index=2084
[VALIDATOR] START index=6158
[VALIDATOR] START index=4602
[VALIDATOR] START index=3424

 55%|█████▌    | 22/40 [07:36<11:38, 38.78s/it]

[VALIDATOR] bug=quicksort candidates=259
[VALIDATOR] START index=6401
[VALIDATOR] START index=622
[VALIDATOR] START index=4603
[VALIDATOR] START index=6159
[VALIDATOR] START index=2085
[VALIDATOR] START index=3425
[VALIDATOR] START index=6402
[VALIDATOR] START index=623
[VALIDATOR] START index=4604
[VALIDATOR] START index=6160
[VALIDATOR] START index=2086
[VALIDATOR] START index=3426
[VALIDATOR] START index=6403
[VALIDATOR] START index=4605
[VALIDATOR] START index=624
[VALIDATOR] START index=2087
[VALIDATOR] START index=6161
[VALIDATOR] START index=3427
[VALIDATOR] START index=6404
[VALIDATOR] START index=4606
[VALIDATOR] START index=625
[VALIDATOR] START index=2088
[VALIDATOR] START index=3428
[VALIDATOR] START index=6162
[VALIDATOR] START index=6405
[VALIDATOR] START index=626
[VALIDATOR] START index=4607
[VALIDATOR] START index=2089
[VALIDATOR] START index=3429
[VALIDATOR] START index=6163
[VALIDATOR] START index=6406
[VALIDATOR] START index=4608
[VALIDATOR] START index=627
[VALIDATOR] START index=2090
[VALIDATOR] START index=3430
[VALIDATOR] START index=6164
[VALIDATOR] START index=6407
[VALIDATOR] START index=4609
[VALIDATOR] START index=628
[VALIDATOR] START index=2091
[VALIDATOR] START index=3431
[VALIDATOR] START index=6165
[VALIDATOR] START index=6408
[VALIDATOR] START index=4610
[VALIDATOR] START index=629
[VALIDATOR] START index=3432
[VALIDATOR] START index=2092
[VALIDATOR] START index=6166
[VALIDATOR] START index=6409
[VALIDATOR] START index=4611
[VALIDATOR] START index=630
[VALIDATOR] START index=2093
[VALIDATOR] START index=3433
[VALIDATOR] START index=6167
[VALIDATOR] START index=6410
[VALIDATOR] START index=4612
[VALIDATOR] START index=631
[VALIDATOR] START index=3434
[VALIDATOR] START index=2094
[VALIDATOR] START index=6168
[VALIDATOR] START index=6411
[VALIDATOR] START index=4613
[VALIDATOR] START index=632
[VALIDATOR] START index=3435
[VALIDATOR] START index=2095
[VALIDATOR] START index=6169
[VALIDATOR] START index=6412
[VALIDATOR] START index=4614
[VALIDATOR] START index=633
[VALIDATOR] START index=3436
[VALIDATOR] START index=2096
[VALIDATOR] START index=6170
[VALIDATOR] START index=4615
[VALIDATOR] START index=6413
[VALIDATOR] START index=634
[VALIDATOR] START index=2097
[VALIDATOR] START index=3437
[VALIDATOR] START index=6171
[VALIDATOR] START index=4616

 57%|█████▊    | 23/40 [08:14<10:54, 38.49s/it]

[VALIDATOR] bug=reverse_linked_list candidates=275
[VALIDATOR] START index=6660
[VALIDATOR] START index=635
[VALIDATOR] START index=2098
[VALIDATOR] START index=3438
[VALIDATOR] START index=6172
[VALIDATOR] START index=4617
[VALIDATOR] START index=6661
[VALIDATOR] START index=636
[VALIDATOR] START index=2099
[VALIDATOR] START index=3439
[VALIDATOR] START index=6173
[VALIDATOR] START index=4618
[VALIDATOR] START index=6662
[VALIDATOR] START index=637
[VALIDATOR] START index=2100
[VALIDATOR] START index=3440
[VALIDATOR] START index=4619
[VALIDATOR] START index=6174
[VALIDATOR] START index=6663
[VALIDATOR] START index=638
[VALIDATOR] START index=3441
[VALIDATOR] START index=2101
[VALIDATOR] START index=4620
[VALIDATOR] START index=6175
[VALIDATOR] START index=6664
[VALIDATOR] START index=639
[VALIDATOR] START index=4621
[VALIDATOR] START index=3442
[VALIDATOR] START index=2102
[VALIDATOR] START index=6176
[VALIDATOR] START index=640
[VALIDATOR] START index=6665
[VALIDATOR] START index=3443
[VALIDATOR] START index=4622
[VALIDATOR] START index=2103
[VALIDATOR] START index=6177
[VALIDATOR] START index=641
[VALIDATOR] START index=6666
[VALIDATOR] START index=3444
[VALIDATOR] START index=4623
[VALIDATOR] START index=2104
[VALIDATOR] START index=6178
[VALIDATOR] START index=642
[VALIDATOR] START index=6667
[VALIDATOR] START index=3445
[VALIDATOR] START index=4624
[VALIDATOR] START index=2105
[VALIDATOR] START index=6179
[VALIDATOR] START index=4625
[VALIDATOR] START index=6668
[VALIDATOR] START index=643
[VALIDATOR] START index=3446
[VALIDATOR] START index=6180
[VALIDATOR] START index=4626
[VALIDATOR] START index=644
[VALIDATOR] START index=6669
[VALIDATOR] START index=3447
[VALIDATOR] START index=6181
[VALIDATOR] START index=4627
[VALIDATOR] START index=3448
[VALIDATOR] START index=6670
[VALIDATOR] START index=645
[VALIDATOR] START index=6182
[VALIDATOR] START index=2106
[VALIDATOR] START index=4628
[VALIDATOR] START index=3449
[VALIDATOR] START index=6671
[VALIDATOR] START index=646
[VALIDATOR] START index=6183
[VALIDATOR] START index=4629
[VALIDATOR] START index=2107
[VALIDATOR] START index=3450
[VALIDATOR] START index=6672
[VALIDATOR] START index=6184
[VALIDATOR] START index=647
[VALIDATOR] START index=4630
[VALIDATOR] START index=2108
[VALIDATOR] START index=3451
[VALIDATOR] START index=6185
[VALIDATOR] START index=6673
[VALIDATOR] START index=648
[VALIDATOR] START index=4631
[VALIDATOR] START index=2109
[VALIDATOR] START index=3452
[VALIDATOR] START index=649
[VALIDATOR] START index=6186
[VALIDATOR] START index=6674
[VALIDATOR] START index=4632
[VALIDATOR] START index=2110
[VALIDATOR] START index=3453
[VALIDATOR] START index=650
[VALIDATOR] START index=6187
[VALIDATOR] START index=4633
[VALIDATOR] START index=6675
[VALIDATOR] START index=2111
[VALIDATOR] START index=3454
[VALIDATOR] START index=651
[VALIDATOR] START index=4634
[VALIDATOR] START index=6676
[VALIDATOR] START index=6188
[VALIDATOR] START index=2112
[VALIDATOR] START index=3455
[VALIDATOR] START index=652
[VALIDATOR] START index=4635
[VALIDATOR] START index=6189
[VALIDATOR] START index=6677
[VALIDATOR] START index=2113
[VALIDATOR] START index=3456
[VALIDATOR] START index=653
[VALIDATOR] START index=4636
[VALIDATOR] START index=6190
[VALIDATOR] START index=2114
[VALIDATOR] START index=6678
[VALIDATOR] START index=3457
[VALIDATOR] START index=654
[VALIDATOR] START index=4637
[VALIDATOR] START index=6191
[VALIDATOR] START index=6679
[VALIDATOR] START index=2115
[VALIDATOR] START index=3458
[VALIDATOR] START index=655
[VALIDATOR] START index=4638
[VALIDATOR] START index=6192
[VALIDATOR] START index=6680
[VALIDATOR] START index=2116
[VALIDATOR] START index=3459
[VALIDATOR] START index=656
[VALIDATOR] START index=4639
[VALIDATOR] START index=6193
[VALIDATOR] START index=3460
[VALIDATOR] START index=2117
[VALIDATOR] START index=657
[VALIDATOR] START index=6681
[VALIDATOR] START index=4640
[VALIDATOR] START index=6194
[VALIDATOR] START index=3461
[VALIDATOR] START index=658
[VALIDATOR] START index=2118
[VALIDATOR] START index=6682
[VALIDATOR] START index=4641
[VALIDATOR] START index=6195
[VALIDATOR] START index=2119
[VALIDATOR] START index=3462
[VALIDATOR] START index=659
[VALIDATOR] START index=6683
[VALIDATOR] START index=4642
[VALIDATOR] START index=6196
[VALIDATOR] START index=2120
[VALIDATOR] START index=3463
[VALIDATOR] START index=660
[VALIDATOR] START index=4643
[VALIDATOR] START index=6684
[VALIDATOR] START index=6197
[VALIDATOR] START index=2121
[VALIDATOR] START index=661
[VALIDATOR] START index=3464
[VALIDATOR] START index=6685
[VALIDATOR] START index=4644
[VALIDATOR] START index=6198
[VALIDATOR] START index=2122
[VALIDATOR] START index=662
[VALIDATOR] START index=3465
[VALIDATOR] START index=4645
[VALIDATOR] START index=6686
[VALIDATOR] START index=6199
[VALIDATOR] START index=3466
[VALIDATOR] START index=663
[VALIDATOR] START index=2123
[VALIDATOR] START index=4646
[VALIDATOR] START index=6687
[VALIDATOR] START index=6200
[VALIDATOR] START index=3467
[VALIDATOR] START index=664
[VALIDATOR] START index=2124
[VALIDATOR] START index=4647
[VALIDATOR] START index=6688
[VALIDATOR] START index=6201
[VALIDATOR] START index=3468
[VALIDATOR] START index=665
[VALIDATOR] START index=4648
[VALIDATOR] START index=2125
[VALIDATOR] START index=6689
[VALIDATOR] START index=6202
[VALIDATOR] START index=3469
[VALIDATOR] START index=666
[VALIDATOR] START index=4649
[VALIDATOR] START index=2126
[VALIDATOR] START index=6690
[VALIDATOR] START index=6203
[VALIDATOR] START index=667
[VALIDATOR] START index=3470
[VALIDATOR] START index=4650
[VALIDATOR] START index=2127
[VALIDATOR] START index=6691
[VALIDATOR] START index=3471
[VALIDATOR] START index=6204
[VALIDATOR] START index=2128
[VALIDATOR] START index=668
[VALIDATOR] START index=4651
[VALIDATOR] START index=6692
[VALIDATOR] START index=2129
[VALIDATOR] START index=3472
[VALIDATOR] START index=6205
[VALIDATOR] START index=669
[VALIDATOR] START index=4652
[VALIDATOR] START index=6693
[VALIDATOR] START index=3473
[VALIDATOR] START index=2130
[VALIDATOR] START index=670
[VALIDATOR] START index=6206
[VALIDATOR] START index=4653
[VALIDATOR] START index=6694
[VALIDATOR] START index=3474
[VALIDATOR] START index=6207
[VALIDATOR] START index=2131
[VALIDATOR] START index=671
[VALIDATOR] START index=4654
[VALIDATOR] START index=3475
[VALIDATOR] START index=2132
[VALIDATOR] START index=6695
[VALIDATOR] START index=6208
[VALIDATOR] START index=672
[VALIDATOR] START index=4655
[VALIDATOR] START index=3476
[VALIDATOR] START index=2133
[VALIDATOR] START index=6209
[VALIDATOR] START index=6696
[VALIDATOR] START index=4656
[VALIDATOR] START index=673
[VALIDATOR] START index=3477
[VALIDATOR] START index=2134
[VALIDATOR] START index=6210
[VALIDATOR] START index=6697
[VALIDATOR] START index=674
[VALIDATOR] START index=4657
[VALIDATOR] START index=3478
[VALIDATOR] START index=2135
[VALIDATOR] START index=6211
[VALIDATOR] START index=6698
[VALIDATOR] START index=675
[VALIDATOR] START index=4658
[VALIDATOR] START index=3479
[VALIDATOR] START index=2136
[VALIDATOR] START index=6212
[VALIDATOR] START index=6699
[VALIDATOR] START index=676
[VALIDATOR] START index=4659
[VALIDATOR] START index=3480
[VALIDATOR] START index=2137
[VALIDATOR] START index=677
[VALIDATOR] START index=4660
[VALIDATOR] START index=6700
[VALIDATOR] START index=6213
[VALIDATOR] START index=3481
[VALIDATOR] START index=2138
[VALIDATOR] START index=4661
[VALIDATOR] START index=6214
[VALIDATOR] START index=678
[VALIDATOR] START index=6701
[VALIDATOR] START index=3482
[VALIDATOR] START index=2139
[VALIDATOR] START index=4662
[VALIDATOR] START index=6215
[VALIDATOR] START index=679
[VALIDATOR] START index=6702
[VALIDATOR] START index=2140
[VALIDATOR] START index=3483
[VALIDATOR] START index=4663
[VALIDATOR] START index=6216
[VALIDATOR] START index=680
[VALIDATOR] START index=6703
[VALIDATOR] START index=2141
[VALIDATOR] START index=3484
[VALIDATOR] START index=4664
[VALIDATOR] START index=6217
[VALIDATOR] START index=681
[VALIDATOR] START index=2142
[VALIDATOR] START index=3485
[VALIDATOR] START index=6704
[VALIDATOR] START index=4665
[VALIDATOR] START index=6218
[VALIDATOR] START index=682
[VALIDATOR] START index=2143
[VALIDATOR] START index=6705
[VALIDATOR] START index=3486
[VALIDATOR] START index=4666
[VALIDATOR] START index=683
[VALIDATOR] START index=6219
[VALIDATOR] START index=3487
[VALIDATOR] START index=6706
[VALIDATOR] START index=2144
[VALIDATOR] START index=4667
[VALIDATOR] START index=6220
[VALIDATOR] START index=684
[VALIDATOR] START index=3488
[VALIDATOR] START index=6707
[VALIDATOR] START index=2145
[VALIDATOR] START index=4668
[VALIDATOR] START index=685
[VALIDATOR] START index=6221
[VALIDATOR] START index=3489
[VALIDATOR] START index=6708
[VALIDATOR] START index=2146
[VALIDATOR] START index=4669
[VALIDATOR] START index=6222
[VALIDATOR] START index=686
[VALIDATOR] START index=3490
[VALIDATOR] START index=2147
[VALIDATOR] START index=6709
[VALIDATOR] START index=4670
[VALIDATOR] START index=6223
[VALIDATOR] START index=687
[VALIDATOR] START index=3491
[VALIDATOR] START index=2148
[VALIDATOR] START index=4671
[VALIDATOR] START index=6710
[VALIDATOR] START index=6224
[VALIDATOR] START index=688
[VALIDATOR] START index=3492
[VALIDATOR] START index=2149
[VALIDATOR] START index=4672
[VALIDATOR] START index=6711
[VALIDATOR] START index=689
[VALIDATOR] START index=6225
[VALIDATOR] START index=3493
[VALIDATOR] START index=2150
[VALIDATOR] START index=6712
[VALIDATOR] START index=4673
[VALIDATOR] START index=690
[VALIDATOR] START index=6226
[VALIDATOR] START index=3494
[VALIDATOR] START index=6713
[VALIDATOR] START index=2151
[VALIDATOR] START index=4674
[VALIDATOR] START index=691
[VALIDATOR] START index=6227
[VALIDATOR] START index=3495
[VALIDATOR] START index=6714
[VALIDATOR] START index=2152
[VALIDATOR] START index=4675
[VALIDATOR] START index=692
[VALIDATOR] START index=3496
[VALIDATOR] START index=6228
[VALIDATOR] START index=6715
[VALIDATOR] START index=4676
[VALIDATOR] START index=2153
[VALIDATOR] START index=3497
[VALIDATOR] START index=693
[VALIDATOR] START index=6229
[VALIDATOR] START index=4677
[VALIDATOR] START index=6716
[VALIDATOR] START index=2154
[VALIDATOR] START index=3498
[VALIDATOR] START index=694
[VALIDATOR] START index=6230
[VALIDATOR] START index=6717
[VALIDATOR] START index=4678
[VALIDATOR] START index=2155
[VALIDATOR] START index=3499
[VALIDATOR] START index=695
[VALIDATOR] START index=6231
[VALIDATOR] START index=4679
[VALIDATOR] START index=6718
[VALIDATOR] START index=2156
[VALIDATOR] START index=3500
[VALIDATOR] START index=696
[VALIDATOR] START index=4680
[VALIDATOR] START index=6232
[VALIDATOR] START index=6719
[VALIDATOR] START index=2157
[VALIDATOR] START index=3501
[VALIDATOR] START index=697
[VALIDATOR] START index=4681
[VALIDATOR] START index=6720
[VALIDATOR] START index=6233
[VALIDATOR] START index=3502
[VALIDATOR] START index=2158
[VALIDATOR] START index=698
[VALIDATOR] START index=4682
[VALIDATOR] START index=6721
[VALIDATOR] START index=6234
[VALIDATOR] START index=3503
[VALIDATOR] START index=2159
[VALIDATOR] START index=699
[VALIDATOR] START index=4683
[VALIDATOR] START index=6722
[VALIDATOR] START index=6235
[VALIDATOR] START index=3504
[VALIDATOR] START index=2160
[VALIDATOR] START index=700
[VALIDATOR] START index=4684
[VALIDATOR] START index=6723
[VALIDATOR] START index=6236
[VALIDATOR] START index=3505
[VALIDATOR] START index=2161
[VALIDATOR] START index=701
[VALIDATOR] START index=4685
[VALIDATOR] START index=6724
[VALIDATOR] START index=3506
[VALIDATOR] START index=6237
[VALIDATOR] START index=2162
[VALIDATOR] START index=702
[VALIDATOR] START index=4686
[VALIDATOR] START index=3507
[VALIDATOR] START index=6238
[VALIDATOR] START index=6725
[VALIDATOR] START index=2163
[VALIDATOR] START index=703
[VALIDATOR] START index=4687
[VALIDATOR] START index=3508
[VALIDATOR] START index=2164
[VALIDATOR] START index=6726
[VALIDATOR] START index=6239
[VALIDATOR] START index=4688
[VALIDATOR] START index=704
[VALIDATOR] START index=3509
[VALIDATOR] START index=2165
[VALIDATOR] START index=6240
[VALIDATOR] START index=4689
[VALIDATOR] bug=rpn_eval candidates=213
[VALIDATOR] START index=6935

 60%|██████    | 24/40 [11:39<23:38, 88.64s/it]

[VALIDATOR] START index=6727
[VALIDATOR] START index=3510
[VALIDATOR] START index=6241
[VALIDATOR] START index=6728
[VALIDATOR] START index=2166
[VALIDATOR] START index=4690
[VALIDATOR] START index=6936
[VALIDATOR] START index=3511
[VALIDATOR] START index=6242
[VALIDATOR] START index=2167
[VALIDATOR] START index=6937
[VALIDATOR] START index=6729
[VALIDATOR] START index=4691
[VALIDATOR] START index=3512
[VALIDATOR] START index=6243
[VALIDATOR] START index=2168
[VALIDATOR] START index=4692
[VALIDATOR] START index=6730
[VALIDATOR] START index=6938
[VALIDATOR] START index=3513
[VALIDATOR] START index=6244
[VALIDATOR] START index=2169
[VALIDATOR] START index=4693
[VALIDATOR] START index=6731
[VALIDATOR] START index=6939
[VALIDATOR] START index=3514
[VALIDATOR] START index=6245
[VALIDATOR] START index=2170
[VALIDATOR] START index=4694
[VALIDATOR] START index=6940
[VALIDATOR] START index=6732
[VALIDATOR] START index=3515
[VALIDATOR] START index=2171
[VALIDATOR] START index=6246
[VALIDATOR] START index=6941
[VALIDATOR] START index=6733
[VALIDATOR] START index=4695
[VALIDATOR] START index=3516
[VALIDATOR] START index=2172
[VALIDATOR] START index=6942
[VALIDATOR] START index=6734
[VALIDATOR] START index=6247
[VALIDATOR] START index=4696
[VALIDATOR] START index=3517
[VALIDATOR] START index=2173
[VALIDATOR] START index=4697
[VALIDATOR] START index=6735
[VALIDATOR] START index=6943
[VALIDATOR] START index=6248
[VALIDATOR] START index=3518
[VALIDATOR] START index=2174
[VALIDATOR] START index=4698
[VALIDATOR] START index=6944
[VALIDATOR] START index=6736
[VALIDATOR] START index=6249
[VALIDATOR] START index=3519
[VALIDATOR] START index=2175
[VALIDATOR] START index=6945
[VALIDATOR] START index=6250
[VALIDATOR] START index=4699
[VALIDATOR] START index=6737
[VALIDATOR] START index=3520
[VALIDATOR] START index=2176
[VALIDATOR] START index=6946
[VALIDATOR] START index=6251
[VALIDATOR] START index=4700
[VALIDATOR] START index=6738
[VALIDATOR] START index=3521
[VALIDATOR] START index=2177
[VALIDATOR] START index=6947
[VALIDATOR] START index=4701
[VALIDATOR] START index=6252
[VALIDATOR] START index=6739
[VALIDATOR] START index=3522
[VALIDATOR] START index=2178
[VALIDATOR] START index=6948
[VALIDATOR] START index=4702
[VALIDATOR] START index=6253
[VALIDATOR] START index=3523
[VALIDATOR] START index=6740
[VALIDATOR] START index=2179
[VALIDATOR] START index=6949
[VALIDATOR] START index=4703
[VALIDATOR] START index=6254
[VALIDATOR] START index=6741
[VALIDATOR] START index=3524

 62%|██████▎   | 25/40 [12:22<18:42, 74.81s/it]

[VALIDATOR] bug=shortest_path_length candidates=247
[VALIDATOR] START index=7148
[VALIDATOR] START index=6950
[VALIDATOR] START index=4704
[VALIDATOR] START index=6255
[VALIDATOR] START index=6742
[VALIDATOR] START index=3525
[VALIDATOR] START index=7149
[VALIDATOR] START index=6951
[VALIDATOR] START index=4705
[VALIDATOR] START index=6256
[VALIDATOR] START index=6743
[VALIDATOR] START index=3526
[VALIDATOR] START index=7150
[VALIDATOR] START index=6952
[VALIDATOR] START index=4706
[VALIDATOR] START index=6257
[VALIDATOR] START index=3527
[VALIDATOR] START index=6744
[VALIDATOR] START index=7151
[VALIDATOR] START index=6953
[VALIDATOR] START index=4707
[VALIDATOR] START index=6258
[VALIDATOR] START index=3528
[VALIDATOR] START index=6745
[VALIDATOR] START index=7152
[VALIDATOR] START index=6954
[VALIDATOR] START index=4708
[VALIDATOR] START index=6259
[VALIDATOR] START index=3529
[VALIDATOR] START index=6746
[VALIDATOR] START index=7153
[VALIDATOR] START index=6955
[VALIDATOR] START index=4709
[VALIDATOR] START index=6260
[VALIDATOR] START index=3530
[VALIDATOR] START index=6747
[VALIDATOR] START index=7154
[VALIDATOR] START index=6956
[VALIDATOR] START index=4710
[VALIDATOR] START index=6261
[VALIDATOR] START index=3531
[VALIDATOR] START index=6748
[VALIDATOR] START index=7155
[VALIDATOR] START index=6957
[VALIDATOR] START index=4711
[VALIDATOR] START index=6262
[VALIDATOR] START index=3532
[VALIDATOR] START index=6749
[VALIDATOR] START index=7156
[VALIDATOR] START index=6958
[VALIDATOR] START index=4712
[VALIDATOR] START index=3533
[VALIDATOR] START index=6750
[VALIDATOR] START index=6263
[VALIDATOR] START index=6959
[VALIDATOR] START index=7157
[VALIDATOR] START index=4713
[VALIDATOR] START index=3534
[VALIDATOR] START index=6264
[VALIDATOR] START index=6751
[VALIDATOR] START index=7158
[VALIDATOR] START index=6960
[VALIDATOR] START index=4714
[VALIDATOR] START index=3535
[VALIDATOR] START index=6752
[VALIDATOR] START index=6265
[VALIDATOR] START index=7159
[VALIDATOR] START index=6961
[VALIDATOR] START index=4715
[VALIDATOR] START index=3536
[VALIDATOR] START index=6266
[VALIDATOR] START index=7160
[VALIDATOR] START index=6753
[VALIDATOR] START index=6962
[VALIDATOR] START index=4716
[VALIDATOR] START index=3537
[VALIDATOR] START index=6267
[VALIDATOR] START index=7161
[VALIDATOR] START index=6754
[VALIDATOR] START index=6963
[VALIDATOR] START index=4717
[VALIDATOR] START index=3538
[VALIDATOR] START index=6268
[VALIDATOR] START index=6755
[VALIDATOR] START index=6964
[VALIDATOR] START index=7162
[VALIDATOR] START index=4718
[VALIDATOR] START index=3539
[VALIDATOR] START index=6269
[VALIDATOR] START index=6965
[VALIDATOR] START index=6756
[VALIDATOR] START index=7163
[VALIDATOR] START index=4719
[VALIDATOR] START index=3540
[VALIDATOR] START index=6270
[VALIDATOR] START index=6966
[VALIDATOR] START index=6757
[VALIDATOR] START index=7164
[VALIDATOR] START index=4720
[VALIDATOR] START index=3541
[VALIDATOR] START index=6271
[VALIDATOR] START index=6967
[VALIDATOR] START index=6758
[VALIDATOR] START index=7165
[VALIDATOR] START index=4721
[VALIDATOR] START index=3542
[VALIDATOR] START index=6272
[VALIDATOR] START index=6968
[VALIDATOR] START index=6759
[VALIDATOR] START index=7166
[VALIDATOR] START index=4722
[VALIDATOR] START index=3543
[VALIDATOR] START index=6273
[VALIDATOR] START index=6969
[VALIDATOR] START index=6760
[VALIDATOR] START index=7167
[VALIDATOR] START index=4723
[VALIDATOR] START index=3544
[VALIDATOR] START index=6274
[VALIDATOR] START index=6970
[VALIDATOR] START index=7168
[VALIDATOR] START index=4724
[VALIDATOR] START index=6761
[VALIDATOR] START index=3545
[VALIDATOR] START index=6275
[VALIDATOR] START index=6971
[VALIDATOR] START index=7169
[VALIDATOR] START index=4725
[VALIDATOR] START index=6762
[VALIDATOR] START index=3546
[VALIDATOR] START index=6276
[VALIDATOR] START index=6972
[VALIDATOR] START index=7170
[VALIDATOR] START index=4726
[VALIDATOR] START index=6763
[VALIDATOR] START index=3547

 65%|██████▌   | 26/40 [13:28<16:52, 72.33s/it]

[VALIDATOR] bug=shortest_path_lengths candidates=271
[VALIDATOR] START index=7395
[VALIDATOR] START index=6277
[VALIDATOR] START index=6764
[VALIDATOR] START index=7171
[VALIDATOR] START index=4727
[VALIDATOR] START index=3548
[VALIDATOR] START index=7396
[VALIDATOR] START index=6765
[VALIDATOR] START index=6278
[VALIDATOR] START index=7172
[VALIDATOR] START index=3549
[VALIDATOR] START index=4728
[VALIDATOR] START index=7397
[VALIDATOR] START index=6279
[VALIDATOR] START index=6766

 68%|██████▊   | 27/40 [13:35<11:25, 52.71s/it]

[VALIDATOR] bug=shortest_paths candidates=223
[VALIDATOR] START index=7666
[VALIDATOR] START index=7173
[VALIDATOR] START index=4729
[VALIDATOR] START index=7398
[VALIDATOR] START index=6280
[VALIDATOR] START index=6767
[VALIDATOR] START index=7174
[VALIDATOR] START index=4730
[VALIDATOR] START index=7667
[VALIDATOR] START index=7399
[VALIDATOR] START index=6281
[VALIDATOR] START index=4731
[VALIDATOR] START index=7175
[VALIDATOR] START index=7668
[VALIDATOR] START index=6768
[VALIDATOR] START index=7400
[VALIDATOR] START index=6282
[VALIDATOR] START index=4732
[VALIDATOR] START index=6769
[VALIDATOR] START index=7176
[VALIDATOR] START index=7669
[VALIDATOR] START index=7401
[VALIDATOR] START index=6283
[VALIDATOR] START index=4733
[VALIDATOR] START index=7670
[VALIDATOR] START index=7177
[VALIDATOR] START index=6770
[VALIDATOR] START index=7402
[VALIDATOR] START index=6284
[VALIDATOR] START index=7178
[VALIDATOR] START index=4734
[VALIDATOR] START index=7671
[VALIDATOR] START index=6771
[VALIDATOR] START index=7403
[VALIDATOR] START index=6285
[VALIDATOR] START index=7179
[VALIDATOR] START index=4735
[VALIDATOR] START index=7672
[VALIDATOR] START index=6772
[VALIDATOR] START index=7404
[VALIDATOR] START index=6286
[VALIDATOR] START index=4736
[VALIDATOR] START index=7673
[VALIDATOR] START index=7180
[VALIDATOR] START index=6773
[VALIDATOR] START index=7405
[VALIDATOR] START index=6287
[VALIDATOR] START index=4737
[VALIDATOR] START index=7181
[VALIDATOR] START index=6774
[VALIDATOR] START index=7674
[VALIDATOR] START index=7406
[VALIDATOR] START index=6288
[VALIDATOR] START index=4738
[VALIDATOR] START index=7182
[VALIDATOR] START index=7675
[VALIDATOR] START index=6775
[VALIDATOR] START index=7407
[VALIDATOR] START index=6289
[VALIDATOR] START index=4739
[VALIDATOR] START index=7676
[VALIDATOR] START index=7183
[VALIDATOR] START index=6776
[VALIDATOR] START index=7408
[VALIDATOR] START index=6290
[VALIDATOR] START index=4740
[VALIDATOR] START index=7677
[VALIDATOR] START index=7184
[VALIDATOR] START index=6777
[VALIDATOR] START index=7409
[VALIDATOR] START index=6291
[VALIDATOR] START index=7678
[VALIDATOR] START index=4741
[VALIDATOR] START index=7185
[VALIDATOR] START index=7410
[VALIDATOR] START index=6778
[VALIDATOR] START index=6292
[VALIDATOR] START index=7679
[VALIDATOR] START index=7186
[VALIDATOR] START index=4742
[VALIDATOR] START index=7411
[VALIDATOR] START index=6779
[VALIDATOR] START index=6293
[VALIDATOR] START index=7680
[VALIDATOR] START index=7187
[VALIDATOR] START index=4743
[VALIDATOR] START index=7412
[VALIDATOR] START index=6780
[VALIDATOR] START index=7681
[VALIDATOR] START index=6294
[VALIDATOR] START index=4744
[VALIDATOR] START index=7413
[VALIDATOR] START index=7188
[VALIDATOR] START index=6781
[VALIDATOR] START index=7682
[VALIDATOR] START index=6295
[VALIDATOR] START index=4745
[VALIDATOR] START index=7414
[VALIDATOR] START index=7189
[VALIDATOR] START index=6782
[VALIDATOR] START index=4746
[VALIDATOR] START index=7683
[VALIDATOR] START index=6296
[VALIDATOR] START index=7415
[VALIDATOR] START index=7190
[VALIDATOR] START index=6783
[VALIDATOR] START index=7684
[VALIDATOR] START index=4747
[VALIDATOR] START index=6297
[VALIDATOR] START index=7191
[VALIDATOR] START index=7416
[VALIDATOR] START index=6784
[VALIDATOR] START index=4748
[VALIDATOR] START index=7685
[VALIDATOR] START index=7192
[VALIDATOR] START index=7417
[VALIDATOR] START index=6298
[VALIDATOR] START index=6785
[VALIDATOR] START index=4749
[VALIDATOR] START index=7193
[VALIDATOR] START index=7686
[VALIDATOR] START index=7418
[VALIDATOR] START index=6299
[VALIDATOR] START index=6786
[VALIDATOR] START index=4750
[VALIDATOR] START index=7194
[VALIDATOR] START index=7419
[VALIDATOR] START index=7687
[VALIDATOR] START index=6300
[VALIDATOR] START index=6787
[VALIDATOR] START index=7195
[VALIDATOR] START index=4751
[VALIDATOR] START index=7688
[VALIDATOR] START index=6301
[VALIDATOR] START index=7420
[VALIDATOR] START index=7689
[VALIDATOR] START index=4752
[VALIDATOR] START index=6302
[VALIDATOR] START index=7196
[VALIDATOR] START index=7421
[VALIDATOR] START index=4753
[VALIDATOR] START index=7690
[VALIDATOR] START index=7197
[VALIDATOR] START index=6303
[VALIDATOR] START index=7422
[VALIDATOR] START index=6788
[VALIDATOR] START index=7691
[VALIDATOR] START index=4754
[VALIDATOR] START index=6304
[VALIDATOR] START index=7198
[VALIDATOR] START index=7423
[VALIDATOR] START index=6789
[VALIDATOR] START index=7692
[VALIDATOR] START index=4755
[VALIDATOR] START index=6305
[VALIDATOR] START index=7199
[VALIDATOR] START index=7424
[VALIDATOR] START index=7693
[VALIDATOR] START index=6790
[VALIDATOR] START index=4756
[VALIDATOR] START index=7200
[VALIDATOR] START index=6306
[VALIDATOR] START index=7425
[VALIDATOR] START index=6791
[VALIDATOR] START index=7694
[VALIDATOR] START index=4757
[VALIDATOR] START index=6307
[VALIDATOR] START index=7201
[VALIDATOR] START index=7426
[VALIDATOR] START index=7695
[VALIDATOR] START index=6792

 70%|███████   | 28/40 [15:00<12:29, 62.42s/it]

[VALIDATOR] bug=shunting_yard candidates=294
[VALIDATOR] START index=7889
[VALIDATOR] START index=6308
[VALIDATOR] START index=7202
[VALIDATOR] START index=7427
[VALIDATOR] START index=6793
[VALIDATOR] START index=7696
[VALIDATOR] START index=6309
[VALIDATOR] START index=7890
[VALIDATOR] START index=7203
[VALIDATOR] START index=7428
[VALIDATOR] START index=7697
[VALIDATOR] START index=6794
[VALIDATOR] START index=7891
[VALIDATOR] START index=6310
[VALIDATOR] START index=7204
[VALIDATOR] START index=7429
[VALIDATOR] START index=7698
[VALIDATOR] START index=6795
[VALIDATOR] START index=7892
[VALIDATOR] START index=6311
[VALIDATOR] START index=7205
[VALIDATOR] START index=7430
[VALIDATOR] START index=7699
[VALIDATOR] START index=6796
[VALIDATOR] START index=7893
[VALIDATOR] START index=6312
[VALIDATOR] START index=7206
[VALIDATOR] START index=7431
[VALIDATOR] START index=7700
[VALIDATOR] START index=6797
[VALIDATOR] START index=6313
[VALIDATOR] START index=7894
[VALIDATOR] START index=7207
[VALIDATOR] START index=7432
[VALIDATOR] START index=7701
[VALIDATOR] START index=6798
[VALIDATOR] START index=6314
[VALIDATOR] START index=7208
[VALIDATOR] START index=7895
[VALIDATOR] START index=7433
[VALIDATOR] START index=7702
[VALIDATOR] START index=6315
[VALIDATOR] START index=6799
[VALIDATOR] START index=7209
[VALIDATOR] START index=7703
[VALIDATOR] START index=7896
[VALIDATOR] START index=7434
[VALIDATOR] START index=6800
[VALIDATOR] START index=6316
[VALIDATOR] START index=7210
[VALIDATOR] START index=7704
[VALIDATOR] START index=7435
[VALIDATOR] START index=7897
[VALIDATOR] START index=6317
[VALIDATOR] START index=7211
[VALIDATOR] START index=6801
[VALIDATOR] START index=7436
[VALIDATOR] START index=7705
[VALIDATOR] START index=7898
[VALIDATOR] START index=7212
[VALIDATOR] START index=6318
[VALIDATOR] START index=6802
[VALIDATOR] START index=7706
[VALIDATOR] START index=7899
[VALIDATOR] START index=7437
[VALIDATOR] START index=7213
[VALIDATOR] START index=6319
[VALIDATOR] START index=6803
[VALIDATOR] START index=7707
[VALIDATOR] START index=7900
[VALIDATOR] START index=7438
[VALIDATOR] START index=7214
[VALIDATOR] START index=6320
[VALIDATOR] START index=6804
[VALIDATOR] START index=7901
[VALIDATOR] START index=7708
[VALIDATOR] START index=7439
[VALIDATOR] START index=7215
[VALIDATOR] START index=6321
[VALIDATOR] START index=6805
[VALIDATOR] START index=7902
[VALIDATOR] START index=7709
[VALIDATOR] START index=7440
[VALIDATOR] START index=7216
[VALIDATOR] START index=6806
[VALIDATOR] START index=6322
[VALIDATOR] START index=7710
[VALIDATOR] START index=7903
[VALIDATOR] START index=7441
[VALIDATOR] START index=7217
[VALIDATOR] START index=6807
[VALIDATOR] START index=6323
[VALIDATOR] START index=7711
[VALIDATOR] START index=7442
[VALIDATOR] START index=7218
[VALIDATOR] START index=7904
[VALIDATOR] START index=6808
[VALIDATOR] START index=6324
[VALIDATOR] START index=7712
[VALIDATOR] START index=7443
[VALIDATOR] START index=7219
[VALIDATOR] START index=7905
[VALIDATOR] START index=6809
[VALIDATOR] START index=6325
[VALIDATOR] START index=7713
[VALIDATOR] START index=7444
[VALIDATOR] START index=7220
[VALIDATOR] START index=7906
[VALIDATOR] START index=6810
[VALIDATOR] START index=6326
[VALIDATOR] START index=7714
[VALIDATOR] START index=7445
[VALIDATOR] START index=7221
[VALIDATOR] START index=7907
[VALIDATOR] START index=6811
[VALIDATOR] START index=6327
[VALIDATOR] START index=7715
[VALIDATOR] START index=7446
[VALIDATOR] START index=7222
[VALIDATOR] START index=7908
[VALIDATOR] START index=6328
[VALIDATOR] START index=7716
[VALIDATOR] START index=6812
[VALIDATOR] START index=7447
[VALIDATOR] START index=7223
[VALIDATOR] START index=7909
[VALIDATOR] START index=6329
[VALIDATOR] START index=6813
[VALIDATOR] START index=7717
[VALIDATOR] START index=7448
[VALIDATOR] START index=7224
[VALIDATOR] START index=7910
[VALIDATOR] START index=6814
[VALIDATOR] START index=7718
[VALIDATOR] START index=6330
[VALIDATOR] START index=7449
[VALIDATOR] START index=7225
[VALIDATOR] START index=7911
[VALIDATOR] START index=6331
[VALIDATOR] START index=6815
[VALIDATOR] START index=7450
[VALIDATOR] START index=7719
[VALIDATOR] START index=7226
[VALIDATOR] START index=7912
[VALIDATOR] START index=7451
[VALIDATOR] START index=6816
[VALIDATOR] START index=6332
[VALIDATOR] START index=7720
[VALIDATOR] START index=7227
[VALIDATOR] START index=7913
[VALIDATOR] START index=6333
[VALIDATOR] START index=7452
[VALIDATOR] START index=7228
[VALIDATOR] START index=6817
[VALIDATOR] START index=7721
[VALIDATOR] START index=7914
[VALIDATOR] START index=6334
[VALIDATOR] START index=7453
[VALIDATOR] START index=7229
[VALIDATOR] START index=6818
[VALIDATOR] START index=7722
[VALIDATOR] START index=7915
[VALIDATOR] START index=7454
[VALIDATOR] START index=6335
[VALIDATOR] START index=7230
[VALIDATOR] START index=7723
[VALIDATOR] START index=6819
[VALIDATOR] START index=7455
[VALIDATOR] START index=7916
[VALIDATOR] START index=6336
[VALIDATOR] START index=7231
[VALIDATOR] START index=7724
[VALIDATOR] START index=6820
[VALIDATOR] START index=7917
[VALIDATOR] START index=7456
[VALIDATOR] START index=6337
[VALIDATOR] START index=7232
[VALIDATOR] START index=7725
[VALIDATOR] START index=6821
[VALIDATOR] START index=7457
[VALIDATOR] START index=7918
[VALIDATOR] START index=6338
[VALIDATOR] START index=7233
[VALIDATOR] START index=7726
[VALIDATOR] START index=6822
[VALIDATOR] START index=7458
[VALIDATOR] START index=7919
[VALIDATOR] START index=6339
[VALIDATOR] START index=7234
[VALIDATOR] START index=7727
[VALIDATOR] START index=6823
[VALIDATOR] START index=7459
[VALIDATOR] START index=6340
[VALIDATOR] START index=7235
[VALIDATOR] START index=7920
[VALIDATOR] START index=7728
[VALIDATOR] START index=6824
[VALIDATOR] START index=7460
[VALIDATOR] START index=6341
[VALIDATOR] START index=7921
[VALIDATOR] START index=7236
[VALIDATOR] START index=7729
[VALIDATOR] START index=7461
[VALIDATOR] START index=6342
[VALIDATOR] START index=7922
[VALIDATOR] START index=7237
[VALIDATOR] START index=7730
[VALIDATOR] START index=7462
[VALIDATOR] START index=6343
[VALIDATOR] START index=7238
[VALIDATOR] START index=7923
[VALIDATOR] START index=7731
[VALIDATOR] START index=7463
[VALIDATOR] START index=6825
[VALIDATOR] START index=7239
[VALIDATOR] START index=6344
[VALIDATOR] START index=7924
[VALIDATOR] START index=7732
[VALIDATOR] START index=7464
[VALIDATOR] START index=6826
[VALIDATOR] START index=7240
[VALIDATOR] START index=7925
[VALIDATOR] START index=7733
[VALIDATOR] START index=6345
[VALIDATOR] START index=7465
[VALIDATOR] START index=6827
[VALIDATOR] START index=7241
[VALIDATOR] START index=7734
[VALIDATOR] START index=6346
[VALIDATOR] START index=7926
[VALIDATOR] START index=7466
[VALIDATOR] START index=6828
[VALIDATOR] START index=7242
[VALIDATOR] START index=7927
[VALIDATOR] START index=7735
[VALIDATOR] START index=6347
[VALIDATOR] START index=7467
[VALIDATOR] START index=6829
[VALIDATOR] START index=7243
[VALIDATOR] START index=7736
[VALIDATOR] START index=7468
[VALIDATOR] START index=6348
[VALIDATOR] START index=7928
[VALIDATOR] START index=6830
[VALIDATOR] START index=7244
[VALIDATOR] START index=7737
[VALIDATOR] START index=7469
[VALIDATOR] START index=7929
[VALIDATOR] START index=6349
[VALIDATOR] START index=6831
[VALIDATOR] START index=7245
[VALIDATOR] START index=7738
[VALIDATOR] START index=7470
[VALIDATOR] START index=7930
[VALIDATOR] START index=6350
[VALIDATOR] START index=6832
[VALIDATOR] START index=7739
[VALIDATOR] START index=7246
[VALIDATOR] START index=7471
[VALIDATOR] START index=6351
[VALIDATOR] START index=6833
[VALIDATOR] START index=7931
[VALIDATOR] START index=7247
[VALIDATOR] START index=7740
[VALIDATOR] START index=7472
[VALIDATOR] START index=6352
[VALIDATOR] START index=6834
[VALIDATOR] START index=7932
[VALIDATOR] START index=7741
[VALIDATOR] START index=7248
[VALIDATOR] START index=7473
[VALIDATOR] START index=6835
[VALIDATOR] START index=6353
[VALIDATOR] START index=7742
[VALIDATOR] START index=7933
[VALIDATOR] START index=7249
[VALIDATOR] START index=7474
[VALIDATOR] START index=6354
[VALIDATOR] START index=6836
[VALIDATOR] START index=7934
[VALIDATOR] START index=7743
[VALIDATOR] START index=7250
[VALIDATOR] START index=7475
[VALIDATOR] START index=6837
[VALIDATOR] START index=6355
[VALIDATOR] START index=7935
[VALIDATOR] START index=7744
[VALIDATOR] START index=7251
[VALIDATOR] START index=7476
[VALIDATOR] START index=6838
[VALIDATOR] START index=7936
[VALIDATOR] START index=7745
[VALIDATOR] START index=6356
[VALIDATOR] START index=7252
[VALIDATOR] START index=7477
[VALIDATOR] START index=6839
[VALIDATOR] START index=7746
[VALIDATOR] START index=7937
[VALIDATOR] START index=6357
[VALIDATOR] START index=7253
[VALIDATOR] START index=7478
[VALIDATOR] START index=6840
[VALIDATOR] START index=7747
[VALIDATOR] START index=7938
[VALIDATOR] START index=6358
[VALIDATOR] START index=7254
[VALIDATOR] START index=7479
[VALIDATOR] START index=6841
[VALIDATOR] START index=7255
[VALIDATOR] START index=6359
[VALIDATOR] START index=7748
[VALIDATOR] START index=7939
[VALIDATOR] START index=7480
[VALIDATOR] START index=6842
[VALIDATOR] START index=7256
[VALIDATOR] START index=6360
[VALIDATOR] START index=7940
[VALIDATOR] START index=7749
[VALIDATOR] START index=7481
[VALIDATOR] START index=6843
[VALIDATOR] START index=7750
[VALIDATOR] START index=7257
[VALIDATOR] START index=7941
[VALIDATOR] START index=6361
[VALIDATOR] START index=7482
[VALIDATOR] START index=6844
[VALIDATOR] START index=7942
[VALIDATOR] START index=6362
[VALIDATOR] START index=7751
[VALIDATOR] START index=7258
[VALIDATOR] START index=7483
[VALIDATOR] START index=6363
[VALIDATOR] START index=7752
[VALIDATOR] START index=7484
[VALIDATOR] START index=7259
[VALIDATOR] START index=7943
[VALIDATOR] START index=6364
[VALIDATOR] START index=7260
[VALIDATOR] START index=7753
[VALIDATOR] START index=7485
[VALIDATOR] START index=7944
[VALIDATOR] START index=6845
[VALIDATOR] START index=6365
[VALIDATOR] START index=7261
[VALIDATOR] START index=7486
[VALIDATOR] START index=7754
[VALIDATOR] START index=7945
[VALIDATOR] START index=6366
[VALIDATOR] START index=6846
[VALIDATOR] START index=7262
[VALIDATOR] START index=7755
[VALIDATOR] START index=7487
[VALIDATOR] START index=7946
[VALIDATOR] START index=6367
[VALIDATOR] START index=7263
[VALIDATOR] START index=6847
[VALIDATOR] START index=7756
[VALIDATOR] START index=7488
[VALIDATOR] START index=7947
[VALIDATOR] START index=7264
[VALIDATOR] START index=6368
[VALIDATOR] START index=6848
[VALIDATOR] START index=7757
[VALIDATOR] START index=7948
[VALIDATOR] START index=7489
[VALIDATOR] START index=7265
[VALIDATOR] START index=6369
[VALIDATOR] START index=7758
[VALIDATOR] START index=6849
[VALIDATOR] START index=7949
[VALIDATOR] START index=7490
[VALIDATOR] START index=6370
[VALIDATOR] START index=6850
[VALIDATOR] START index=7266
[VALIDATOR] START index=7759
[VALIDATOR] START index=7950
[VALIDATOR] START index=7491
[VALIDATOR] START index=7267
[VALIDATOR] START index=6371
[VALIDATOR] START index=6851
[VALIDATOR] START index=7760
[VALIDATOR] START index=7492
[VALIDATOR] START index=7951
[VALIDATOR] START index=7268
[VALIDATOR] START index=6372
[VALIDATOR] START index=7761
[VALIDATOR] START index=6852
[VALIDATOR] START index=7493
[VALIDATOR] START index=7952
[VALIDATOR] START index=6373
[VALIDATOR] START index=7269
[VALIDATOR] START index=6853
[VALIDATOR] START index=7762
[VALIDATOR] START index=7494
[VALIDATOR] START index=7953
[VALIDATOR] START index=7270
[VALIDATOR] START index=6374
[VALIDATOR] START index=7763
[VALIDATOR] START index=6854
[VALIDATOR] START index=7495
[VALIDATOR] START index=7954
[VALIDATOR] START index=7271
[VALIDATOR] START index=6375
[VALIDATOR] START index=7764
[VALIDATOR] START index=6855
[VALIDATOR] START index=7496
[VALIDATOR] START index=7955
[VALIDATOR] START index=7272
[VALIDATOR] START index=6376
[VALIDATOR] START index=7765
[VALIDATOR] START index=6856
[VALIDATOR] START index=7497
[VALIDATOR] START index=7956
[VALIDATOR] START index=6377
[VALIDATOR] START index=7766
[VALIDATOR] START index=7273
[VALIDATOR] START index=6857
[VALIDATOR] START index=7498
[VALIDATOR] START index=7957
[VALIDATOR] START index=7767
[VALIDATOR] START index=6378
[VALIDATOR] START index=7274
[VALIDATOR] START index=7499
[VALIDATOR] START index=7958
[VALIDATOR] START index=7768
[VALIDATOR] START index=6379
[VALIDATOR] START index=7275
[VALIDATOR] START index=7500
[VALIDATOR] START index=7959
[VALIDATOR] START index=7769
[VALIDATOR] START index=6380
[VALIDATOR] START index=7276
[VALIDATOR] START index=7501
[VALIDATOR] START index=6858
[VALIDATOR] START index=7960
[VALIDATOR] START index=7770
[VALIDATOR] START index=6381
[VALIDATOR] START index=7277
[VALIDATOR] START index=7502
[VALIDATOR] START index=6859
[VALIDATOR] START index=7961
[VALIDATOR] START index=7771
[VALIDATOR] START index=6382
[VALIDATOR] START index=7278
[VALIDATOR] START index=7503
[VALIDATOR] START index=6860
[VALIDATOR] START index=7772
[VALIDATOR] START index=7962
[VALIDATOR] START index=6383
[VALIDATOR] START index=7279
[VALIDATOR] START index=7504
[VALIDATOR] START index=6861
[VALIDATOR] START index=7773
[VALIDATOR] START index=7963
[VALIDATOR] START index=7280
[VALIDATOR] START index=6384
[VALIDATOR] START index=7505
[VALIDATOR] START index=6862
[VALIDATOR] START index=7281
[VALIDATOR] START index=7774
[VALIDATOR] START index=7964
[VALIDATOR] START index=7506
[VALIDATOR] START index=6385
[VALIDATOR] START index=6863
[VALIDATOR] START index=7282
[VALIDATOR] START index=7507
[VALIDATOR] START index=7775
[VALIDATOR] START index=7965
[VALIDATOR] START index=6386
[VALIDATOR] START index=6864
[VALIDATOR] START index=7283
[VALIDATOR] START index=6387
[VALIDATOR] START index=7508
[VALIDATOR] START index=7776
[VALIDATOR] START index=7966
[VALIDATOR] START index=6865
[VALIDATOR] START index=7284
[VALIDATOR] START index=6388
[VALIDATOR] START index=7509
[VALIDATOR] START index=7777
[VALIDATOR] START index=6866
[VALIDATOR] START index=7967
[VALIDATOR] START index=7285
[VALIDATOR] START index=7778
[VALIDATOR] START index=6389
[VALIDATOR] START index=6867
[VALIDATOR] START index=7968
[VALIDATOR] START index=7510
[VALIDATOR] START index=7286
[VALIDATOR] START index=7779
[VALIDATOR] START index=6390
[VALIDATOR] START index=7511
[VALIDATOR] START index=7969
[VALIDATOR] START index=6868
[VALIDATOR] START index=7287
[VALIDATOR] START index=6391
[VALIDATOR] START index=6869
[VALIDATOR] START index=7780
[VALIDATOR] START index=7512
[VALIDATOR] START index=7970
[VALIDATOR] START index=6392
[VALIDATOR] START index=7288
[VALIDATOR] START index=7781
[VALIDATOR] START index=7513
[VALIDATOR] START index=6870
[VALIDATOR] START index=7971
[VALIDATOR] START index=6393
[VALIDATOR] START index=7782
[VALIDATOR] START index=7289
[VALIDATOR] START index=7514
[VALIDATOR] START index=6871
[VALIDATOR] START index=7972
[VALIDATOR] START index=6394
[VALIDATOR] START index=7783
[VALIDATOR] START index=7290
[VALIDATOR] START index=7515
[VALIDATOR] START index=6872
[VALIDATOR] START index=7973
[VALIDATOR] START index=6395
[VALIDATOR] START index=7784
[VALIDATOR] START index=7516
[VALIDATOR] START index=7291
[VALIDATOR] START index=6873
[VALIDATOR] START index=7974
[VALIDATOR] START index=6396
[VALIDATOR] START index=7517
[VALIDATOR] START index=7785
[VALIDATOR] START index=6874
[VALIDATOR] START index=7292
[VALIDATOR] START index=7975
[VALIDATOR] START index=6397
[VALIDATOR] START index=7518
[VALIDATOR] START index=7786
[VALIDATOR] START index=6875
[VALIDATOR] START index=7293
[VALIDATOR] START index=7976
[VALIDATOR] START index=6398
[VALIDATOR] START index=7519
[VALIDATOR] START index=7787
[VALIDATOR] START index=6876
[VALIDATOR] START index=7977
[VALIDATOR] START index=7294
[VALIDATOR] START index=6399
[VALIDATOR] START index=7520
[VALIDATOR] START index=7788
[VALIDATOR] START index=6877
[VALIDATOR] START index=7978
[VALIDATOR] START index=7295
[VALIDATOR] START index=6400
[VALIDATOR] START index=7521
[VALIDATOR] START index=6878
[VALIDATOR] START index=7789
[VALIDATOR] START index=7296
[VALIDATOR] START index=7979

 72%|███████▎  | 29/40 [19:39<23:20, 127.33s/it]

[VALIDATOR] START index=7522
[VALIDATOR] bug=sieve candidates=250
[VALIDATOR] START index=8183
[VALIDATOR] START index=7790
[VALIDATOR] START index=6879
[VALIDATOR] START index=7297
[VALIDATOR] START index=7980
[VALIDATOR] START index=7791
[VALIDATOR] START index=6880
[VALIDATOR] START index=7523
[VALIDATOR] START index=8184
[VALIDATOR] START index=7298
[VALIDATOR] START index=7981
[VALIDATOR] START index=7524
[VALIDATOR] START index=6881
[VALIDATOR] START index=7792
[VALIDATOR] START index=8185
[VALIDATOR] START index=7299
[VALIDATOR] START index=7982
[VALIDATOR] START index=7525
[VALIDATOR] START index=6882
[VALIDATOR] START index=8186
[VALIDATOR] START index=7300
[VALIDATOR] START index=7793
[VALIDATOR] START index=7983
[VALIDATOR] START index=7526
[VALIDATOR] START index=8187
[VALIDATOR] START index=6883
[VALIDATOR] START index=7301
[VALIDATOR] START index=7794
[VALIDATOR] START index=7984
[VALIDATOR] START index=7527
[VALIDATOR] START index=8188
[VALIDATOR] START index=6884
[VALIDATOR] START index=7795
[VALIDATOR] START index=7302
[VALIDATOR] START index=7985
[VALIDATOR] START index=7528
[VALIDATOR] START index=6885
[VALIDATOR] START index=8189
[VALIDATOR] START index=7796
[VALIDATOR] START index=7303
[VALIDATOR] START index=7986
[VALIDATOR] START index=8190
[VALIDATOR] START index=6886
[VALIDATOR] START index=7529
[VALIDATOR] START index=7797
[VALIDATOR] START index=7304
[VALIDATOR] START index=7987
[VALIDATOR] START index=6887
[VALIDATOR] START index=7530
[VALIDATOR] START index=8191
[VALIDATOR] START index=7798
[VALIDATOR] START index=7305
[VALIDATOR] START index=7988
[VALIDATOR] START index=6888
[VALIDATOR] START index=7531
[VALIDATOR] START index=8192
[VALIDATOR] START index=7799
[VALIDATOR] START index=7306
[VALIDATOR] START index=6889
[VALIDATOR] START index=7800
[VALIDATOR] START index=7532
[VALIDATOR] START index=8193
[VALIDATOR] START index=7989
[VALIDATOR] START index=7307
[VALIDATOR] START index=6890
[VALIDATOR] START index=8194
[VALIDATOR] START index=7533
[VALIDATOR] START index=7801
[VALIDATOR] START index=7308
[VALIDATOR] START index=7990
[VALIDATOR] START index=6891
[VALIDATOR] START index=8195
[VALIDATOR] START index=7802
[VALIDATOR] START index=7534
[VALIDATOR] START index=7309
[VALIDATOR] START index=7991

 75%|███████▌  | 30/40 [20:17<16:45, 100.57s/it]

[VALIDATOR] START index=7803
[VALIDATOR] START index=6892
[VALIDATOR] bug=sqrt candidates=254
[VALIDATOR] START index=8433
[VALIDATOR] START index=7535
[VALIDATOR] START index=7310
[VALIDATOR] START index=7992
[VALIDATOR] START index=7804
[VALIDATOR] START index=8434
[VALIDATOR] START index=6893
[VALIDATOR] START index=7536
[VALIDATOR] START index=7993
[VALIDATOR] START index=7311
[VALIDATOR] START index=7805
[VALIDATOR] START index=6894
[VALIDATOR] START index=7537
[VALIDATOR] START index=7994
[VALIDATOR] START index=7312
[VALIDATOR] START index=7806
[VALIDATOR] START index=7538
[VALIDATOR] START index=6895
[VALIDATOR] START index=7995
[VALIDATOR] START index=7313
[VALIDATOR] START index=7807
[VALIDATOR] START index=7996
[VALIDATOR] START index=7539
[VALIDATOR] START index=7314
[VALIDATOR] START index=8435
[VALIDATOR] START index=7808
[VALIDATOR] START index=7540
[VALIDATOR] START index=7997
[VALIDATOR] START index=7315
[VALIDATOR] START index=7809
[VALIDATOR] START index=7541
[VALIDATOR] START index=7998
[VALIDATOR] START index=7316
[VALIDATOR] START index=6896
[VALIDATOR] START index=7810
[VALIDATOR] START index=7542
[VALIDATOR] START index=7999
[VALIDATOR] START index=7317
[VALIDATOR] START index=6897
[VALIDATOR] START index=7811
[VALIDATOR] START index=7543
[VALIDATOR] START index=8436
[VALIDATOR] START index=8000
[VALIDATOR] START index=6898
[VALIDATOR] START index=7318
[VALIDATOR] START index=7812
[VALIDATOR] START index=8437
[VALIDATOR] START index=7544
[VALIDATOR] START index=8001
[VALIDATOR] START index=6899
[VALIDATOR] START index=7319
[VALIDATOR] START index=7813
[VALIDATOR] START index=7545
[VALIDATOR] START index=8002

 78%|███████▊  | 31/40 [20:48<11:55, 79.55s/it]

[VALIDATOR] bug=subsequences candidates=204
[VALIDATOR] START index=8687
[VALIDATOR] START index=7814
[VALIDATOR] START index=7320
[VALIDATOR] START index=7546
[VALIDATOR] START index=8003
[VALIDATOR] START index=7815
[VALIDATOR] START index=7321
[VALIDATOR] START index=8688
[VALIDATOR] START index=7547
[VALIDATOR] START index=8004
[VALIDATOR] START index=8438
[VALIDATOR] START index=7816
[VALIDATOR] START index=7322
[VALIDATOR] START index=8689
[VALIDATOR] START index=7548
[VALIDATOR] START index=7817
[VALIDATOR] START index=8005
[VALIDATOR] START index=7323
[VALIDATOR] START index=8690
[VALIDATOR] START index=7549
[VALIDATOR] START index=8006
[VALIDATOR] START index=7818
[VALIDATOR] START index=7324
[VALIDATOR] START index=8691
[VALIDATOR] START index=7550
[VALIDATOR] START index=7819
[VALIDATOR] START index=7325
[VALIDATOR] START index=8007
[VALIDATOR] START index=8439
[VALIDATOR] START index=8692
[VALIDATOR] START index=7551
[VALIDATOR] START index=7820
[VALIDATOR] START index=7326
[VALIDATOR] START index=8008
[VALIDATOR] START index=8693
[VALIDATOR] START index=7552
[VALIDATOR] START index=7821
[VALIDATOR] START index=7327
[VALIDATOR] START index=8009
[VALIDATOR] START index=8694
[VALIDATOR] START index=7822
[VALIDATOR] START index=7328
[VALIDATOR] START index=7553
[VALIDATOR] START index=8010
[VALIDATOR] START index=8695
[VALIDATOR] START index=7823
[VALIDATOR] START index=8440
[VALIDATOR] START index=7329
[VALIDATOR] START index=7554
[VALIDATOR] START index=8011
[VALIDATOR] START index=8696
[VALIDATOR] START index=7824
[VALIDATOR] START index=7330
[VALIDATOR] START index=8441
[VALIDATOR] START index=7555
[VALIDATOR] START index=8697
[VALIDATOR] START index=8012
[VALIDATOR] START index=7825
[VALIDATOR] START index=7331
[VALIDATOR] START index=7556
[VALIDATOR] START index=8698
[VALIDATOR] START index=8013
[VALIDATOR] START index=7826
[VALIDATOR] START index=7557
[VALIDATOR] START index=7332
[VALIDATOR] START index=8699
[VALIDATOR] START index=8014
[VALIDATOR] START index=7827
[VALIDATOR] START index=7558
[VALIDATOR] START index=7333
[VALIDATOR] START index=8700
[VALIDATOR] START index=8442
[VALIDATOR] START index=8015
[VALIDATOR] START index=7559
[VALIDATOR] START index=7828
[VALIDATOR] START index=7334
[VALIDATOR] START index=8701
[VALIDATOR] START index=8443
[VALIDATOR] START index=7829
[VALIDATOR] START index=7560
[VALIDATOR] START index=7335
[VALIDATOR] START index=8016
[VALIDATOR] START index=8702
[VALIDATOR] START index=8444
[VALIDATOR] START index=7561
[VALIDATOR] START index=7830
[VALIDATOR] START index=7336
[VALIDATOR] START index=8017
[VALIDATOR] START index=8703
[VALIDATOR] START index=7562
[VALIDATOR] START index=7337
[VALIDATOR] START index=7831
[VALIDATOR] START index=8018
[VALIDATOR] START index=8704
[VALIDATOR] START index=7563
[VALIDATOR] START index=7338
[VALIDATOR] START index=7832
[VALIDATOR] START index=8019
[VALIDATOR] START index=8705
[VALIDATOR] START index=7564
[VALIDATOR] START index=7339
[VALIDATOR] START index=8445
[VALIDATOR] START index=7833
[VALIDATOR] START index=8020
[VALIDATOR] START index=8706
[VALIDATOR] START index=7565
[VALIDATOR] START index=8446
[VALIDATOR] START index=7834
[VALIDATOR] START index=7340
[VALIDATOR] START index=8707
[VALIDATOR] START index=8021
[VALIDATOR] START index=7566
[VALIDATOR] START index=8447
[VALIDATOR] START index=7835
[VALIDATOR] START index=7341
[VALIDATOR] START index=8708
[VALIDATOR] START index=8022
[VALIDATOR] START index=7567
[VALIDATOR] START index=8448
[VALIDATOR] START index=7836
[VALIDATOR] START index=7342
[VALIDATOR] START index=8709
[VALIDATOR] START index=7568
[VALIDATOR] START index=8023
[VALIDATOR] START index=7837
[VALIDATOR] START index=7343
[VALIDATOR] START index=8710
[VALIDATOR] START index=7569
[VALIDATOR] START index=8024
[VALIDATOR] START index=7838
[VALIDATOR] START index=8711
[VALIDATOR] START index=7344
[VALIDATOR] START index=7570
[VALIDATOR] START index=8025
[VALIDATOR] START index=7839
[VALIDATOR] START index=8712
[VALIDATOR] START index=8449
[VALIDATOR] START index=7345
[VALIDATOR] START index=7571
[VALIDATOR] START index=8026
[VALIDATOR] START index=7840
[VALIDATOR] START index=8713
[VALIDATOR] START index=7572
[VALIDATOR] START index=7346
[VALIDATOR] START index=8027
[VALIDATOR] START index=7841
[VALIDATOR] START index=8714
[VALIDATOR] START index=7573
[VALIDATOR] START index=7347
[VALIDATOR] START index=8028
[VALIDATOR] START index=7842
[VALIDATOR] START index=8715
[VALIDATOR] START index=7574
[VALIDATOR] START index=7348
[VALIDATOR] START index=8029
[VALIDATOR] START index=8450
[VALIDATOR] START index=7843
[VALIDATOR] START index=8716
[VALIDATOR] START index=7575
[VALIDATOR] START index=7349
[VALIDATOR] START index=8030
[VALIDATOR] START index=8451
[VALIDATOR] START index=7844
[VALIDATOR] START index=7576
[VALIDATOR] START index=8717
[VALIDATOR] START index=8031
[VALIDATOR] START index=7350
[VALIDATOR] START index=7845
[VALIDATOR] START index=7577
[VALIDATOR] START index=8718
[VALIDATOR] START index=7351
[VALIDATOR] START index=8032
[VALIDATOR] START index=7846
[VALIDATOR] START index=7578
[VALIDATOR] START index=8719
[VALIDATOR] START index=7352
[VALIDATOR] START index=8033
[VALIDATOR] START index=7847
[VALIDATOR] START index=7579
[VALIDATOR] START index=8452
[VALIDATOR] START index=8720
[VALIDATOR] START index=8034
[VALIDATOR] START index=7353
[VALIDATOR] START index=7848
[VALIDATOR] START index=7580
[VALIDATOR] START index=8721
[VALIDATOR] START index=8035
[VALIDATOR] START index=7354
[VALIDATOR] START index=7581
[VALIDATOR] START index=7849
[VALIDATOR] START index=8722
[VALIDATOR] START index=8036
[VALIDATOR] START index=7355
[VALIDATOR] START index=7582
[VALIDATOR] START index=7850
[VALIDATOR] START index=8723
[VALIDATOR] START index=8037
[VALIDATOR] START index=8453
[VALIDATOR] START index=7356
[VALIDATOR] START index=7583
[VALIDATOR] START index=7851
[VALIDATOR] START index=8724
[VALIDATOR] START index=8038
[VALIDATOR] START index=7357
[VALIDATOR] START index=7584
[VALIDATOR] START index=7852
[VALIDATOR] START index=8725
[VALIDATOR] START index=7358
[VALIDATOR] START index=8039
[VALIDATOR] START index=7585
[VALIDATOR] START index=7853
[VALIDATOR] START index=8726
[VALIDATOR] START index=8040
[VALIDATOR] START index=7359
[VALIDATOR] START index=7854
[VALIDATOR] START index=7586
[VALIDATOR] START index=8454
[VALIDATOR] START index=8727
[VALIDATOR] START index=8041
[VALIDATOR] START index=7360
[VALIDATOR] START index=7587
[VALIDATOR] START index=7855
[VALIDATOR] START index=8728
[VALIDATOR] START index=7361
[VALIDATOR] START index=8042
[VALIDATOR] START index=7588
[VALIDATOR] START index=7856
[VALIDATOR] START index=8729
[VALIDATOR] START index=7362
[VALIDATOR] START index=8043
[VALIDATOR] START index=7589
[VALIDATOR] START index=7857
[VALIDATOR] START index=8730
[VALIDATOR] START index=8455
[VALIDATOR] START index=7363
[VALIDATOR] START index=7590
[VALIDATOR] START index=8044
[VALIDATOR] START index=7858
[VALIDATOR] START index=8731
[VALIDATOR] START index=7364
[VALIDATOR] START index=7591
[VALIDATOR] START index=8045
[VALIDATOR] START index=7859
[VALIDATOR] START index=8732
[VALIDATOR] START index=7365
[VALIDATOR] START index=7592
[VALIDATOR] START index=8046
[VALIDATOR] START index=7860

 80%|████████  | 32/40 [23:02<12:46, 95.87s/it]

[VALIDATOR] bug=to_base candidates=257
[VALIDATOR] START index=8891
[VALIDATOR] START index=7366
[VALIDATOR] START index=7593
[VALIDATOR] START index=8047
[VALIDATOR] START index=8456
[VALIDATOR] START index=8892
[VALIDATOR] START index=7861
[VALIDATOR] START index=7367
[VALIDATOR] START index=7594
[VALIDATOR] START index=8048
[VALIDATOR] START index=7862
[VALIDATOR] START index=8893
[VALIDATOR] START index=7368
[VALIDATOR] START index=7595
[VALIDATOR] START index=8049
[VALIDATOR] START index=8894
[VALIDATOR] START index=7863
[VALIDATOR] START index=7369
[VALIDATOR] START index=7596
[VALIDATOR] START index=8050
[VALIDATOR] START index=7864
[VALIDATOR] START index=8895
[VALIDATOR] START index=8457
[VALIDATOR] START index=7370
[VALIDATOR] START index=7597
[VALIDATOR] START index=8051
[VALIDATOR] START index=7865
[VALIDATOR] START index=8896
[VALIDATOR] START index=7371
[VALIDATOR] START index=7598
[VALIDATOR] START index=8052
[VALIDATOR] START index=7866
[VALIDATOR] START index=8897
[VALIDATOR] START index=7372
[VALIDATOR] START index=7599
[VALIDATOR] START index=8053
[VALIDATOR] START index=7867
[VALIDATOR] START index=7373
[VALIDATOR] START index=8898
[VALIDATOR] START index=7600
[VALIDATOR] START index=8054
[VALIDATOR] START index=8458
[VALIDATOR] START index=7374
[VALIDATOR] START index=7868
[VALIDATOR] START index=8899
[VALIDATOR] START index=8055
[VALIDATOR] START index=7601
[VALIDATOR] START index=7375
[VALIDATOR] START index=7869
[VALIDATOR] START index=8900
[VALIDATOR] START index=8056
[VALIDATOR] START index=7602
[VALIDATOR] START index=7376
[VALIDATOR] START index=8901
[VALIDATOR] START index=7870
[VALIDATOR] START index=7603
[VALIDATOR] START index=8057
[VALIDATOR] START index=7377
[VALIDATOR] START index=8459
[VALIDATOR] START index=8902
[VALIDATOR] START index=7871
[VALIDATOR] START index=8058
[VALIDATOR] START index=7604
[VALIDATOR] START index=7378
[VALIDATOR] START index=7872
[VALIDATOR] START index=8460
[VALIDATOR] START index=8903
[VALIDATOR] START index=7605
[VALIDATOR] START index=8059
[VALIDATOR] START index=7379
[VALIDATOR] START index=7873
[VALIDATOR] START index=8461
[VALIDATOR] START index=8904
[VALIDATOR] START index=8060
[VALIDATOR] START index=7606
[VALIDATOR] START index=7380
[VALIDATOR] START index=7874
[VALIDATOR] START index=8905
[VALIDATOR] START index=8061
[VALIDATOR] START index=7607
[VALIDATOR] START index=7381
[VALIDATOR] START index=7875
[VALIDATOR] START index=8906
[VALIDATOR] START index=7608
[VALIDATOR] START index=8062
[VALIDATOR] START index=7876
[VALIDATOR] START index=7382
[VALIDATOR] START index=8907
[VALIDATOR] START index=7609
[VALIDATOR] START index=8063
[VALIDATOR] START index=8462
[VALIDATOR] START index=7877
[VALIDATOR] START index=7383
[VALIDATOR] START index=8908
[VALIDATOR] START index=7610
[VALIDATOR] START index=8064
[VALIDATOR] START index=7878
[VALIDATOR] START index=7384
[VALIDATOR] START index=8909
[VALIDATOR] START index=7611
[VALIDATOR] START index=7879
[VALIDATOR] START index=8065
[VALIDATOR] START index=7385
[VALIDATOR] START index=8910
[VALIDATOR] START index=7612
[VALIDATOR] START index=8066
[VALIDATOR] START index=7880
[VALIDATOR] START index=8911
[VALIDATOR] START index=8463
[VALIDATOR] START index=7386
[VALIDATOR] START index=7613
[VALIDATOR] START index=8067
[VALIDATOR] START index=7881
[VALIDATOR] START index=8464
[VALIDATOR] START index=8912
[VALIDATOR] START index=7387
[VALIDATOR] START index=7614
[VALIDATOR] START index=8068
[VALIDATOR] START index=8465
[VALIDATOR] START index=8913
[VALIDATOR] START index=7882
[VALIDATOR] START index=7388
[VALIDATOR] START index=7615
[VALIDATOR] START index=8914
[VALIDATOR] START index=8069
[VALIDATOR] START index=7883
[VALIDATOR] START index=7389
[VALIDATOR] START index=7616
[VALIDATOR] START index=8915
[VALIDATOR] START index=8070
[VALIDATOR] START index=7884
[VALIDATOR] START index=7390
[VALIDATOR] START index=7617
[VALIDATOR] START index=8916
[VALIDATOR] START index=8071
[VALIDATOR] START index=7391
[VALIDATOR] START index=7885
[VALIDATOR] START index=8466
[VALIDATOR] START index=7618
[VALIDATOR] START index=8917
[VALIDATOR] START index=8072
[VALIDATOR] START index=7886
[VALIDATOR] START index=7392
[VALIDATOR] START index=7619
[VALIDATOR] START index=8918
[VALIDATOR] START index=7887
[VALIDATOR] START index=8073
[VALIDATOR] START index=7393
[VALIDATOR] START index=7620
[VALIDATOR] START index=8919
[VALIDATOR] START index=7888
[VALIDATOR] START index=7394
[VALIDATOR] START index=8074
[VALIDATOR] START index=7621
[VALIDATOR] START index=8920
[VALIDATOR] START index=8467

 82%|████████▎ | 33/40 [24:27<10:48, 92.60s/it]

[VALIDATOR] bug=topological_ordering candidates=233
[VALIDATOR] START index=9148
[VALIDATOR] START index=8075

 85%|████████▌ | 34/40 [24:27<06:29, 64.96s/it]

[VALIDATOR] bug=wrap candidates=286
[VALIDATOR] START index=9381
[VALIDATOR] START index=7622
[VALIDATOR] START index=8921
[VALIDATOR] START index=9149
[VALIDATOR] START index=8076
[VALIDATOR] START index=9382
[VALIDATOR] START index=7623
[VALIDATOR] START index=8922

 88%|████████▊ | 35/40 [24:32<03:55, 47.02s/it]

[VALIDATOR] START index=8077
[VALIDATOR] START index=9383
[VALIDATOR] START index=8923
[VALIDATOR] START index=7624
[VALIDATOR] START index=8078
[VALIDATOR] START index=9384
[VALIDATOR] START index=8468
[VALIDATOR] START index=8924
[VALIDATOR] START index=7625
[VALIDATOR] START index=8079
[VALIDATOR] START index=9385
[VALIDATOR] START index=8925
[VALIDATOR] START index=7626
[VALIDATOR] START index=8080
[VALIDATOR] START index=9386
[VALIDATOR] START index=8926
[VALIDATOR] START index=7627
[VALIDATOR] START index=8081
[VALIDATOR] START index=9387
[VALIDATOR] START index=8927
[VALIDATOR] START index=7628
[VALIDATOR] START index=8082
[VALIDATOR] START index=8928
[VALIDATOR] START index=9388
[VALIDATOR] START index=8469
[VALIDATOR] START index=7629
[VALIDATOR] START index=8083
[VALIDATOR] START index=8929
[VALIDATOR] START index=9389
[VALIDATOR] START index=8470
[VALIDATOR] START index=7630
[VALIDATOR] START index=8084
[VALIDATOR] START index=8930
[VALIDATOR] START index=9390
[VALIDATOR] START index=8471
[VALIDATOR] START index=7631
[VALIDATOR] START index=8085
[VALIDATOR] START index=8931
[VALIDATOR] START index=9391
[VALIDATOR] START index=8472
[VALIDATOR] START index=7632
[VALIDATOR] START index=8932
[VALIDATOR] START index=8086
[VALIDATOR] START index=9392
[VALIDATOR] START index=7633
[VALIDATOR] START index=8473
[VALIDATOR] START index=8933
[VALIDATOR] START index=8087
[VALIDATOR] START index=7634
[VALIDATOR] START index=9393
[VALIDATOR] START index=8934
[VALIDATOR] START index=8088
[VALIDATOR] START index=7635
[VALIDATOR] START index=9394
[VALIDATOR] START index=8935
[VALIDATOR] START index=8089
[VALIDATOR] START index=9395
[VALIDATOR] START index=7636
[VALIDATOR] START index=8936
[VALIDATOR] START index=8090
[VALIDATOR] START index=8937
[VALIDATOR] START index=7637
[VALIDATOR] START index=9396
[VALIDATOR] START index=8474
[VALIDATOR] START index=8091
[VALIDATOR] START index=7638
[VALIDATOR] START index=8938
[VALIDATOR] START index=8475
[VALIDATOR] START index=9397
[VALIDATOR] START index=8092
[VALIDATOR] START index=7639
[VALIDATOR] START index=8476
[VALIDATOR] START index=8939
[VALIDATOR] START index=9398
[VALIDATOR] START index=8093
[VALIDATOR] START index=7640
[VALIDATOR] START index=8477
[VALIDATOR] START index=8940
[VALIDATOR] START index=9399
[VALIDATOR] START index=8094
[VALIDATOR] START index=7641
[VALIDATOR] START index=8941
[VALIDATOR] START index=9400
[VALIDATOR] START index=8095
[VALIDATOR] START index=7642
[VALIDATOR] START index=8942
[VALIDATOR] START index=8096
[VALIDATOR] START index=7643
[VALIDATOR] START index=8943
[VALIDATOR] START index=8097
[VALIDATOR] START index=7644
[VALIDATOR] START index=8944
[VALIDATOR] START index=8478
[VALIDATOR] START index=8098
[VALIDATOR] START index=8945
[VALIDATOR] START index=7645
[VALIDATOR] START index=8479
[VALIDATOR] START index=8099
[VALIDATOR] START index=9401
[VALIDATOR] START index=8946
[VALIDATOR] START index=7646
[VALIDATOR] START index=8100
[VALIDATOR] START index=9402
[VALIDATOR] START index=8947
[VALIDATOR] START index=7647
[VALIDATOR] START index=8101

 90%|█████████ | 36/40 [25:31<03:22, 50.60s/it]

[VALIDATOR] START index=8948
[VALIDATOR] START index=7648
[VALIDATOR] START index=8102
[VALIDATOR] START index=8949
[VALIDATOR] START index=7649
[VALIDATOR] START index=8103
[VALIDATOR] START index=8950
[VALIDATOR] START index=8480
[VALIDATOR] START index=7650
[VALIDATOR] START index=8104
[VALIDATOR] START index=8951
[VALIDATOR] START index=7651
[VALIDATOR] START index=8105
[VALIDATOR] START index=8952
[VALIDATOR] START index=7652
[VALIDATOR] START index=8106
[VALIDATOR] START index=8953
[VALIDATOR] START index=7653
[VALIDATOR] START index=8107
[VALIDATOR] START index=8954
[VALIDATOR] START index=7654
[VALIDATOR] START index=8108
[VALIDATOR] START index=8955
[VALIDATOR] START index=7655
[VALIDATOR] START index=8109
[VALIDATOR] START index=8481
[VALIDATOR] START index=8956
[VALIDATOR] START index=7656
[VALIDATOR] START index=8957
[VALIDATOR] START index=7657
[VALIDATOR] START index=8958
[VALIDATOR] START index=7658
[VALIDATOR] START index=8959
[VALIDATOR] START index=7659
[VALIDATOR] START index=8960
[VALIDATOR] START index=7660
[VALIDATOR] START index=8110
[VALIDATOR] START index=8482
[VALIDATOR] START index=8961
[VALIDATOR] START index=7661
[VALIDATOR] START index=8483
[VALIDATOR] START index=8111
[VALIDATOR] START index=8962
[VALIDATOR] START index=7662
[VALIDATOR] START index=8484
[VALIDATOR] START index=8112
[VALIDATOR] START index=8963
[VALIDATOR] START index=7663
[VALIDATOR] START index=8113
[VALIDATOR] START index=8964
[VALIDATOR] START index=7664
[VALIDATOR] START index=8114
[VALIDATOR] START index=8965
[VALIDATOR] START index=7665
[VALIDATOR] START index=8115
[VALIDATOR] START index=8966

 92%|█████████▎| 37/40 [26:07<02:18, 46.03s/it]

[VALIDATOR] START index=8116
[VALIDATOR] START index=8967
[VALIDATOR] START index=8117
[VALIDATOR] START index=8968
[VALIDATOR] START index=8485
[VALIDATOR] START index=8118
[VALIDATOR] START index=8969
[VALIDATOR] START index=8119
[VALIDATOR] START index=8970
[VALIDATOR] START index=8120
[VALIDATOR] START index=8971
[VALIDATOR] START index=8121
[VALIDATOR] START index=8972
[VALIDATOR] START index=8122
[VALIDATOR] START index=8973
[VALIDATOR] START index=8486
[VALIDATOR] START index=8123
[VALIDATOR] START index=8974
[VALIDATOR] START index=8975
[VALIDATOR] START index=8124
[VALIDATOR] START index=8976
[VALIDATOR] START index=8125
[VALIDATOR] START index=8977
[VALIDATOR] START index=8126
[VALIDATOR] START index=8978
[VALIDATOR] START index=8127
[VALIDATOR] START index=8487
[VALIDATOR] START index=8979
[VALIDATOR] START index=8128
[VALIDATOR] START index=8980
[VALIDATOR] START index=8129
[VALIDATOR] START index=8981
[VALIDATOR] START index=8130
[VALIDATOR] START index=8982
[VALIDATOR] START index=8131
[VALIDATOR] START index=8983
[VALIDATOR] START index=8132
[VALIDATOR] START index=8984
[VALIDATOR] START index=8133
[VALIDATOR] START index=8985
[VALIDATOR] START index=8488
[VALIDATOR] START index=8134
[VALIDATOR] START index=8986
[VALIDATOR] START index=8135
[VALIDATOR] START index=8489
[VALIDATOR] START index=8987
[VALIDATOR] START index=8136
[VALIDATOR] START index=8988
[VALIDATOR] START index=8137
[VALIDATOR] START index=8989
[VALIDATOR] START index=8138
[VALIDATOR] START index=8990
[VALIDATOR] START index=8139
[VALIDATOR] START index=8991
[VALIDATOR] START index=8140
[VALIDATOR] START index=8992
[VALIDATOR] START index=8141
[VALIDATOR] START index=8993
[VALIDATOR] START index=8490
[VALIDATOR] START index=8142
[VALIDATOR] START index=8994
[VALIDATOR] START index=8143
[VALIDATOR] START index=8995
[VALIDATOR] START index=8144
[VALIDATOR] START index=8996
[VALIDATOR] START index=8145
[VALIDATOR] START index=8997
[VALIDATOR] START index=8146
[VALIDATOR] START index=8998
[VALIDATOR] START index=8147
[VALIDATOR] START index=8491
[VALIDATOR] START index=8999
[VALIDATOR] START index=8148
[VALIDATOR] START index=9000
[VALIDATOR] START index=8149
[VALIDATOR] START index=9001
[VALIDATOR] START index=8150
[VALIDATOR] START index=9002
[VALIDATOR] START index=8151
[VALIDATOR] START index=9003
[VALIDATOR] START index=8152
[VALIDATOR] START index=9004
[VALIDATOR] START index=8492
[VALIDATOR] START index=8153
[VALIDATOR] START index=9005
[VALIDATOR] START index=8154
[VALIDATOR] START index=9006
[VALIDATOR] START index=8155
[VALIDATOR] START index=9007
[VALIDATOR] START index=8156
[VALIDATOR] START index=9008
[VALIDATOR] START index=8157
[VALIDATOR] START index=9009
[VALIDATOR] START index=8158
[VALIDATOR] START index=9010
[VALIDATOR] START index=8493
[VALIDATOR] START index=8159
[VALIDATOR] START index=9011
[VALIDATOR] START index=8494
[VALIDATOR] START index=8160
[VALIDATOR] START index=9012
[VALIDATOR] START index=8495
[VALIDATOR] START index=8161
[VALIDATOR] START index=9013
[VALIDATOR] START index=8496
[VALIDATOR] START index=8162
[VALIDATOR] START index=9014
[VALIDATOR] START index=8163
[VALIDATOR] START index=9015
[VALIDATOR] START index=8164
[VALIDATOR] START index=9016
[VALIDATOR] START index=8165
[VALIDATOR] START index=9017
[VALIDATOR] START index=8166
[VALIDATOR] START index=9018
[VALIDATOR] START index=8167
[VALIDATOR] START index=9019
[VALIDATOR] START index=8168
[VALIDATOR] START index=8497
[VALIDATOR] START index=9020
[VALIDATOR] START index=8498
[VALIDATOR] START index=8169
[VALIDATOR] START index=9021
[VALIDATOR] START index=8170
[VALIDATOR] START index=8499
[VALIDATOR] START index=9022
[VALIDATOR] START index=8171
[VALIDATOR] START index=9023
[VALIDATOR] START index=8172
[VALIDATOR] START index=9024
[VALIDATOR] START index=8173
[VALIDATOR] START index=9025
[VALIDATOR] START index=8174
[VALIDATOR] START index=9026
[VALIDATOR] START index=8175
[VALIDATOR] START index=9027
[VALIDATOR] START index=8500
[VALIDATOR] START index=8176
[VALIDATOR] START index=9028
[VALIDATOR] START index=8501
[VALIDATOR] START index=9029
[VALIDATOR] START index=8177
[VALIDATOR] START index=9030
[VALIDATOR] START index=8178
[VALIDATOR] START index=9031
[VALIDATOR] START index=8179
[VALIDATOR] START index=9032
[VALIDATOR] START index=8180
[VALIDATOR] START index=9033
[VALIDATOR] START index=8181
[VALIDATOR] START index=9034
[VALIDATOR] START index=8502
[VALIDATOR] START index=8182
[VALIDATOR] START index=9035

 95%|█████████▌| 38/40 [28:04<02:14, 67.28s/it]

[VALIDATOR] START index=9036
[VALIDATOR] START index=9037
[VALIDATOR] START index=9038
[VALIDATOR] START index=9039
[VALIDATOR] START index=9040
[VALIDATOR] START index=9041
[VALIDATOR] START index=8503
[VALIDATOR] START index=9042
[VALIDATOR] START index=8504
[VALIDATOR] START index=9043
[VALIDATOR] START index=8505
[VALIDATOR] START index=9044
[VALIDATOR] START index=9045
[VALIDATOR] START index=9046
[VALIDATOR] START index=9047
[VALIDATOR] START index=9048
[VALIDATOR] START index=9049
[VALIDATOR] START index=9050
[VALIDATOR] START index=9051
[VALIDATOR] START index=8506
[VALIDATOR] START index=9052
[VALIDATOR] START index=9053
[VALIDATOR] START index=9054
[VALIDATOR] START index=9055
[VALIDATOR] START index=9056
[VALIDATOR] START index=9057
[VALIDATOR] START index=9058
[VALIDATOR] START index=9059
[VALIDATOR] START index=8507
[VALIDATOR] START index=9060
[VALIDATOR] START index=9061
[VALIDATOR] START index=9062
[VALIDATOR] START index=9063
[VALIDATOR] START index=9064
[VALIDATOR] START index=9065
[VALIDATOR] START index=9066
[VALIDATOR] START index=9067
[VALIDATOR] START index=9068
[VALIDATOR] START index=8508
[VALIDATOR] START index=9069
[VALIDATOR] START index=8509
[VALIDATOR] START index=9070
[VALIDATOR] START index=9071
[VALIDATOR] START index=9072
[VALIDATOR] START index=9073
[VALIDATOR] START index=9074
[VALIDATOR] START index=9075
[VALIDATOR] START index=9076
[VALIDATOR] START index=9077
[VALIDATOR] START index=8510
[VALIDATOR] START index=9078
[VALIDATOR] START index=8511
[VALIDATOR] START index=9079
[VALIDATOR] START index=9080
[VALIDATOR] START index=9081
[VALIDATOR] START index=9082
[VALIDATOR] START index=9083
[VALIDATOR] START index=9084
[VALIDATOR] START index=9085
[VALIDATOR] START index=9086
[VALIDATOR] START index=8512
[VALIDATOR] START index=9087
[VALIDATOR] START index=8513
[VALIDATOR] START index=9088
[VALIDATOR] START index=8514
[VALIDATOR] START index=9089
[VALIDATOR] START index=9090
[VALIDATOR] START index=9091
[VALIDATOR] START index=9092
[VALIDATOR] START index=9093
[VALIDATOR] START index=9094
[VALIDATOR] START index=9095
[VALIDATOR] START index=9096
[VALIDATOR] START index=8515
[VALIDATOR] START index=9097
[VALIDATOR] START index=8516
[VALIDATOR] START index=9098
[VALIDATOR] START index=9099
[VALIDATOR] START index=9100
[VALIDATOR] START index=9101
[VALIDATOR] START index=9102
[VALIDATOR] START index=9103
[VALIDATOR] START index=9104
[VALIDATOR] START index=9105
[VALIDATOR] START index=8517
[VALIDATOR] START index=9106
[VALIDATOR] START index=9107
[VALIDATOR] START index=9108
[VALIDATOR] START index=9109
[VALIDATOR] START index=9110
[VALIDATOR] START index=9111
[VALIDATOR] START index=9112
[VALIDATOR] START index=9113
[VALIDATOR] START index=9114
[VALIDATOR] START index=8518
[VALIDATOR] START index=9115
[VALIDATOR] START index=8519
[VALIDATOR] START index=9116
[VALIDATOR] START index=9117
[VALIDATOR] START index=9118
[VALIDATOR] START index=9119
[VALIDATOR] START index=9120
[VALIDATOR] START index=9121
[VALIDATOR] START index=9122
[VALIDATOR] START index=9123
[VALIDATOR] START index=8520
[VALIDATOR] START index=9124
[VALIDATOR] START index=9125
[VALIDATOR] START index=9126
[VALIDATOR] START index=9127
[VALIDATOR] START index=9128
[VALIDATOR] START index=9129
[VALIDATOR] START index=9130
[VALIDATOR] START index=9131
[VALIDATOR] START index=8521
[VALIDATOR] START index=9132
[VALIDATOR] START index=8522
[VALIDATOR] START index=9133
[VALIDATOR] START index=8523
[VALIDATOR] START index=9134
[VALIDATOR] START index=8524
[VALIDATOR] START index=9135
[VALIDATOR] START index=8525
[VALIDATOR] START index=9136
[VALIDATOR] START index=9137
[VALIDATOR] START index=9138
[VALIDATOR] START index=9139
[VALIDATOR] START index=9140
[VALIDATOR] START index=9141
[VALIDATOR] START index=9142
[VALIDATOR] START index=9143
[VALIDATOR] START index=9144
[VALIDATOR] START index=8526
[VALIDATOR] START index=9145
[VALIDATOR] START index=9146
[VALIDATOR] START index=9147

 98%|█████████▊| 39/40 [30:22<01:28, 88.60s/it]

[VALIDATOR] START index=8527
[VALIDATOR] START index=8528
[VALIDATOR] START index=8529
[VALIDATOR] START index=8530
[VALIDATOR] START index=8531
[VALIDATOR] START index=8532
[VALIDATOR] START index=8533
[VALIDATOR] START index=8534
[VALIDATOR] START index=8535
[VALIDATOR] START index=8536
[VALIDATOR] START index=8537
[VALIDATOR] START index=8538
[VALIDATOR] START index=8539
[VALIDATOR] START index=8540
[VALIDATOR] START index=8541
[VALIDATOR] START index=8542
[VALIDATOR] START index=8543
[VALIDATOR] START index=8544
[VALIDATOR] START index=8545
[VALIDATOR] START index=8546
[VALIDATOR] START index=8547
[VALIDATOR] START index=8548
[VALIDATOR] START index=8549
[VALIDATOR] START index=8550
[VALIDATOR] START index=8551
[VALIDATOR] START index=8552
[VALIDATOR] START index=8553
[VALIDATOR] START index=8554
[VALIDATOR] START index=8555
[VALIDATOR] START index=8556
[VALIDATOR] START index=8557
[VALIDATOR] START index=8558
[VALIDATOR] START index=8559
[VALIDATOR] START index=8560
[VALIDATOR] START index=8561
[VALIDATOR] START index=8562
[VALIDATOR] START index=8563
[VALIDATOR] START index=8564
[VALIDATOR] START index=8565
[VALIDATOR] START index=8566
[VALIDATOR] START index=8567
[VALIDATOR] START index=8568
[VALIDATOR] START index=8569
[VALIDATOR] START index=8570
[VALIDATOR] START index=8571
[VALIDATOR] START index=8572
[VALIDATOR] START index=8573
[VALIDATOR] START index=8574
[VALIDATOR] START index=8575
[VALIDATOR] START index=8576
[VALIDATOR] START index=8577
[VALIDATOR] START index=8578
[VALIDATOR] START index=8579
[VALIDATOR] START index=8580
[VALIDATOR] START index=8581
[VALIDATOR] START index=8582
[VALIDATOR] START index=8583
[VALIDATOR] START index=8584
[VALIDATOR] START index=8585
[VALIDATOR] START index=8586
[VALIDATOR] START index=8587
[VALIDATOR] START index=8588
[VALIDATOR] START index=8589
[VALIDATOR] START index=8590
[VALIDATOR] START index=8591
[VALIDATOR] START index=8592
[VALIDATOR] START index=8593
[VALIDATOR] START index=8594
[VALIDATOR] START index=8595
[VALIDATOR] START index=8596
[VALIDATOR] START index=8597
[VALIDATOR] START index=8598
[VALIDATOR] START index=8599
[VALIDATOR] START index=8600
[VALIDATOR] START index=8601
[VALIDATOR] START index=8602
[VALIDATOR] START index=8603
[VALIDATOR] START index=8604
[VALIDATOR] START index=8605
[VALIDATOR] START index=8606
[VALIDATOR] START index=8607
[VALIDATOR] START index=8608
[VALIDATOR] START index=8609
[VALIDATOR] START index=8610
[VALIDATOR] START index=8611
[VALIDATOR] START index=8612
[VALIDATOR] START index=8613
[VALIDATOR] START index=8614
[VALIDATOR] START index=8615
[VALIDATOR] START index=8616
[VALIDATOR] START index=8617
[VALIDATOR] START index=8618
[VALIDATOR] START index=8619
[VALIDATOR] START index=8620
[VALIDATOR] START index=8621
[VALIDATOR] START index=8622
[VALIDATOR] START index=8623
[VALIDATOR] START index=8624
[VALIDATOR] START index=8625
[VALIDATOR] START index=8626
[VALIDATOR] START index=8627
[VALIDATOR] START index=8628
[VALIDATOR] START index=8629
[VALIDATOR] START index=8630
[VALIDATOR] START index=8631
[VALIDATOR] START index=8632
[VALIDATOR] START index=8633
[VALIDATOR] START index=8634
[VALIDATOR] START index=8635
[VALIDATOR] START index=8636
[VALIDATOR] START index=8637
[VALIDATOR] START index=8638
[VALIDATOR] START index=8639
[VALIDATOR] START index=8640
[VALIDATOR] START index=8641
[VALIDATOR] START index=8642
[VALIDATOR] START index=8643
[VALIDATOR] START index=8644
[VALIDATOR] START index=8645
[VALIDATOR] START index=8646
[VALIDATOR] START index=8647
[VALIDATOR] START index=8648
[VALIDATOR] START index=8649
[VALIDATOR] START index=8650
[VALIDATOR] START index=8651
[VALIDATOR] START index=8652
[VALIDATOR] START index=8653
[VALIDATOR] START index=8654
[VALIDATOR] START index=8655
[VALIDATOR] START index=8656
[VALIDATOR] START index=8657
[VALIDATOR] START index=8658
[VALIDATOR] START index=8659
[VALIDATOR] START index=8660
[VALIDATOR] START index=8661
[VALIDATOR] START index=8662
[VALIDATOR] START index=8663
[VALIDATOR] START index=8664
[VALIDATOR] START index=8665
[VALIDATOR] START index=8666
[VALIDATOR] START index=8667
[VALIDATOR] START index=8668
[VALIDATOR] START index=8669
[VALIDATOR] START index=8670
[VALIDATOR] START index=8671
[VALIDATOR] START index=8672
[VALIDATOR] START index=8673
[VALIDATOR] START index=8674
[VALIDATOR] START index=8675
[VALIDATOR] START index=8676
[VALIDATOR] START index=8677
[VALIDATOR] START index=8678
[VALIDATOR] START index=8679
[VALIDATOR] START index=8680
[VALIDATOR] START index=8681
[VALIDATOR] START index=8682
[VALIDATOR] START index=8683
[VALIDATOR] START index=8684
[VALIDATOR] START index=8685
[VALIDATOR] START index=8686

100%|██████████| 40/40 [44:08<00:00, 66.22s/it]

===== PLAUSIBLE =====
bugid
bitcount                       True
breadth_first_search           True
bucketsort                    False
depth_first_search             True
detect_cycle                   True
find_first_in_sorted           True
find_in_sorted                 True
flatten                        True
gcd                           False
get_factors                    True
hanoi                          True
is_valid_parenthesization      True
kheapsort                      True
knapsack                       True
kth                           False
lcs_length                     True
levenshtein                    True
lis                            True
longest_common_subsequence     True
max_sublist_sum               False
mergesort                      True
minimum_spanning_tree          True
next_palindrome                True
next_permutation               True
pascal                         True
possible_change                True
powerset                      False
quicksort                      True
reverse_linked_list            True
rpn_eval                       True
shortest_path_length          False
shortest_path_lengths         False
shortest_paths                False
shunting_yard                 False
sieve                          True
sqrt                          False
subsequences                   True
to_base                       False
topological_ordering           True
wrap                           True
Name: plausible, dtype: bool
plausible
True     29
False    11
Name: count, dtype: int64

===== CORRECT =====
bugid
bitcount                       True
breadth_first_search           True
bucketsort                    False
depth_first_search             True
detect_cycle                   True
find_first_in_sorted           True
find_in_sorted                 True
flatten                        True
gcd                           False
get_factors                    True
hanoi                          True
is_valid_parenthesization      True
kheapsort                      True
knapsack                       True
kth                           False
lcs_length                     True
levenshtein                    True
lis                           False
longest_common_subsequence     True
max_sublist_sum               False
mergesort                      True
minimum_spanning_tree          True
next_palindrome               False
next_permutation               True
pascal                         True
possible_change                True
powerset                      False
quicksort                      True
reverse_linked_list            True
rpn_eval                       True
shortest_path_length          False
shortest_path_lengths         False
shortest_paths                False
shunting_yard                 False
sieve                          True
sqrt                          False
subsequences                   True
to_base                       False
topological_ordering           True
wrap                           True
Name: correct, dtype: bool
correct
True     27
False    13
Name: count, dtype: int64

fixed_rag: validation complete
Output: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/outputs-multimend-fixed_rag/plausible_candidates_100.jsonl
Columns verified: plausible, correct

In [74]:
# Cell 8 â€” Produce metrics required by the Stage 1 plan
import json
import pandas as pd

def load_jsonl(path):
    return pd.read_json(path, orient="records", lines=True)

def bug_success_at_k(frame, column, k):
    eligible = frame[frame["rank"] < k]
    per_hunk = eligible.groupby(["bugid", "hunk"])[column].any()
    return per_hunk.groupby(level=0).all()

def summarize(strategy):
    base = output_root / f"outputs-multimend-{strategy}"
    candidates = load_jsonl(base / "final_candidates_100.jsonl")
    validated = load_jsonl(base / "plausible_candidates_100.jsonl")
    if "rank" not in validated:
        raise ValueError(f"{strategy}: validator output has no rank column")
    if "exact_match" not in validated:
        validated["exact_match"] = False
    validated["exact_match"] = validated["exact_match"].fillna(False)
    if "correct" not in validated:
        validated["correct"] = False
    validated["correct"] = validated["correct"].fillna(False)
    validated["plausible"] = validated["plausible"].fillna(False)
    bugs = int(validated["bugid"].nunique())
    plausible_bugs = bug_success_at_k(validated, "plausible", 10**9)
    exact_bugs = bug_success_at_k(validated, "exact_match", 10**9)
    context_path = base / f"context_log_{strategy}.jsonl"
    context = load_jsonl(context_path) if context_path.exists() else pd.DataFrame()
    context_count = len(context)
    return {
        "strategy": strategy,
        "bugs": bugs,
        "hunks": int(validated[["bugid", "hunk"]].drop_duplicates().shape[0]),
       # "raw_candidates": int(load_jsonl(base / "sequences_100.jsonl").shape[0]),
        "final_candidates": int(candidates.shape[0]),
        "correct_at_1": int(bug_success_at_k(validated, "correct", 1).sum()),
        "correct_at_10": int(bug_success_at_k(validated, "correct", 10).sum()),
        "correct_at_100": int(bug_success_at_k(validated, "correct", 100).sum()),
        "plausible_at_1": int(bug_success_at_k(validated, "plausible", 1).sum()),
        "plausible_at_10": int(bug_success_at_k(validated, "plausible", 10).sum()),
        "plausible_at_100": int(bug_success_at_k(validated, "plausible", 100).sum()),
        "correct_bugs": int(bug_success_at_k(validated, "correct", 10**9).sum()),
        "plausible_bugs": int(plausible_bugs.sum()),
        "exact_match_bugs": int(exact_bugs.sum()),
        #"truncated_inputs": int(context["was_truncated"].sum()) if context_count else 0,
       # "truncate_percent": round(100 * float(context["was_truncated"].sum()) / context_count, 4) if context_count else 0.0,
        "retrieved_contexts": int((context["retrieved_count"] > 0).sum()) if context_count else 0,
        "local_context_at_risk": int(context["local_context_at_risk"].sum()) if context_count else 0,
       # "context_records": context_count,
    }

summary = pd.DataFrame([summarize("no_rag"), summarize("fixed_rag")])
for metric in ("correct_at_1", "correct_at_10", "correct_at_100", "correct_bugs", "plausible_bugs", "exact_match_bugs"):
    summary[f"{metric}_rate"] = summary[metric] / summary["bugs"]

def case_status(strategy):
    frame = load_jsonl(output_root / f"outputs-multimend-{strategy}" / "plausible_candidates_100.jsonl")
    frame["plausible"] = frame["plausible"].fillna(False)
    return frame.groupby(["bugid", "hunk"])["plausible"].any()

b0_status = case_status("no_rag")
b1_status = case_status("fixed_rag")
cases = pd.concat([b0_status.rename("b0_plausible"), b1_status.rename("b1_plausible")], axis=1).fillna(False)
cases["classification"] = "unchanged"
cases.loc[~cases.b0_plausible & cases.b1_plausible, "classification"] = "rag_helped"
cases.loc[cases.b0_plausible & ~cases.b1_plausible, "classification"] = "rag_harmed"
cases.reset_index().to_json(output_root / "stage1_rag_case_comparison.jsonl", orient="records", lines=True)
case_counts = cases["classification"].value_counts().to_dict()

summary_path = output_root / "stage1_b0_b1_comparison.json"
summary.to_json(summary_path, orient="records", indent=2)
(output_root / "stage1_rag_case_counts.json").write_text(json.dumps(case_counts, indent=2), encoding="utf-8")
display(summary)
print("RAG case counts:", case_counts)
print("Saved:", summary_path)

,strategy,bugs,hunks,final_candidates,correct_at_1,correct_at_10,correct_at_100,plausible_at_1,plausible_at_10,plausible_at_100,...,plausible_bugs,exact_match_bugs,retrieved_contexts,local_context_at_risk,correct_at_1_rate,correct_at_10_rate,correct_at_100_rate,correct_bugs_rate,plausible_bugs_rate,exact_match_bugs_rate
0,no_rag,40,40,9709,5,16,27,7,21,29,...,29,27,0,0,0.125,0.400,0.675,0.675,0.725,0.675
1,fixed_rag,40,40,9667,5,15,27,7,20,29,...,29,27,0,0,0.125,0.375,0.675,0.675,0.725,0.675

RAG case counts: {'unchanged': 40}
Saved: /kaggle/working/MultiMend28/outputs/QuixBugs-Python/stage1_b0_b1_comparison.json

In [73]:
# Time-to-repair and GPU-plan report
import os
from pathlib import Path
import pandas as pd

def _time_to_first(frame, flag):
    work = frame.copy()
    if "validation_time" not in work:
        return pd.Series(dtype="float64")
    work["validation_time"] = pd.to_numeric(work["validation_time"], errors="coerce").fillna(0.0)
    work = work.sort_values(["bugid", "rank"])
    work["elapsed_seconds"] = work.groupby("bugid")["validation_time"].cumsum()
    return work[work[flag].fillna(False).astype(bool)].groupby("bugid")["elapsed_seconds"].min()

def _time_stats(values, name):
    values = pd.to_numeric(values, errors="coerce").dropna()
    if values.empty:
        return {f"{name}_seconds_{k}": None for k in ("min", "max", "median", "mean")}
    return {f"{name}_seconds_{k}": round(float(getattr(values, k)()), 4) for k in ("min", "max", "median", "mean")}

def _gpu_plan():
    path = Path(os.environ.get("MULTIMEND_PLAN_XLSX", "MultiMend_ke_hoach_2026-10-04_2026-10-11.xls.xlsx"))
    if not path.exists():
        raise FileNotFoundError(f"GPU plan workbook not found: {path}")
    import openpyxl
    book = openpyxl.load_workbook(path, read_only=True, data_only=True)
    rows = list(book["2_Thuc_hien_giai_doan"].iter_rows(min_row=3, values_only=True))
    gpu_count = max(float(row[3]) for row in rows if row[3] is not None)
    return {"plan_file": str(path), "planned_sessions": len(rows), "planned_gpu_count": int(gpu_count), "planned_slot_hours": 12.0, "planned_gpu_hours": len(rows) * 12.0 * gpu_count}

reports = []
for strategy in ("no_rag", "fixed_rag"):
    base = output_root / f"outputs-multimend-{strategy}"
    frame = pd.read_json(base / "plausible_candidates_100.jsonl", orient="records", lines=True)
    frame["correct"] = frame["correct"].fillna(False).astype(bool)
    frame["plausible"] = frame["plausible"].fillna(False).astype(bool)
    row = {"strategy": strategy, "bugs": int(frame["bugid"].nunique()), "validation_records": int(len(frame))}
    row.update(_time_stats(_time_to_first(frame, "correct"), "time_to_correct"))
    row.update(_time_stats(_time_to_first(frame, "plausible"), "time_to_plausible"))
    row["validation_seconds_total"] = round(float(pd.to_numeric(frame["validation_time"], errors="coerce").sum()), 4)
    reports.append(row)
report = pd.DataFrame(reports)
for key, value in _gpu_plan().items():
    report[key] = value
report["gpu_hours_observed"] = pd.to_numeric(os.environ.get("MULTIMEND_GPU_HOURS"), errors="coerce")
report["gpu_hours_note"] = "planned capacity, not consumed usage"
report.to_json(output_root / "stage1_time_gpu_metrics.json", orient="records", indent=2)
display(report)

,strategy,bugs,validation_records,time_to_correct_seconds_min,time_to_correct_seconds_max,time_to_correct_seconds_median,time_to_correct_seconds_mean,time_to_plausible_seconds_min,time_to_plausible_seconds_max,time_to_plausible_seconds_median,time_to_plausible_seconds_mean,validation_seconds_total,plan_file,planned_sessions,planned_gpu_count,planned_slot_hours,planned_gpu_hours,gpu_hours_observed,gpu_hours_note
0,no_rag,40,9709,5.7027,741.8266,28.5952,80.3834,5.7027,741.8266,28.5952,76.7066,10443.8707,MultiMend_ke_hoach_2026-10-04_2026-10-11.xls.xlsx,16,30,12.0,5760.0,NaN,"planned capacity, not consumed usage"
1,fixed_rag,40,9667,5.4090,740.6907,35.5343,87.5021,5.4090,740.6907,35.5343,83.1393,10521.7609,MultiMend_ke_hoach_2026-10-04_2026-10-11.xls.xlsx,16,30,12.0,5760.0,NaN,"planned capacity, not consumed usage"

In [75]:
# Cell 9 — Final reproducibility checks and artifact manifest

import hashlib
import json
import subprocess
from datetime import datetime, timezone

def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


run_started_at = datetime.now(timezone.utc).isoformat()
artifact_manifest = {}

SKIPPED_PROGRAMS = {
    "detect_cycle_test",
    "shortest_path_length_test",
}

for strategy in ("no_rag", "fixed_rag"):
    directory = output_root / f"outputs-multimend-{strategy}"

    required = [
        directory / "generated_input.jsonl",
        directory / "sequences_100.jsonl",
        directory / "final_candidates_100.jsonl",
        directory / "plausible_candidates_100.jsonl",
    ]

    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise FileNotFoundError(
            f"{strategy} incomplete: {missing}"
        )

    # ---------------------------------------------------------
    # Load raw candidates.
    # load_jsonl() returns a pandas DataFrame.
    # ---------------------------------------------------------
    raw = load_jsonl(
        directory / "sequences_100.jsonl"
    )

    if raw.empty:
        raise RuntimeError(
            f"{strategy}: sequences_100.jsonl is empty"
        )

    # ---------------------------------------------------------
    # Check columns.
    # ---------------------------------------------------------
    required_raw_columns = {"bugid", "hunk"}
    missing_raw_columns = (
        required_raw_columns - set(raw.columns)
    )

    if missing_raw_columns:
        raise RuntimeError(
            f"{strategy}: raw output missing columns: "
            f"{sorted(missing_raw_columns)}"
        )

    # ---------------------------------------------------------
    # Count actual bugs/hunks.
    # Two programs are intentionally skipped.
    # ---------------------------------------------------------
    raw_bugids = set(raw["bugid"].dropna().unique())

    unexpected_skipped = (
        SKIPPED_PROGRAMS & raw_bugids
    )

    if unexpected_skipped:
        raise RuntimeError(
            f"{strategy}: skipped programs unexpectedly appear "
            f"in sequences_100.jsonl: "
            f"{sorted(unexpected_skipped)}"
        )

    hunk_keys = raw[
        ["bugid", "hunk"]
    ].drop_duplicates()

    expected_hunks = len(hunk_keys)
    expected_records = expected_hunks * 5 * 100

    print("=" * 70)
    print(strategy)
    print(f"bugs        : {len(raw_bugids)}")
    print(f"hunks       : {expected_hunks}")
    print(f"raw records : {len(raw)}")
    print(f"expected    : {expected_records}")
    print("=" * 70)

    if len(raw) != expected_records:
        raise RuntimeError(
            f"{strategy}: expected {expected_records} raw records "
            f"for {expected_hunks} hunks, found {len(raw)}"
        )

    # ---------------------------------------------------------
    # Verify validation output.
    # ---------------------------------------------------------
    validated = load_jsonl(
        directory / "plausible_candidates_100.jsonl"
    )

    if validated.empty:
        raise RuntimeError(
            f"{strategy}: plausible_candidates_100.jsonl is empty"
        )

    required_validation_columns = {
        "plausible",
        "correct",
    }

    missing_columns = (
        required_validation_columns
        - set(validated.columns)
    )

    if missing_columns:
        raise RuntimeError(
            f"{strategy}: validation output missing columns: "
            f"{sorted(missing_columns)}"
        )

    artifact_manifest[strategy] = {
        "status": "complete",
        "bugs": len(raw_bugids),
        "hunks": expected_hunks,
        "raw_records": len(raw),
        "validation_records": len(validated),
        "skipped_programs": sorted(SKIPPED_PROGRAMS),
        "files": {
            path.name: sha256(path)
            for path in required
        },
    }


manifest = {
    "stage": 1,
    "dataset": "QuixBugs-Python",
    "strategies": [
        "no_rag",
        "fixed_rag",
    ],
    "seed": 42,
    "num_checkpoints": 5,
    "num_return_sequences": 100,
    "skipped_programs": sorted(SKIPPED_PROGRAMS),
    "rag": {
        "top_k": 5,
        "distance_threshold": 0.5,
    },
    "git_commit": subprocess.check_output(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO,
        text=True,
    ).strip(),
    "run_started_at": run_started_at,
    "run_finished_at": datetime.now(timezone.utc).isoformat(),
    "artifacts": artifact_manifest,
    "comparison_file": str(summary_path),
}


(output_root / "stage1_manifest.json").write_text(
    json.dumps(manifest, indent=2),
    encoding="utf-8",
)

print(json.dumps(manifest, indent=2))
print("STAGE 1 — B0/B1 COMPLETE")

======================================================================
no_rag
bugs        : 40
hunks       : 40
raw records : 20000
expected    : 20000
======================================================================
======================================================================
fixed_rag
bugs        : 40
hunks       : 40
raw records : 20000
expected    : 20000
======================================================================
{
  "stage": 1,
  "dataset": "QuixBugs-Python",
  "strategies": [
    "no_rag",
    "fixed_rag"
  ],
  "seed": 42,
  "num_checkpoints": 5,
  "num_return_sequences": 100,
  "skipped_programs": [
    "detect_cycle_test",
    "shortest_path_length_test"
  ],
  "rag": {
    "top_k": 5,
    "distance_threshold": 0.5
  },
  "git_commit": "08c0c75f5331f54616a083267e501f21713c6047",
  "run_started_at": "2026-10-07T15:37:21.340203+00:00",
  "run_finished_at": "2026-10-07T15:37:21.781929+00:00",
  "artifacts": {
    "no_rag": {
      "status": "complete",
      "bugs": 40,
      "hunks": 40,
      "raw_records": 20000,
      "validation_records": 9709,
      "skipped_programs": [
        "detect_cycle_test",
        "shortest_path_length_test"
      ],
      "files": {
        "generated_input.jsonl": "1a61343616821b865f5c5d0c73bd35943976297d9f484cde5231238ef007ab6c",
        "sequences_100.jsonl": "bb60e76ec226b16247c748c311dba0fd382e81a86b374b814262b5242955f594",
        "final_candidates_100.jsonl": "3763280ab4489c67576b214f82ee582c8deb28807a01857e66120c465fd4170c",
        "plausible_candidates_100.jsonl": "100abb02eec0b5674baee5f3cf07d703a28877fa7dafbffa228a16aff2c7cdbe"
      }
    },
    "fixed_rag": {
      "status": "complete",
      "bugs": 40,
      "hunks": 40,
      "raw_records": 20000,
      "validation_records": 9667,
      "skipped_programs": [
        "detect_cycle_test",
        "shortest_path_length_test"
      ],
      "files": {
        "generated_input.jsonl": "b4c71bc93055ccb17f10b3ccb25797bc3b562ae04963837787b143ce2ce6e3e2",
        "sequences_100.jsonl": "ca24bfb0ad956c5b53b6167d719f73b509cabce96aa05b22670827f7327d2bda",
        "final_candidates_100.jsonl": "7dcb659ed981246206cb49e4783b9b5879050e160cf740f765fb4006e537a356",
        "plausible_candidates_100.jsonl": "c7e5eeb6a05cdacca0d7d5db5c2ecb1fb73649362389dd9af4da98b501bf9ff2"
      }
    }
  },
  "comparison_file": "/kaggle/working/MultiMend28/outputs/QuixBugs-Python/stage1_b0_b1_comparison.json"
}
STAGE 1 — B0/B1 COMPLETE

Giai đoạn 0:

In [ ]:
# Cell 1 — Kaggle environment
import os, sys, subprocess, textwrap, json, pathlib, shutil, time
from pathlib import Path

print("Python:", sys.version)
print("CUDA_VISIBLE_DEVICES:", os.environ.get("CUDA_VISIBLE_DEVICES"))
try:
    import torch
    print("Torch:", torch.__version__)
    print("CUDA available:", torch.cuda.is_available())
    if torch.cuda.is_available():
        print("GPU:", torch.cuda.get_device_name(0))
except Exception as e:
    print("Torch import error:", repr(e))

In [ ]:
# Cell 2 — Clone ONLY the MultiMend repo first.
# We intentionally do not recurse through all benchmark submodules yet.

REPO = Path("/kaggle/working/MultiMend")
if REPO.exists():
    print("Repo already exists:", REPO)
else:
    subprocess.run([
        "git", "clone", "--depth", "1",
        "https://github.com/h4iku/MultiMend.git",
        str(REPO)
    ], check=True)

os.chdir(REPO)
print("HEAD:", subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip())
print("Repo:", REPO)
print("Top-level:", [p.name for p in REPO.iterdir()])

In [ ]:
# Cell 3 — Inspect the official repo BEFORE running anything
from pathlib import Path

for p in sorted((REPO / "src").rglob("*.py")):
    print(p.relative_to(REPO))

print("\nrequirements.txt:")
print((REPO / "requirements.txt").read_text())

## Important implementation findings

The official generation script uses:

- `max_input_length = 512`
- `max_target_length = 256`
- `beam_size = 100`
- `num_return_sequences = 100`
- `batch_size = 1`
- `num_checkpoints = 5`

It loads the last five `checkpoint-*` directories under `models/multimend-codet5-small`, generates from every checkpoint, and writes `sequences_100.jsonl`.

The context augmentation is local RAG: `all-MiniLM-L6-v2` + persistent ChromaDB, not a paid LLM API.

In [ ]:
# Cell 4 — Install official MultiMend dependencies.
# Do NOT upgrade unrelated Kaggle packages.

import subprocess
import sys

result = subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "--no-cache-dir",
        "-r",
        "requirements.txt",
        "more-itertools",
        "pygments",
    ],
    text=True,
)

if result.returncode != 0:
    raise RuntimeError("MultiMend dependency installation failed.")

print("MultiMend dependency installation complete.")

In [ ]:
# Cell 4b — Force the versions required by MultiMend
import subprocess
import sys

packages = [
    "numpy==1.26.4",
    "pandas==2.2.3",
    "torch==2.4.0",
]

subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "--no-cache-dir",
        "--force-reinstall",
        *packages,
    ],
    check=True,
)

print("Pinned NumPy/Pandas/Torch versions installed.")

In [ ]:
# Cell 4c — Match torchvision with MultiMend's torch 2.4.0

import subprocess
import sys

subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "--no-cache-dir",
        "--force-reinstall",
        "torchvision==0.19.0",
    ],
    check=True,
)

print("torchvision 0.19.0 installed.")

In [ ]:
# Fix NumPy for ChromaDB 0.5.5 / MultiMend
import subprocess
import sys

subprocess.run(
    [
        sys.executable,
        "-m", "pip", "install",
        "-q",
        "--no-cache-dir",
        "--force-reinstall",
        "numpy==1.26.4",
    ],
    check=True,
)

print("NumPy 1.26.4 installed.")

In [ ]:
import numpy as np

print("NumPy:", np.__version__)

In [2]:
import torch
import transformers
import datasets
import chromadb
import sentence_transformers
import tree_sitter
import unidiff
import more_itertools
import pygments

print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("chromadb:", chromadb.__version__)
print("sentence-transformers:", sentence_transformers.__version__)
print("tree-sitter:", tree_sitter.__version__ if hasattr(tree_sitter, "__version__") else "unknown")
print("CUDA:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

torch: 2.4.0+cu121
transformers: 4.44.2
datasets: 2.21.0
chromadb: 0.5.5
sentence-transformers: 3.0.1
tree-sitter: unknown
CUDA: True
GPU: Tesla T4

In [3]:
# Cell 5 — Verify versions and direct imports
import torch, transformers, datasets, chromadb, sentence_transformers
import tree_sitter, unidiff, more_itertools, pygments

print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("chromadb:", chromadb.__version__)
print("sentence-transformers:", sentence_transformers.__version__)
print("tree-sitter:", tree_sitter.__version__ if hasattr(tree_sitter, "__version__") else "unknown")
print("CUDA:", torch.cuda.is_available())

torch: 2.4.0+cu121
transformers: 4.44.2
datasets: 2.21.0
chromadb: 0.5.5
sentence-transformers: 3.0.1
tree-sitter: unknown
CUDA: True

In [ ]:
from pathlib import Path

REPO = Path("/kaggle/working/MultiMend")

print("Repo exists:", REPO.exists())
print("Repo:", REPO)

if REPO.exists():
    print("Contents:")
    for p in list(REPO.iterdir())[:20]:
        print(" -", p.name)

In [ ]:
# Cell 6 — Download QuixBugs

from pathlib import Path
import subprocess
import shutil

REPO = Path("/kaggle/working/MultiMend")
QB = REPO / "benchmarks" / "QuixBugs"

if not REPO.exists():
    raise FileNotFoundError(
        f"MultiMend repo not found at {REPO}. "
        "Please run the clone cell first."
    )

if not (QB / "python_programs").exists():
    if QB.exists():
        shutil.rmtree(QB)

    subprocess.run([
        "git", "clone", "--depth", "1",
        "https://github.com/jkoppel/QuixBugs.git",
        str(QB)
    ], check=True)

print("QuixBugs files:")
for d in ["python_programs", "correct_python_programs", "python_testcases"]:
    p = QB / d
    print(
        d,
        "=>", p.exists(),
        "count=", len(list(p.glob("*.py"))) if p.exists() else 0
    )

In [ ]:
# Check what MultiMend itself actually references
!grep -RniE "from_pretrained|snapshot_download|huggingface|checkpoint" \
    /kaggle/working/MultiMend/src \
    --include="*.py" | head -200

xác định chính xác workflow/config của tác giả

In [ ]:
# Cell 7a — Inspect MultiMend model/config paths

print("=== configs.py ===")
print((REPO / "src" / "configs.py").read_text())

print("\n=== generate_primary_candidates.py (relevant section) ===")
lines = (REPO / "src" / "generate_primary_candidates.py").read_text().splitlines()
for i, line in enumerate(lines):
    if 180 <= i <= 235:
        print(f"{i+1}: {line}")

In [ ]:
# Cell 7b — Inspect existing model/results artifacts

from pathlib import Path

print("=== models/ ===")
models_dir = REPO / "models"

if models_dir.exists():
    for p in models_dir.rglob("*"):
        if p.is_file():
            print(p.relative_to(REPO))
else:
    print("No models directory yet.")

print("\n=== results/ ===")
results_dir = REPO / "results"

for p in results_dir.rglob("*"):
    if p.is_file():
        print(p.relative_to(REPO))

In [ ]:
# # Cell 7 — Download the OFFICIAL MultiMend fine-tuned checkpoint repository.
# # No API key is required for a public Hugging Face repository.

# from huggingface_hub import snapshot_download

# MODEL_REPO = "h4iku/multimend-codet5-small"
# MODEL_DIR = REPO / "models" / "multimend-codet5-small"
# MODEL_DIR.mkdir(parents=True, exist_ok=True)

# snapshot_download(
#     repo_id=MODEL_REPO,
#     local_dir=str(MODEL_DIR),
#     local_dir_use_symlinks=False,
# )

# print("Model snapshot:", MODEL_DIR)
# print("Checkpoint directories:")
# for p in sorted(MODEL_DIR.glob("checkpoint-*")):
#     print(" ", p.name)

In [ ]:
# Cell 8 — Inspect the official MultiMend training configuration

train_file = REPO / "src" / "train_model.py"
lines = train_file.read_text().splitlines()

for i, line in enumerate(lines, start=1):
    print(f"{i:3}: {line}")

tính chính xác số sample + số training steps + save_steps từ chính 4 dataset mà code dùng. (Chạy CPU thôi, không tốn GPU)

In [ ]:
# Cell 9 — Inspect official CoCoNuT training dataset sizes

from datasets import load_dataset

dataset_names = {
    "Python": "h4iku/coconut_python2010_preprocessed",
    "Java": "h4iku/coconut_java2006_preprocessed",
    "JavaScript": "h4iku/coconut_javascript2010_preprocessed",
    "C": "h4iku/coconut_c2005_preprocessed",
}

for prefix, name in dataset_names.items():
    print(f"\nLoading {prefix}: {name}")
    ds = load_dataset(name, split="train")
    print("raw samples:", len(ds))
    print("columns:", ds.column_names)

đã biết raw dataset tổng cộng khoảng 2.64 triệu samples, nhưng code còn filter rất nhiều sample. Cần tính số sample sau filter, vì đó mới quyết định 30 GPU-hours có đủ không.

In [ ]:
# Cell 10 — Reproduce the official filtering step and calculate training steps

from math import ceil
from datasets import load_dataset, concatenate_datasets
from transformers import AutoTokenizer

model_checkpoint = "Salesforce/codet5-small"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

dataset_names = {
    "Python": "h4iku/coconut_python2010_preprocessed",
    "Java": "h4iku/coconut_java2006_preprocessed",
    "JavaScript": "h4iku/coconut_javascript2010_preprocessed",
    "C": "h4iku/coconut_c2005_preprocessed",
}

max_input_length = 512
max_target_length = 256


def preprocess_function(prefix, examples):
    inputs = [
        f"{prefix} {ex.strip()} :".replace(
            tokenizer.eos_token, tokenizer.unk_token
        )
        for ex in examples["rem"]
    ]

    targets = [
        ex.strip().replace(
            tokenizer.eos_token, tokenizer.unk_token
        )
        for ex in examples["add"]
    ]

    contexts = [
        " ".join(ex.split()).replace(
            tokenizer.eos_token, tokenizer.unk_token
        )
        for ex in examples["context"]
    ]

    inputs_contexts = [
        f"{src} {ctx}" for src, ctx in zip(inputs, contexts)
    ]

    model_inputs = tokenizer(
        inputs_contexts,
        max_length=max_input_length,
        truncation=True,
    )

    model_inputs["inputs_only"] = tokenizer(inputs).input_ids

    labels = tokenizer(targets)
    model_inputs["labels"] = labels["input_ids"]

    return model_inputs


def allowed_length(example):
    return (
        len(example["inputs_only"]) <= max_input_length
        and 2 < len(example["labels"]) <= max_target_length
    )


filtered_datasets = []

for prefix, dataset_name in dataset_names.items():
    print(f"\nProcessing {prefix}...")

    raw_dataset = load_dataset(dataset_name, split="train")

    tokenized = raw_dataset.map(
        lambda ex: preprocess_function(prefix, ex),
        batched=True,
        remove_columns=raw_dataset.column_names,
        desc=f"Tokenizing {prefix}",
    )

    filtered = tokenized.filter(
        allowed_length,
        desc=f"Filtering {prefix}",
    ).remove_columns(["inputs_only"])

    print("Raw:", len(raw_dataset))
    print("After filter:", len(filtered))

    filtered_datasets.append(filtered)


concatenated_dataset = concatenate_datasets(filtered_datasets)

print("\n==============================")
print("FINAL DATASET")
print("==============================")
print("Total training samples:", len(concatenated_dataset))

train_batch_size = 8
epochs = 2

epoch_steps = ceil(len(concatenated_dataset) / train_batch_size)
train_steps = epoch_steps * epochs
save_steps = epoch_steps // 5

print("Steps / epoch:", epoch_steps)
print("Total training steps:", train_steps)
print("Checkpoint save_steps:", save_steps)
print("Expected checkpoints:", 10)

In [ ]:
# Cell 11 — Benchmark official MultiMend training speed
# Uses the exact official model/training batch size.
# Only 200 steps, then estimate full training time.

import time
import torch
from transformers import (
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
)

model_checkpoint = "Salesforce/codet5-small"

model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
)

benchmark_args = Seq2SeqTrainingArguments(
    output_dir=str(REPO / "benchmark_train"),
    per_device_train_batch_size=8,
    max_steps=200,
    fp16=True,
    learning_rate=1e-4,
    lr_scheduler_type="constant",
    logging_steps=50,
    save_strategy="no",
    report_to="none",
    remove_unused_columns=False,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=benchmark_args,
    train_dataset=concatenated_dataset,
    data_collator=data_collator,
    tokenizer=tokenizer,
)

print("Starting 200-step benchmark...")
start = time.time()

trainer.train()

elapsed = time.time() - start

print("\n==============================")
print("BENCHMARK")
print("==============================")
print(f"200 steps: {elapsed / 60:.2f} minutes")
print(f"Average: {elapsed / 200:.3f} sec/step")

estimated_hours = (elapsed / 200) * 581008 / 3600

print(f"Estimated full 581,008 steps: {estimated_hours:.2f} GPU hours")
print(f"30-hour budget remaining margin: {30 - estimated_hours:.2f} hours")

In [ ]:
from pathlib import Path
import shutil

src = Path(
    "/kaggle/input/datasets/thothanh28/"
    "checkpoint58100/checkpoint-58100"
)

dst = Path(
    "/kaggle/working/MultiMend/models/"
    "multimend-codet5-small/checkpoint-58100"
)

if not src.exists():
    raise FileNotFoundError(f"Checkpoint không tồn tại: {src}")

dst.parent.mkdir(parents=True, exist_ok=True)

if dst.exists():
    shutil.rmtree(dst)

shutil.copytree(src, dst)

print("Restored checkpoint:")
print(dst)
print()
print("Files:")

for p in sorted(dst.iterdir()):
    print(" -", p.name)

In [ ]:
from pathlib import Path
import shutil

src = Path(
    "/kaggle/input/datasets/honglcl/"
    "checkpoint-116200/checkpoint-116200"
)

dst = Path(
    "/kaggle/working/MultiMend/models/"
    "multimend-codet5-small/checkpoint-116200"
)

if not src.exists():
    raise FileNotFoundError(f"Checkpoint không tồn tại: {src}")

dst.parent.mkdir(parents=True, exist_ok=True)

if dst.exists():
    shutil.rmtree(dst)

shutil.copytree(src, dst)

print("Restored checkpoint:")
print(dst)
print()
print("Files:")

for p in sorted(dst.iterdir()):
    print(" -", p.name)

In [ ]:
from pathlib import Path
import shutil

src = Path(
    "/kaggle/input/datasets/honglcl/"
    "checkpoint174300/checkpoint-174300"
)

dst = Path(
    "/kaggle/working/MultiMend/models/"
    "multimend-codet5-small/checkpoint-174300"
)

if not src.exists():
    raise FileNotFoundError(f"Checkpoint không tồn tại: {src}")

dst.parent.mkdir(parents=True, exist_ok=True)

if dst.exists():
    shutil.rmtree(dst)

shutil.copytree(src, dst)

print("Restored checkpoint:")
print(dst)
print()
print("Files:")

for p in sorted(dst.iterdir()):
    print(" -", p.name)

In [ ]:
from pathlib import Path
import shutil

src = Path(
    "/kaggle/input/datasets/minhhanh123/"
    "checkpoint-232400/checkpoint-232400"
)

dst = Path(
    "/kaggle/working/MultiMend/models/"
    "multimend-codet5-small/checkpoint-232400"
)

if not src.exists():
    raise FileNotFoundError(f"Checkpoint không tồn tại: {src}")

dst.parent.mkdir(parents=True, exist_ok=True)

if dst.exists():
    shutil.rmtree(dst)

shutil.copytree(src, dst)

print("Restored checkpoint:")
print(dst)
print()
print("Files:")

for p in sorted(dst.iterdir()):
    print(" -", p.name)

In [ ]:
from pathlib import Path
import shutil

src = Path(
    "/kaggle/input/datasets/tramtvt/"
    "checkpoint348600/checkpoint-348600"
)

dst = Path(
    "/kaggle/working/MultiMend/models/"
    "multimend-codet5-small/checkpoint-348600"
)

if not src.exists():
    raise FileNotFoundError(f"Checkpoint không tồn tại: {src}")

dst.parent.mkdir(parents=True, exist_ok=True)

if dst.exists():
    shutil.rmtree(dst)

shutil.copytree(src, dst)

print("Restored checkpoint:")
print(dst)
print()
print("Files:")

for p in sorted(dst.iterdir()):
    print(" -", p.name)

In [ ]:
from pathlib import Path
import shutil

src = Path(
    "/kaggle/input/datasets/tramtvt/checkpoint406700/"
    "checkpoint-406700"
)

dst = Path(
    "/kaggle/working/MultiMend/models/"
    "multimend-codet5-small/checkpoint-406700"
)

if not src.exists():
    raise FileNotFoundError(f"Checkpoint không tồn tại: {src}")

dst.parent.mkdir(parents=True, exist_ok=True)

if dst.exists():
    shutil.rmtree(dst)

shutil.copytree(src, dst)

print("Restored checkpoint:")
print(dst)
print()
print("Files:")

for p in sorted(dst.iterdir()):
    print(" -", p.name)

In [ ]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for d in dirs:
        if "406700" in d:
            print("FOUND:", os.path.join(root, d))

In [ ]:
import os

print("WORLD_SIZE:", os.environ.get("WORLD_SIZE"))
print("LOCAL_RANK:", os.environ.get("LOCAL_RANK"))
print("RANK:", os.environ.get("RANK"))

mục tiêu giữ nguyên training config của MultiMend và chỉ thêm cơ chế auto-resume, dùng cell này. Nó sẽ tìm checkpoint-* mới nhất trong models/multimend-codet5-small/; nếu chưa có thì train từ đầu, nếu có thì resume từ checkpoint đó.

In [ ]:
# Cell 12 — Official MultiMend training with automatic checkpoint resume
#
# IMPORTANT:
# - Keeps the official MultiMend training configuration unchanged.
# - Only adds automatic checkpoint detection/resume.
# - Run this cell again in a new Kaggle session after restoring the
#   checkpoint directory.
#
# Expected checkpoint layout:
# /kaggle/working/MultiMend/models/multimend-codet5-small/
# ├── checkpoint-58100/
# ├── checkpoint-116200/
# ├── ...
#
# Do NOT delete optimizer.pt, scheduler.pt, trainer_state.json, etc.
# from the checkpoint if you want a proper training resume.

from pathlib import Path
import re
import torch

from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    DataCollatorForSeq2Seq,
    GenerationConfig,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
)

# ------------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------------

REPO = Path("/kaggle/working/MultiMend")
MODELS_ROOT = REPO / "models"
OUTPUT_DIR = MODELS_ROOT / "multimend-codet5-small"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Repository:", REPO)
print("Training output:", OUTPUT_DIR)
print("CUDA:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA:", torch.version.cuda)


# ------------------------------------------------------------------
# 2. Auto-detect latest valid checkpoint
# ------------------------------------------------------------------

def get_latest_checkpoint(output_dir: Path):
    checkpoints = []

    for p in output_dir.glob("checkpoint-*"):
        if not p.is_dir():
            continue

        match = re.fullmatch(r"checkpoint-(\d+)", p.name)
        if match:
            step = int(match.group(1))
            checkpoints.append((step, p))

    if not checkpoints:
        return None

    checkpoints.sort(key=lambda x: x[0])

    return checkpoints[-1][1]


latest_checkpoint = get_latest_checkpoint(OUTPUT_DIR)

if latest_checkpoint is None:
    print("\nNo existing checkpoint found.")
    print("Training will start from Salesforce/codet5-small.")
else:
    print("\nLatest checkpoint found:")
    print(" ", latest_checkpoint)

    # Useful sanity check
    required_files = [
        "trainer_state.json",
        "optimizer.pt",
        "scheduler.pt",
    ]

    missing = [
        f for f in required_files
        if not (latest_checkpoint / f).exists()
    ]

    if missing:
        raise RuntimeError(
            "Checkpoint appears incomplete.\n"
            f"Checkpoint: {latest_checkpoint}\n"
            f"Missing files: {missing}\n\n"
            "Do not resume from an incomplete checkpoint."
        )

    print("Checkpoint training state looks complete.")


# ------------------------------------------------------------------
# 3. Official base model
# ------------------------------------------------------------------

MODEL_CHECKPOINT = "Salesforce/codet5-small"

tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_CHECKPOINT)


# ------------------------------------------------------------------
# 4. IMPORTANT:
#    Reuse the tokenized/filtered training dataset from Cell 8/earlier.
#
#    This variable should already exist in the notebook:
#
#        concatenated_dataset
#
#    We deliberately do NOT recreate the 2.3M-example preprocessing here.
# ------------------------------------------------------------------

if "concatenated_dataset" not in globals():
    raise RuntimeError(
        "concatenated_dataset is not available.\n"
        "Run the official dataset preprocessing cell first."
    )

print("\nTraining dataset:")
print(concatenated_dataset)


# ------------------------------------------------------------------
# 5. Official MultiMend generation configuration
# ------------------------------------------------------------------

max_input_length = 512
max_target_length = 256

generation_config = GenerationConfig(
    max_length=max_target_length,
    min_length=0,
    early_stopping=True,
    num_beams=5,
)


# ------------------------------------------------------------------
# 6. Official MultiMend training configuration
# ------------------------------------------------------------------

train_batch_size = 8
eval_batch_size = 16

epochs = 2
lr = 1e-4

checkpoints_each_epoch = 5

epoch_steps = (
    len(concatenated_dataset) // train_batch_size
    + int(len(concatenated_dataset) % train_batch_size != 0)
)

train_steps = epoch_steps * epochs

save_steps = epoch_steps // checkpoints_each_epoch

print("\n==============================")
print("OFFICIAL TRAINING CONFIG")
print("==============================")
print("Dataset size:", len(concatenated_dataset))
print("Train batch size:", train_batch_size)
print("Epoch steps:", epoch_steps)
print("Total training steps:", train_steps)
print("Save steps:", save_steps)
print("Epochs:", epochs)
print("Learning rate:", lr)
print("FP16:", True)


# ------------------------------------------------------------------
# 7. Trainer
# ------------------------------------------------------------------

args = Seq2SeqTrainingArguments(
    output_dir=str(OUTPUT_DIR),

    learning_rate=lr,

    per_device_train_batch_size=train_batch_size,
    per_device_eval_batch_size=eval_batch_size,

    save_total_limit=epochs * checkpoints_each_epoch,

    max_steps=train_steps,

    save_steps=save_steps,

    predict_with_generate=True,

    fp16=True,

    lr_scheduler_type="constant",

    generation_config=generation_config,

    report_to="tensorboard",
)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=args,
    train_dataset=concatenated_dataset,
    data_collator=data_collator,
    tokenizer=tokenizer,
)


# ------------------------------------------------------------------
# 8. AUTO RESUME
# ------------------------------------------------------------------

print("\n==============================")
print("TRAINING")
print("==============================")

if latest_checkpoint is None:

    print("Starting training from scratch...")
    
    trainer.train(
        resume_from_checkpoint=False
    )

else:

    print(f"Resuming from: {latest_checkpoint}")

    trainer.train(
        resume_from_checkpoint=str(latest_checkpoint)
    )


# ------------------------------------------------------------------
# 9. Final status
# ------------------------------------------------------------------

print("\n==============================")
print("TRAINING SESSION FINISHED")
print("==============================")

latest_checkpoint = get_latest_checkpoint(OUTPUT_DIR)

if latest_checkpoint:
    print("Latest checkpoint:")
    print(latest_checkpoint)

    state_file = latest_checkpoint / "trainer_state.json"

    if state_file.exists():
        import json

        with open(state_file, "r") as f:
            state = json.load(f)

        print("Global step:", state.get("global_step"))
        print("Epoch:", state.get("epoch"))

print("\nAll checkpoint directories:")

for p in sorted(
    OUTPUT_DIR.glob("checkpoint-*"),
    key=lambda x: int(x.name.split("-")[-1])
):
    print(" ", p.name)

In [ ]:
from pathlib import Path

ckpt = Path(
    "/kaggle/working/MultiMend/"
    "models/multimend-codet5-small/checkpoint-464800"
)

print("Exists:", ckpt.exists())

if ckpt.exists():
    print("Files:")
    for p in ckpt.iterdir():
        print(" -", p.name)

In [ ]:
import shutil
from pathlib import Path

ckpt = Path(
    "/kaggle/working/MultiMend/"
    "models/multimend-codet5-small/checkpoint-464800"
)

zip_path = Path("/kaggle/working/checkpoint-464800")

shutil.make_archive(
    str(zip_path),
    "zip",
    root_dir=ckpt.parent,
    base_dir=ckpt.name
)

final_zip = Path("/kaggle/working/checkpoint-464800.zip")

print("Created:", final_zip)
print("Size:", round(final_zip.stat().st_size / 1024**3, 2), "GB")

In [ ]:
!ls -lh /kaggle/working/kaggle_upload/

In [ ]:
# ==========================================
# CREATE KAGGLE DATASET - checkpoint464800
# ==========================================

import os
import json
import shutil

# ------------------------------
# 1. Cấu hình
# ------------------------------

USERNAME = "tramtvt"
DATASET_NAME = "checkpoint464800"

SOURCE_FILE = "/kaggle/working/checkpoint-464800.zip"
UPLOAD_DIR = "/kaggle/working/kaggle_upload"

DATASET_ID = f"{USERNAME}/{DATASET_NAME}"

# ------------------------------
# 2. Kiểm tra file checkpoint
# ------------------------------

if not os.path.isfile(SOURCE_FILE):
    raise FileNotFoundError(
        f"Không tìm thấy file:\n{SOURCE_FILE}"
    )

file_size = os.path.getsize(SOURCE_FILE)

print("Checkpoint found:")
print(SOURCE_FILE)
print(f"Size: {file_size / (1024**3):.3f} GB")

# ------------------------------
# 3. Xóa thư mục upload cũ
# ------------------------------

if os.path.exists(UPLOAD_DIR):
    shutil.rmtree(UPLOAD_DIR)

os.makedirs(UPLOAD_DIR, exist_ok=True)

# ------------------------------
# 4. Copy checkpoint
# ------------------------------

destination = os.path.join(
    UPLOAD_DIR,
    "checkpoint-464800.zip"
)

shutil.copy2(
    SOURCE_FILE,
    destination
)

# ------------------------------
# 5. Tạo metadata
# ------------------------------

metadata = {
    "title": DATASET_NAME,
    "id": DATASET_ID,
    "description": "Training checkpoint 464800",
    "licenses": [
        {
            "name": "Unknown"
        }
    ]
}

metadata_file = os.path.join(
    UPLOAD_DIR,
    "dataset-metadata.json"
)

with open(metadata_file, "w") as f:
    json.dump(
        metadata,
        f,
        indent=2
    )

# ------------------------------
# 6. Kiểm tra trước khi upload
# ------------------------------

print("\n================================")
print("FILES TO UPLOAD")
print("================================")

for filename in os.listdir(UPLOAD_DIR):
    path = os.path.join(UPLOAD_DIR, filename)
    size = os.path.getsize(path)

    print(
        f"{filename:30s} "
        f"{size / (1024**2):.2f} MB"
    )

print("\n================================")
print("METADATA")
print("================================")

print(
    json.dumps(
        metadata,
        indent=2
    )
)

In [ ]:
!kaggle datasets create \
    -p /kaggle/working/kaggle_upload \
    --public

In [ ]:
import os
import shutil

# Xóa dataset-metadata.json
metadata = "/kaggle/working/dataset-metadata.json"
if os.path.exists(metadata):
    os.remove(metadata)

# Xóa thư mục kaggle_upload
upload_dir = "/kaggle/working/kaggle_upload"
if os.path.exists(upload_dir):
    shutil.rmtree(upload_dir)

print("Đã xóa.")

In [ ]:
!kaggle config view

In [ ]:
from pathlib import Path

zip_path = Path("/kaggle/working/checkpoint-174300.zip")

print("Exists:", zip_path.exists())

if zip_path.exists():
    print("Path:", zip_path)
    print("Size:", round(zip_path.stat().st_size / 1024**2, 2), "MB")